"""Exact offline HTML, normal UI actions, accelerated local simulation.
Starts from an earned checkpoint generated by chapter_journey.cjs (no granted
inventory there). Storage is an explicit Map fixture, not native-origin
persistence certification. Known-answer failure cases use isolated save fixtures.
"""
from pathlib import Path
import json, hashlib, traceback
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'evidence07'/'chapter1';OUT.mkdir(exist_ok=True)
H=(ROOT/'FIRSTLIGHT_VALLEY.html').read_text();START=json.loads((OUT/'OPTIONAL_CHAPTER_START.json').read_text())
REPORT={'build_sha256':hashlib.sha256(H.encode()).hexdigest(),'method':__doc__,'checks':[],'errors':[]}
def check(name,v):
 REPORT['checks'].append({'check':name,'passed':bool(v)});print(('PASS ' if v else 'FAIL ')+name,flush=True)
 if not v:raise AssertionError(name)
ARGS=['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=gl-egl','--enable-webgl','--ignore-gpu-blocklist','--disable-gpu-sandbox']
try:
 with sync_playwright() as pw:
  b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=ARGS)
  errors=[];requests=[]
  def spawn(ctx,storage=None,fallback=False):
   p=ctx.new_page();p.on('pageerror',lambda e:errors.append(str(e)));p.on('request',lambda r:requests.append(r.url))
   p.evaluate('''({storage,fallback})=>{window.__ETERNITIES_TEST_MODE=true;window.__ETERNITIES_CAPTURE_MODE=true;window.ST=new Map(Object.entries(storage||{}));Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>ST.get(k)||null,setItem:(k,v)=>ST.set(k,String(v)),removeItem:k=>ST.delete(k)}});if(fallback){const old=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return t==='webgl2'?null:old.call(this,t,...a)}}}''',{'storage':storage or {},'fallback':fallback})
   p.set_content(H,wait_until='load');p.wait_for_function('window.Realm');p.wait_for_timeout(650);p.evaluate('Realm.test.quality("low");Realm.test.render()');return p
  ctx=b.new_context(viewport={'width':1440,'height':960},offline=True,accept_downloads=True)
  p=spawn(ctx,{'eternities.realm06.save.v5':json.dumps(START)})
  def advance(t,render=False):
   p.evaluate('(t)=>Realm.test.step(t)',t)
   if render:p.evaluate('Realm.test.render()')
  def panel():
   if p.locator('#drawer').evaluate('(e)=>e.classList.contains("open")'):p.click('#close-panel')
   p.click('#adventure-open');p.wait_for_timeout(220)
  def walk(x,z):
   if p.locator('#drawer').evaluate('(e)=>e.classList.contains("open")'):p.click('#close-panel')
   check('Accepted movement '+str((x,z)),p.evaluate('([x,z])=>Realm.test.move(x,z).ok',[x,z]))
   for _ in range(500):
    if not p.evaluate('Realm.test.path.length'):break
    if p.evaluate('Realm.state.adventure.hp')<60 and p.locator('#battle-heal').is_visible() and p.locator('#battle-heal').is_enabled():p.click('#battle-heal')
    advance(.15)
   p.evaluate('Realm.test.render()');pos=p.evaluate('Realm.diagnostics.adventure.player');check('Reached '+str((x,z)),((pos['x']-x)**2+(pos['z']-z)**2)**.5<.15)
  def click_ground(x,z):
   p.evaluate('Realm.test.render()');point=p.evaluate('([x,z])=>Realm.project(x,1.3,z)',[x,z]);p.mouse.click(point['x'],point['y'])
  def fight(id):
   panel();p.click('[data-action="adv-seek"][data-id="'+id+'"]')
   for _ in range(200):
    hp=p.evaluate('Realm.state.adventure.hp')
    if p.evaluate('(id)=>Realm.state.adventure.defeated.includes(id)',id):break
    if hp<65 and p.locator('#battle-heal').is_enabled():p.click('#battle-heal')
    if p.locator('#battle-pulse').is_enabled() and p.evaluate('Realm.state.adventure.stamina')>=55:p.click('#battle-pulse')
    advance(.25)
    if p.evaluate('Realm.state.adventure.hp')<=0:raise AssertionError('Automated browser journey died before '+id)
   check('Defeated through actual attack UI: '+id,p.evaluate('(id)=>Realm.state.adventure.defeated.includes(id)',id));p.evaluate('Realm.test.render()')
  check('Realm 08 preserves chapter I in offline WebGL2',p.evaluate('Realm.diagnostics.version')=='8.0.0' and p.evaluate('Realm.diagnostics.mode')=='webgl2')
  check('Earned starter supplies restored',p.evaluate('Realm.state.adventure.started&&Realm.state.sandbox.bridge&&Realm.state.sandbox.inventory.pick===1'))
  p.click('#interact');p.evaluate('Realm.test.render()');check('Normal interaction enters mine',p.evaluate('Realm.diagnostics.scene')=='mine')
  check('Mine contains actual separate geometry',p.evaluate('Realm.diagnostics.metrics.instances')>300)
  p.screenshot(path=str(OUT/'06-underways-overview.png'),timeout=30000)
  p.click('#explore');p.click('[data-action="place-action"][data-id="home"]');check('Outdoor interaction cannot bypass mine exit',p.evaluate('Realm.diagnostics.scene')=='mine');p.click('#close-panel')
  check('Outdoor destination API refuses route from mine',p.evaluate('Realm.navigate("home")') is False)
  walk(0,4);click_ground(0,2);advance(2,True)
  check('Canvas stone click excavates a real cell',p.evaluate('Realm.state.adventure.dug.includes("0,1")'))
  check('Removed stone is navigable',p.evaluate('RealmAdventure.walkable(Realm.state.adventure,0,2)'))
  check('Correct reflection method remains',p.evaluate('Realm.diagnostics.reflection.method')=='world-plane P*V*H')
  fight('briar-1');walk(-4,2);p.keyboard.press('e');check('Interaction claims a real cache',p.evaluate('Realm.state.adventure.coins')==3)
  walk(-8,2);p.click('#interact');check('Fox rescue establishes a bond',p.evaluate('Realm.state.adventure.companion.bonded'))
  panel();p.fill('#companion-name','<b>Willow</b>');p.click('[data-action="adv-rename"]');check('Companion text does not create markup',p.locator('#drawer-body h3 b').count()==0 and p.evaluate('Realm.state.adventure.companion.name')=='<b>Willow</b>')
  p.fill('#companion-name','Willow');p.click('[data-action="adv-rename"]');p.click('[data-action="adv-mode"][data-id="stay"]');p.click('#close-panel');before=p.evaluate('Realm.diagnostics.adventure.companion');walk(-6,2);advance(1,True)
  after=p.evaluate('Realm.diagnostics.adventure.companion');check('Stay keeps fox in place',before['x']==after['x'] and before['z']==after['z'])
  panel();p.click('[data-action="adv-mode"][data-id="follow"]');p.click('#close-panel');advance(2);check('Follow is accepted',p.evaluate('Realm.state.adventure.companion.mode')=='follow')
  fight('briar-2');walk(0,-3);p.keyboard.press('e');check('Second cache awarded once',p.evaluate('Realm.state.adventure.coins')==7)
  walk(2,-4);click_ground(4,-4);advance(2,True);check('Second barrier excavates via world click',p.evaluate('Realm.state.adventure.dug.includes("2,-2")'))
  fight('sentinel');walk(8,-3);p.click('#interact');panel();p.click('[data-action="adv-equip"][data-id="guard_vest"]');check('Armor changes defense',p.evaluate('Realm.diagnostics.adventure.stats.defense')==4);p.click('#close-panel')
  walk(8,-5.7);advance(.3,True);p.evaluate('Realm.test.view({overview:false,half:12,center:[8,2,-6]});Realm.test.render()');p.screenshot(path=str(OUT/'06-guardian-approach.png'),timeout=30000)
  fight('hart');walk(8,-10);p.click('#interact');check('Guardian defeat enables relic collection',p.evaluate('Realm.state.adventure.relic'))
  p.click('#interact');check('Guardian cache adds ore and sunmarks',p.evaluate('Realm.state.adventure.coins')==25)
  p.evaluate('Realm.test.quality("balanced");Realm.test.view({overview:true});Realm.test.render()');p.screenshot(path=str(OUT/'06-cleared-underways.png'),timeout=30000)
  walk(0,11);p.keyboard.press('e');p.evaluate('Realm.test.render()');check('Exit returns to actual mine entrance',p.evaluate('Realm.diagnostics.scene')=='valley' and p.evaluate('Math.hypot(Realm.state.player.x,Realm.state.player.z+48)<.2'))
  p.evaluate('Realm.test.quality("low")');panel();p.click('[data-action="adv-go"][data-id="workshop"]');advance(70,True);panel();p.click('[data-action="adv-forge"]');p.click('[data-action="adv-equip"][data-id="copper_blade"]');check('Forge/equip uses materials for actual weapon',p.evaluate('Realm.state.adventure.equipment.weapon')=='copper_blade' and p.evaluate('Realm.state.adventure.coins')==21)
  p.click('[data-action="adv-go"][data-id="spring"]');advance(30,True)
  if p.locator('#drawer').evaluate('(e)=>e.classList.contains("open")'):p.click('#close-panel')
  p.click('#interact');check('Relic opens story dialog',p.locator('#story-dialog').is_visible());check('Story pauses simulation',p.evaluate('Realm.diagnostics.adventure.paused'))
  check('Warning states the narrative stakes','Heaven is under attack' in p.evaluate('RealmAdventure.STORY.map(x=>x.body).join(" ")'))
  p.screenshot(path=str(OUT/'06-envoy-dialogue.png'),timeout=30000)
  p.locator('#story-buttons button').click();p.locator('#story-buttons button').click();check('Final page offers two alternatives',p.locator('#story-buttons button').count()==2)
  p.locator('#story-buttons button').filter(has_text='Endurance').click();check('One gift persists and dialog closes',p.evaluate('Realm.state.adventure.reward')=='warden_stone' and not p.locator('#story-dialog').is_visible())
  check('Story restores preceding pause state',not p.evaluate('Realm.diagnostics.adventure.paused'))
  panel();p.click('[data-action="adv-equip"][data-id="warden_stone"]');check('Charm changes health capacity',p.evaluate('Realm.diagnostics.adventure.stats.maxHP')==170);p.click('#close-panel')
  p.evaluate('Realm.test.quality("balanced");Realm.test.setTime(17.5);Realm.test.view({overview:false,half:12});Realm.test.render()');p.wait_for_timeout(200);p.screenshot(path=str(OUT/'06-envoy-and-companion.png'),timeout=30000)
  check('All chapter objectives complete',p.evaluate('RealmAdventure.objectives(Realm.state.adventure).every(x=>x.done)'))
  check('Existing composition preserved',p.evaluate('Realm.state.score')==START['score'])
  p.click('#chronicle')
  with p.expect_download() as dl:p.click('[data-action="export"]')
  payload=Path(dl.value.path()).read_bytes();(OUT/'BROWSER_CHAPTER_COMPLETED.json').write_bytes(payload)
  check('Export includes current world and chapter state',json.loads(payload)['version']==p.evaluate('RealmCore.VERSION') and json.loads(payload)['adventure']['reward']=='warden_stone')
  p.on('dialog',lambda d:d.accept());bad=json.loads(payload);bad['adventure']['ore']=-1;prior=p.evaluate('JSON.stringify(Realm.state)');p.set_input_files('#import-file',{'name':'invalid.json','mimeType':'application/json','buffer':json.dumps(bad).encode()});p.wait_for_timeout(150)
  check('Invalid chapter import cannot mutate state',p.evaluate('JSON.stringify(Realm.state)')==prior)
  p.evaluate('Realm.test.save()');storage=p.evaluate('Object.fromEntries(ST)');expected=p.evaluate('Realm.state');p.close();p=spawn(ctx,storage)
  check('Cold page restores exact adventure state',p.evaluate('Realm.state.adventure')==expected['adventure'])
  check('Cold page restores sandbox, score and room',p.evaluate('Realm.state.sandbox')==expected['sandbox'] and p.evaluate('Realm.state.score')==expected['score'] and p.evaluate('Realm.state.retreat')==expected['retreat'])
  check('Cold page never autoplays audio',p.evaluate('Realm.diagnostics.audio.state')=='not-created')
  p.click('#interact');p.locator('#story-buttons button').click();p.locator('#story-buttons button').click();check('Repeat story has no duplicate reward',p.locator('#story-buttons button').count()==1);p.locator('#story-buttons button').click()
  fallen=expected.copy();fallen['adventure']=dict(expected['adventure']);fallen['adventure']['hp']=0;p.evaluate('(x)=>{Realm.test.replace(x);Realm.test.render()}',fallen)
  check('Zero health presents recovery dialog',p.locator('#fallen-dialog').is_visible());p.click('#revive-button');check('Recovery restores health and retains earned items',p.evaluate('Realm.state.adventure.hp')>0 and p.evaluate('Realm.state.adventure.reward')=='warden_stone')
  ctx.close()
  mob=b.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True,offline=True);p=spawn(mob,{'eternities.realm06.save.v5':json.dumps(START)});p.click('#interact');p.evaluate('Realm.test.render()')
  check('Touch-sized mine loads WebGL2',p.evaluate('Realm.diagnostics.scene')=='mine' and p.evaluate('Realm.diagnostics.mode')=='webgl2')
  check('No mobile horizontal overflow',p.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  for sel in ['#battle-strike','#battle-pulse','#battle-dodge','#battle-heal','#interact','#chapter-open']:
   box=p.locator(sel).bounding_box();check('Touch control fits '+sel,box and box['x']>=0 and box['y']>=0 and box['x']+box['width']<=390.5 and box['y']+box['height']<=844)
  p.click('#battle-dodge');check('Touch dodge spends stamina',p.evaluate('Realm.state.adventure.stamina')==78);p.evaluate('Realm.test.render()');p.screenshot(path=str(OUT/'06-mobile-underways.png'),timeout=30000)
  p.click('#chapter-open');check('Touch chapter has accessible route buttons',p.locator('[data-action="adv-seek"]').count()==7);mob.close()
  fb=b.new_context(viewport={'width':1000,'height':800},offline=True);p=spawn(fb,{'eternities.realm06.save.v5':json.dumps(START)},True);p.click('#interact');p.evaluate('Realm.test.render()');check('Map fallback enters same cave',p.evaluate('Realm.diagnostics.mode')=='map' and p.evaluate('Realm.diagnostics.scene')=='mine');p.click('#battle-pulse');check('Map fallback uses same combat rules',p.evaluate('Realm.state.adventure.stamina')==70);p.click('#interact');check('Map fallback exits cave',p.evaluate('Realm.diagnostics.scene')=='valley');fb.close()
  check('No unhandled JavaScript errors',not errors);check('No external requests',not requests);REPORT['requests']=requests;REPORT['browser_errors']=errors;b.close()
except Exception as e:
 REPORT['errors'].append(str(e));REPORT['traceback']=traceback.format_exc();print(REPORT['traceback'],flush=True)
finally:
 REPORT['passed']=not REPORT['errors'] and all(x['passed'] for x in REPORT['checks']);REPORT['checks_passed']=sum(x['passed'] for x in REPORT['checks']);(OUT/'ADVENTURE_BROWSER_REPORT.json').write_text(json.dumps(REPORT,indent=2));print(json.dumps({'passed':REPORT['passed'],'checks':REPORT['checks_passed'],'errors':REPORT['errors']}),flush=True)
