/* Known-answer unit fixtures deliberately set test positions and inventory.
 * arsenal_journey.cjs separately earns resources and medals through commands. */
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const C=require('../src/core.js'),A=require('../src/adventure.js'),AR=require('../src/arsenal.js'),R=require('../src/road.js');let seq=0;
const cmd=(s,t,p={})=>s.adventureCommand('arsenal-unit-'+(++seq),t,p);
const snapshot=s=>JSON.stringify(s.snapshot());
function step(s,t){for(let i=0;i<Math.round(t*20);i++)s.tick(.05);}
function bench(){const s=new C.Simulation();s.state.player={x:11,z:9,yaw:0};assert.ok(cmd(s,'start').ok);return s;}
function materials(s){Object.assign(s.state.sandbox.inventory,{wood:100,fiber:100,stone:100,plank:100,crystal:100});s.state.adventure.ore=100;s.state.adventure.coins=100;return s;}
function equipped(){const s=materials(bench());assert.ok(cmd(s,'arsenal-craft',{id:'trail_bow'}).ok);assert.ok(cmd(s,'equip',{id:'trail_bow'}).ok);return s;}
function range(){const s=equipped();assert.ok(cmd(s,'range-enter').ok);s.state.player={x:0,z:1,yaw:Math.PI};return s;}
function reject(s,t,p={}){const before=snapshot(s);const r=cmd(s,t,p);assert.equal(r.ok,false,JSON.stringify(r));assert.equal(snapshot(s),before);return r;}
function hostile(){const s=equipped();s.state.sandbox.bridge=true;s.state.sandbox.inventory.pick=1;s.state.player={x:0,z:-48,yaw:0};assert.ok(cmd(s,'enter').ok);s.state.player={x:0,z:8,yaw:Math.PI};const r=A.runtime(s);r.enemies=[{id:'briar-1',kind:'skitter',x:0,z:4,hp:100,maxHP:100,damage:0,xp:20,ore:1,coins:3,mode:'recover',timer:100,path:[],home:{x:0,z:4}}];return s;}
function win(s){cmd(s,'range-start');s.state.adventure.elapsed+=10;for(const t of A.runtime(s).enemies){AR.practiceHit(s,t);AR.practiceHit(s,t);}}

test('version07 raw save migrates without losing road or creative state',()=>{const raw=JSON.parse(fs.readFileSync(require.resolve('../examples/CHAPTER_II_COMPLETE_EARNED.json')));assert.equal(raw.version,6);assert.equal(raw.adventure.version,2);const before=JSON.stringify(raw),n=C.validate(raw);assert.equal(n.version,C.VERSION);assert.equal(n.adventure.version,A.VERSION);for(const k of['score','retreat','visitor','sandbox','notes','flowers'])assert.deepEqual(n[k],raw[k]);assert.deepEqual(n.adventure.road,raw.adventure.road);assert.deepEqual(n.adventure.arsenal,AR.fresh());assert.equal(JSON.stringify(raw),before);});
test('legacy storage key is copied not overwritten',()=>{const raw=JSON.parse(fs.readFileSync(require.resolve('../examples/CHAPTER_II_COMPLETE_EARNED.json'))),text=JSON.stringify(raw),m=new Map([['eternities.realm07.save.v6',text]]),store={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};const load=C.load(store);assert.equal(load.status,'migrated');new C.Simulation(load.state).save(store);assert.equal(m.get('eternities.realm07.save.v6'),text);assert.equal(JSON.parse(m.get(C.KEY)).version,C.VERSION);});
test('fresh arsenal has no free bows gems or medals',()=>{const s=C.fresh();assert.deepEqual(s.adventure.arsenal,AR.fresh());assert.equal(s.adventure.owned.length,0);assert.equal(AR.weapon(s.adventure).style,'blade');});
test('gem records reject invalid quantities and unknown fields',()=>{for(const n of[-1,1.2,10000,Infinity,NaN,'1']){const s=bench().snapshot();s.adventure.arsenal.gems.ruby=n;assert.throws(()=>C.validate(s));}const s=bench().snapshot();s.adventure.arsenal.gems.fake=1;assert.throws(()=>C.validate(s));});
test('socket validation needs owned weapon and known gem',()=>{for(const [id,g]of[['__proto__','ruby'],['travel_coat','ruby'],['trail_bow','ruby'],['trail_blade','fake']]){const s=bench().snapshot();Object.defineProperty(s.adventure.arsenal.sockets,id,{enumerable:true,value:g});assert.throws(()=>C.validate(s));}});
test('medal requires bounded completion time and vice versa',()=>{for(const [medal,time]of[[true,null],[false,12],[true,31],[true,0],[true,-1],[true,Infinity]]){const s=bench().snapshot();Object.assign(s.adventure.arsenal,{rangeMedal:medal,bestTime:time});assert.throws(()=>C.validate(s));}});
test('unstarted record cannot mint loose gems or a medal',()=>{for(const prop of['gem','medal']){const s=C.fresh();if(prop==='gem')s.adventure.arsenal.gems.amber=1;else Object.assign(s.adventure.arsenal,{rangeMedal:true,bestTime:10});assert.throws(()=>C.validate(s));}});
test('craft refuses before supplies, remote bench, paused or unknown recipe',()=>{const s=new C.Simulation();reject(s,'arsenal-craft',{id:'trail_bow'});const t=materials(bench());t.state.player={x:0,z:3,yaw:0};reject(t,'arsenal-craft',{id:'trail_bow'});t.state.player={x:11,z:9,yaw:0};reject(t,'arsenal-craft',{id:'__proto__'});t.paused=true;reject(t,'arsenal-craft',{id:'trail_bow'});});
test('bow recipe consumes exact wood fiber stone and creates a unique item',()=>{const s=materials(bench());cmd(s,'arsenal-craft',{id:'trail_bow'});assert.equal(s.state.sandbox.inventory.wood,94);assert.equal(s.state.sandbox.inventory.fiber,96);assert.equal(s.state.sandbox.inventory.stone,98);assert.ok(s.state.adventure.owned.includes('trail_bow'));assert.equal(s.state.adventure.equipment.weapon,'trail_blade');reject(s,'arsenal-craft',{id:'trail_bow'});});
test('insufficient material on any ingredient causes no partial charge',()=>{for(const k of['wood','fiber','stone']){const s=materials(bench());s.state.sandbox.inventory[k]=0;reject(s,'arsenal-craft',{id:'trail_bow'});}});
test('longbow requires original bow then keeps it and charges exact components',()=>{const s=materials(bench());reject(s,'arsenal-craft',{id:'copper_bow'});cmd(s,'arsenal-craft',{id:'trail_bow'});cmd(s,'arsenal-craft',{id:'copper_bow'});assert.equal(s.state.adventure.ore,96);assert.equal(s.state.adventure.coins,94);assert.equal(s.state.sandbox.inventory.plank,98);assert.ok(s.state.adventure.owned.includes('trail_bow'));assert.ok(s.state.adventure.owned.includes('copper_bow'));});
test('craft duplicate id never charges twice and changed content is refused',()=>{const s=materials(bench());const p={id:'trail_bow'};assert.ok(s.adventureCommand('fixed','arsenal-craft',p).ok);const before=snapshot(s);assert.ok(s.adventureCommand('fixed','arsenal-craft',p).duplicate);assert.equal(snapshot(s),before);assert.equal(s.adventureCommand('fixed','arsenal-craft',{id:'ruby'}).ok,false);assert.equal(snapshot(s),before);});
test('gem crafting charges correct actual material and currency balances',()=>{const s=materials(bench());for(const id of['ruby','moonstone','amber'])assert.ok(cmd(s,'arsenal-craft',{id}).ok);assert.deepEqual(s.state.adventure.arsenal.gems,{ruby:1,moonstone:1,amber:1});assert.equal(s.state.adventure.ore,97);assert.equal(s.state.adventure.coins,93);assert.equal(s.state.sandbox.inventory.crystal,98);assert.equal(s.state.sandbox.inventory.fiber,95);assert.equal(s.state.sandbox.inventory.wood,98);});
test('gem capacity, ore and coin refusals are atomic',()=>{const s=materials(bench());s.state.adventure.arsenal.gems.ruby=9999;reject(s,'arsenal-craft',{id:'ruby'});s.state.adventure.arsenal.gems.ruby=0;s.state.adventure.ore=0;reject(s,'arsenal-craft',{id:'ruby'});s.state.adventure.ore=10;s.state.adventure.coins=0;reject(s,'arsenal-craft',{id:'ruby'});});
test('socket requires actual outdoor workbench and loose gem',()=>{const s=equipped();reject(s,'socket',{weapon:'trail_bow',gem:'ruby'});cmd(s,'arsenal-craft',{id:'ruby'});s.state.player={x:0,z:3,yaw:0};reject(s,'socket',{weapon:'trail_bow',gem:'ruby'});s.state.player={x:11,z:9,yaw:0};cmd(s,'range-enter');reject(s,'socket',{weapon:'trail_bow',gem:'ruby'});});
test('fitting replacing reclaiming preserves total gem quantities',()=>{const s=equipped();cmd(s,'arsenal-craft',{id:'ruby'});cmd(s,'arsenal-craft',{id:'moonstone'});cmd(s,'socket',{weapon:'trail_bow',gem:'ruby'});assert.equal(s.state.adventure.arsenal.gems.ruby,0);cmd(s,'socket',{weapon:'trail_bow',gem:'moonstone'});assert.equal(s.state.adventure.arsenal.gems.ruby,1);assert.equal(s.state.adventure.arsenal.gems.moonstone,0);cmd(s,'socket',{weapon:'trail_bow',gem:null});assert.equal(s.state.adventure.arsenal.gems.moonstone,1);assert.equal(s.state.adventure.arsenal.sockets.trail_bow,undefined);});
test('socket changes stats only for currently equipped weapon',()=>{const s=equipped(),v=s.state.adventure;cmd(s,'arsenal-craft',{id:'ruby'});cmd(s,'socket',{weapon:'trail_blade',gem:'ruby'});assert.equal(A.stats(v).attack,13);cmd(s,'equip',{id:'trail_blade'});assert.equal(A.stats(v).attack,20);cmd(s,'equip',{id:'trail_bow'});assert.equal(A.stats(v).attack,13);});
test('moonstone raises capacity without healing and removal clamps current HP',()=>{const s=equipped(),v=s.state.adventure;cmd(s,'arsenal-craft',{id:'moonstone'});v.hp=50;cmd(s,'socket',{weapon:'trail_bow',gem:'moonstone'});assert.equal(A.stats(v).maxHP,118);assert.equal(v.hp,50);v.hp=118;cmd(s,'socket',{weapon:'trail_bow',gem:null});assert.equal(A.stats(v).maxHP,100);assert.equal(v.hp,100);});
test('socket rejects same setting, wrong slot, foreign weapon, unknown gem',()=>{const s=equipped();for(const p of[{weapon:'trail_bow',gem:null},{weapon:'travel_coat',gem:'ruby'},{weapon:'dawn_edge',gem:'ruby'},{weapon:'trail_bow',gem:'__proto__'}])reject(s,'socket',p);});
test('full reclaim pouch prevents swap without consuming new gem',()=>{const s=equipped(),a=s.state.adventure;a.arsenal.gems.ruby=1;cmd(s,'socket',{weapon:'trail_bow',gem:'ruby'});a.arsenal.gems.ruby=9999;a.arsenal.gems.amber=1;reject(s,'socket',{weapon:'trail_bow',gem:'amber'});reject(s,'socket',{weapon:'trail_bow',gem:null});});
test('socket duplicate cannot charge, reclaim or alter stats twice',()=>{const s=equipped();s.state.adventure.arsenal.gems.ruby=1;const p={weapon:'trail_bow',gem:'ruby'};s.adventureCommand('socket-once','socket',p);const old=snapshot(s);assert.ok(s.adventureCommand('socket-once','socket',p).duplicate);assert.equal(snapshot(s),old);});
test('range entry checks workshop proximity and prepared character',()=>{reject(new C.Simulation(),'range-enter');const s=bench();s.state.player={x:0,z:3,yaw:0};reject(s,'range-enter');s.state.player={x:11,z:9,yaw:0};assert.ok(cmd(s,'range-enter').ok);assert.equal(s.room,'range');reject(s,'range-enter');});
test('range collision bounds and pillars affect real walking',()=>{for(const [x,z]of[[0,9],[-6,-5],[0,-8],[6,-5]])assert.ok(AR.rangeWalkable(x,z));for(const q of[[14,0],[0,-13],[-3,0],[3,0],[NaN,0],[0,Infinity]])assert.equal(AR.rangeWalkable(...q),false);const s=range();assert.equal(s.moveTo(3,0).ok,false);});
test('range path routes around a pillar, not through it',()=>{const s=range(),path=C.pathfind({x:3,z:3},{x:3,z:-3},s.navRoom);assert.ok(path);let last={x:3,z:3};for(const p of path){assert.ok(C.segment(last,p,s.navRoom));last=p;}assert.ok(path.some(p=>Math.abs(p.x-3)>.8));});
test('range south exit requires proximity and restores workshop position',()=>{const s=range();reject(s,'range-leave');s.state.player={...AR.RANGE.entry};assert.ok(cmd(s,'range-leave').ok);assert.equal(s.room,null);assert.equal(s.state.player.x,11);assert.equal(s.state.player.z,9);});
test('save inside court restores outside without unfinished arrows or round',()=>{const s=range();cmd(s,'range-start');cmd(s,'attack',{target:'range-mid'});const cold=new C.Simulation(s.snapshot());assert.equal(cold.room,null);assert.equal(cold.state.player.x,11);assert.equal(AR.runtime(cold).arrows.length,0);assert.equal(AR.runtime(cold).range.active,false);});
test('bow provides ranged profile while all previous blades keep their reach',()=>{const s=equipped(),v=s.state.adventure;assert.deepEqual(AR.weapon(v),{style:'bow',reach:11,cooldown:.75,stamina:6,primary:'Loose arrow',special:'Piercing light'});v.equipment.weapon='copper_blade';assert.equal(AR.weapon(v).reach,2.65);});
test('bows refuse village shots and blades refuse practice target attacks',()=>{const s=equipped();reject(s,'attack');const t=range();cmd(t,'equip',{id:'trail_blade'});reject(t,'attack',{target:'range-mid'});reject(t,'pulse');});
test('launch spends exact stamina and damage is delayed until actual travel',()=>{const s=hostile(),e=A.runtime(s).enemies[0];assert.ok(cmd(s,'attack',{target:e.id}).ok);assert.equal(e.hp,100);assert.equal(s.state.adventure.stamina,94);step(s,.05);assert.equal(e.hp,100);step(s,.25);assert.equal(e.hp,87);assert.equal(AR.runtime(s).arrows.length,0);});
test('cooldown and low stamina refusals do not consume resources',()=>{const s=hostile();cmd(s,'attack',{target:'briar-1'});reject(s,'attack',{target:'briar-1'});step(s,1);s.state.adventure.stamina=5;reject(s,'attack',{target:'briar-1'});s.state.adventure.stamina=29;reject(s,'pulse',{target:'briar-1'});});
test('unknown out of range and obstructed targets do not launch',()=>{const s=hostile(),e=A.runtime(s).enemies[0];reject(s,'attack',{target:'not-there'});e.z=-4;reject(s,'attack',{target:e.id});e.x=4;e.z=5;reject(s,'attack',{target:e.id});assert.equal(AR.runtime(s).arrows.length,0);});
test('arrow direction is fixed and can miss a moving enemy',()=>{const s=hostile(),e=A.runtime(s).enemies[0];cmd(s,'attack',{target:e.id});const dir={...AR.runtime(s).arrows[0]};e.x=2;step(s,.5);assert.equal(e.hp,100);const q=AR.runtime(s).arrows[0];if(q){assert.equal(q.dx,dir.dx);assert.equal(q.dz,dir.dz);}});
test('damage snapshots the launch gear, not later equipped weapon',()=>{const s=hostile(),e=A.runtime(s).enemies[0];cmd(s,'attack',{target:e.id});cmd(s,'equip',{id:'trail_blade'});step(s,.3);assert.equal(e.hp,87);});
test('incoming arrow grants timed enemy awareness at current world time',()=>{const s=hostile();s.state.adventure.elapsed=500;const e=A.runtime(s).enemies[0];cmd(s,'attack',{target:e.id});step(s,.3);assert.ok(e.awareness>502);});
test('line trace chooses first target regardless of requested target order',()=>{const trace=AR.trace({x:0,z:0},{x:0,z:10},[{id:'far',x:0,z:8,hp:1},{id:'near',x:0,z:3,hp:1}],()=>true);assert.deepEqual(trace.hits.map(q=>q.e.id),['near','far']);});
test('wall precedes targets behind it and already-hit ids are ignored',()=>{const trace=AR.trace({x:0,z:0},{x:0,z:10},[{id:'front',x:0,z:2,hp:1},{id:'back',x:0,z:8,hp:1}],(x,z)=>z<5,['front']);assert.ok(trace.wall>.45&&trace.wall<.55);assert.equal(trace.hits.length,0);});
test('swept segments catch a target between endpoints',()=>{const u=AR.segmentCircle({x:0,z:0},{x:0,z:4},{x:0,z:2},.2);assert.ok(u>.44&&u<.46);assert.equal(AR.segmentCircle({x:0,z:0},{x:0,z:4},{x:2,z:2},.2),null);});
test('degenerate and invalid geometry is bounded',()=>{assert.equal(AR.segmentCircle({x:0,z:0},{x:0,z:0},{x:0,z:0},.2),0);assert.equal(AR.segmentCircle({x:0,z:0},{x:0,z:0},{x:1,z:0},.2),null);assert.equal(AR.segmentCircle({x:NaN,z:0},{x:1,z:0},{x:1,z:0},1),null);assert.equal(AR.aimClear(range(),{x:0,z:0},{x:Infinity,z:0}),false);assert.deepEqual(AR.trace({x:0,z:0},{x:Infinity,z:0},[],()=>true),{wall:0,hits:[]});});
test('projectiles cross road water but not real obstacles',()=>{const s=range();s.room='road';assert.equal(R.walkable(-8,0),false);assert.equal(AR.projectileGround(s,-8,0),true);for(const o of R.OBSTACLES)assert.equal(AR.projectileGround(s,o.x,o.z),false);});
test('mine stone and court pillars stop arrows',()=>{const s=hostile();assert.equal(AR.projectileGround(s,4,5),false);const t=range();assert.equal(AR.aimClear(t,{x:3,z:3},{x:3,z:-3}),false);});
test('piercing light can hit at most two bodies and each at most once',()=>{const s=hostile(),r=A.runtime(s);r.enemies=[1,2,3].map(i=>({id:'test-'+i,x:0,z:7-i,hp:200,maxHP:200,mode:'recover',timer:100,kind:'skitter',damage:0}));cmd(s,'pulse',{target:'test-1'});step(s,.4);assert.deepEqual(r.enemies.map(e=>e.hp),[179,179,200]);assert.equal(r.arrows.length,0);});
test('ordinary arrow only hits first intervening target',()=>{const s=hostile(),r=A.runtime(s);r.enemies=[1,2].map(i=>({id:'test-'+i,x:0,z:7-i,hp:200,maxHP:200,mode:'recover',timer:100,kind:'skitter',damage:0}));cmd(s,'attack',{target:'test-2'});step(s,.4);assert.deepEqual(r.enemies.map(e=>e.hp),[187,200]);});
test('leaving and dying discard transient arrows',()=>{for(const mode of['leave','death']){const s=hostile();cmd(s,'attack',{target:'briar-1'});if(mode==='leave'){s.room=null;A.syncScene(s);}else{s.state.adventure.hp=0;step(s,.1);}assert.equal(AR.runtime(s).arrows.length,0);}});
test('no arrow follows an enemy forever',()=>{const s=hostile(),e=A.runtime(s).enemies[0];cmd(s,'attack',{target:e.id});e.x=2;step(s,2);assert.equal(AR.runtime(s).arrows.length,0);});
test('a fired arrow reaching zero HP creates one ordinary cache and XP result',()=>{const s=hostile(),e=A.runtime(s).enemies[0];e.hp=5;cmd(s,'attack',{target:e.id});step(s,.3);assert.deepEqual(s.state.adventure.defeated,['briar-1']);assert.deepEqual(s.state.adventure.drops,['briar-1']);assert.equal(s.state.adventure.xp,20);});
test('target motion is reproducible and only the sun moves',()=>{const [a,b,c]=AR.RANGE.targets;assert.equal(AR.targetPose(a,2).x,a.x);assert.equal(AR.targetPose(b,2).x,b.x);assert.notEqual(AR.targetPose(c,2).x,c.x);assert.deepEqual(AR.targetPose(c,2),AR.targetPose(c,2));});
test('round requires range and bow and cannot restart a running clock',()=>{reject(equipped(),'range-start');const s=range();cmd(s,'equip',{id:'trail_blade'});reject(s,'range-start');cmd(s,'equip',{id:'trail_bow'});assert.ok(cmd(s,'range-start').ok);reject(s,'range-start');});
test('practice arrows hit real targets without XP harm defeat or loot',()=>{const s=range(),v=s.state.adventure,r=AR.runtime(s);cmd(s,'range-start');cmd(s,'attack',{target:'range-mid'});step(s,.5);assert.equal(r.range.hits['range-mid'],1);assert.equal(v.xp,0);assert.equal(v.hp,100);assert.equal(r.enemies[1].hp,100);assert.equal(v.defeated.length,0);assert.equal(v.drops.length,0);});
test('untimed target hits cannot mint a practice reward',()=>{const s=range(),v=s.state.adventure;for(const e of AR.runtime(s).enemies){AR.practiceHit(s,e);AR.practiceHit(s,e);}assert.equal(v.arsenal.rangeMedal,false);assert.equal(v.coins,100);});
test('known-answer six hits award one medal five coins one amber',()=>{const s=range();win(s);const v=s.state.adventure;assert.equal(v.arsenal.rangeMedal,true);assert.equal(v.arsenal.bestTime,10);assert.equal(v.coins,105);assert.equal(v.arsenal.gems.amber,1);assert.equal(AR.runtime(s).range.active,false);});
test('repeated completed rounds improve best but never pay again',()=>{const s=range();win(s);win(s);assert.equal(s.state.adventure.coins,105);assert.equal(s.state.adventure.arsenal.gems.amber,1);assert.equal(s.state.adventure.arsenal.bestTime,10);});
test('longer round preserves faster recorded time',()=>{const s=range();win(s);cmd(s,'range-start');s.state.adventure.elapsed+=20;for(const e of AR.runtime(s).enemies){AR.practiceHit(s,e);AR.practiceHit(s,e);}assert.equal(s.state.adventure.arsenal.bestTime,10);});
test('partial hits and timeout have no reward; new round starts empty',()=>{const s=range(),r=AR.runtime(s);cmd(s,'range-start');AR.practiceHit(s,r.enemies[0]);step(s,30.1);assert.equal(r.range.active,false);assert.equal(s.state.adventure.arsenal.rangeMedal,false);cmd(s,'range-start');assert.deepEqual(r.range.hits,{});});
test('pause freezes timer projectile and moving target',()=>{const s=range();cmd(s,'range-start');cmd(s,'attack',{target:'range-mid'});const old=snapshot(s),r=JSON.stringify(AR.runtime(s));s.paused=true;step(s,40);assert.equal(snapshot(s),old);assert.equal(JSON.stringify(AR.runtime(s)),r);reject(s,'range-start');});
test('daylight adjustment does not advance practice clock',()=>{const s=range();cmd(s,'range-start');const t=s.state.adventure.elapsed;s.setTime(23);assert.equal(s.state.adventure.elapsed,t);assert.equal(AR.runtime(s).range.active,true);});
test('round stop preserves prior medal and clears arrows',()=>{const s=range();win(s);cmd(s,'range-start');cmd(s,'attack',{target:'range-mid'});cmd(s,'range-stop');assert.equal(s.state.adventure.arsenal.rangeMedal,true);assert.equal(AR.runtime(s).arrows.length,0);assert.equal(AR.runtime(s).range.active,false);reject(s,'range-stop');});
test('reward overflow does not mark medal or partly pay',()=>{for(const field of['coin','gem']){const s=range(),v=s.state.adventure;if(field==='coin')v.coins=9999;else v.arsenal.gems.amber=9999;const coins=v.coins,gems=v.arsenal.gems.amber;win(s);assert.equal(v.arsenal.rangeMedal,false);assert.equal(v.arsenal.bestTime,null);assert.equal(v.coins,coins);assert.equal(v.arsenal.gems.amber,gems);}});
test('saved medal sockets and health validate in a cold restart',()=>{const s=equipped();s.state.adventure.arsenal.gems.moonstone=1;cmd(s,'socket',{weapon:'trail_bow',gem:'moonstone'});cmd(s,'range-enter');win(s);const old=s.snapshot(),cold=new C.Simulation(old);assert.deepEqual(cold.snapshot(),old);assert.equal(A.stats(cold.state.adventure).maxHP,118);});
test('equipped amber modifies actual fox damage, unequipped amber does not',()=>{for(const active of[true,false]){const s=hostile(),v=s.state.adventure,r=A.runtime(s),e=r.enemies[0];v.companion.bonded=true;v.arsenal.sockets[active?'trail_bow':'trail_blade']='amber';r.companion={room:'mine',x:0,z:4.9,yaw:0,path:[],nextPath:100,nextHit:0,status:'Beside you'};e.awareness=100;step(s,.05);assert.equal(e.hp,100-(6+(active?3:0)));}});
