/* Known-answer rule fixtures deliberately control positions/enemy state.
 * See beacon_journey.cjs for the separate no-grant/no-teleport acceptance run. */
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const C=require('../src/core.js'),A=require('../src/adventure.js'),B=require('../src/beacon.js'),T=require('../src/combat.js'),AR=require('../src/arsenal.js');
const raw=()=>JSON.parse(fs.readFileSync(require.resolve('../examples/CHAPTER_II_COMPLETE_EARNED.json')));
let seq=0;const cmd=(s,t,p={})=>s.adventureCommand('beacon-test-'+(++seq),t,p),step=(s,t)=>{for(let i=0;i<Math.ceil(t/.05);i++)s.tick(.05);};
const snap=s=>JSON.stringify(s.snapshot());
function reject(s,t,p={}){const old=snap(s);assert.equal(cmd(s,t,p).ok,false,t);assert.equal(snap(s),old,t+' unchanged');}
function atBeacon(){const s=new C.Simulation(raw());s.state.player={x:44,z:6,yaw:0};assert.ok(cmd(s,'road-enter').ok);s.state.player={x:0,z:-24,yaw:0};A.runtime(s).companion={...A.runtime(s).companion,room:'road',x:0,z:-24};return s;}
function ready(){const s=atBeacon();assert.ok(cmd(s,'beacon-answer').ok);step(s,18);assert.equal(B.runtime(s).phase,'ready');return s;}
function assault(){const s=ready();assert.ok(cmd(s,'beacon-defend').ok);return s;}
function victory(){const s=assault();for(let k=0;k<3;k++){for(const e of A.runtime(s).enemies.filter(e=>e.eventEnemy)){e.hidden=false;A.damageEnemy(s,e,10000);}step(s,k===2?.1:7.2);}assert.equal(B.runtime(s).phase,'won');return s;}
function hitFixture(){const s=atBeacon();s.state.adventure.companion.mode='stay';A.runtime(s).enemies=[{id:'test-foe',kind:'invader',eventEnemy:true,name:'Test foe',x:0,z:-22,hp:1000,maxHP:1000,damage:0,mode:'recover',timer:100,path:[],home:{x:0,z:-22}}];return s;}

test('Realm08 world migrates to current schema without changing supported content',()=>{const v=raw();v.version=7;v.adventure.version=3;v.adventure.arsenal=AR.fresh();const text=JSON.stringify(v),n=C.validate(v);assert.equal(n.version,C.VERSION);assert.equal(n.adventure.version,A.VERSION);assert.deepEqual(n.adventure.beacon,B.fresh());for(const k of['score','retreat','sandbox','visitor','notes','flowers'])assert.deepEqual(n[k],v[k]);assert.equal(JSON.stringify(v),text);});
test('fresh beacon contains no earned alignment or free story completion',()=>assert.deepEqual(C.fresh().adventure.beacon,B.fresh()));
for(const [name,mut]of Object.entries({version:b=>b.version=9,missingSoul:b=>b.soul=null,badStatus:b=>b.status='evil',badCounts:b=>b.failures=1,unknownRoute:b=>b.route='__proto__',unearnedCompletion:b=>b.complete=true,rewardEarly:b=>b.reward=true,graceEarly:b=>b.soul.grace=true,negativeRadiance:b=>b.soul.radiance=-1,corruptionNoHistory:b=>b.soul.corruption=1,falsePower:b=>b.soul.equipped='cinder',fakeScar:b=>b.soul.scars=['automatic-evil'],duplicatedScars:b=>b.soul.scars=['cinder-invoked','cinder-invoked'],unearnedRelic:b=>b.relic='accepted',nonintegerAttempts:b=>b.attempts=1.4}))test('beacon import rejects '+name,()=>{const v=C.fresh();mut(v.adventure.beacon);assert.throws(()=>C.validate(v));});
test('beacon opening requires story and physical scene',()=>{const s=new C.Simulation(raw());reject(s,'beacon-answer');s.state.player={x:0,z:-24,yaw:0};reject(s,'beacon-answer');const t=atBeacon();t.state.adventure.road.reported=false;t.state.adventure.road.beaconLit=false;reject(t,'beacon-answer');});
test('answer at beacon settles an unreported chapter II exactly once',()=>{const s=atBeacon(),a=s.state.adventure;a.road.reported=false;a.owned=a.owned.filter(x=>x!=='wayfarer_band');a.equipment.charm=null;a.hp=Math.min(a.hp,A.stats(a).maxHP);const xp=a.xp;assert.ok(cmd(s,'beacon-answer').ok);assert.ok(a.road.reported);assert.equal(a.xp,xp+20);assert.equal(a.owned.filter(x=>x==='wayfarer_band').length,1);reject(s,'beacon-answer');});
test('arrival has three actual valid paths and does not start combat automatically',()=>{const s=atBeacon();cmd(s,'beacon-answer');const r=B.runtime(s);assert.equal(r.actors.length,3);assert.ok(r.actors.every(x=>x.path.length>0));step(s,3);assert.equal(r.phase,'arrival');assert.ok(r.actors.some(x=>x.path.length));step(s,15);assert.equal(r.phase,'ready');assert.ok(r.actors.every(x=>Math.hypot(x.x-x.goal.x,x.z-x.goal.z)<.1));assert.equal(s.state.adventure.beacon.attempts,0);});
test('cannot accept Grace or start battle during the descent',()=>{const s=atBeacon();cmd(s,'beacon-answer');reject(s,'beacon-grace');reject(s,'beacon-defend');});
test('Grace is optional and a deliberate single claim',()=>{const s=ready();assert.equal(s.state.adventure.beacon.soul.radiance,0);assert.ok(cmd(s,'beacon-grace').ok);assert.equal(s.state.adventure.beacon.soul.radiance,1);reject(s,'beacon-grace');assert.ok(cmd(s,'soul-equip',{power:null}).ok);assert.equal(s.state.adventure.beacon.soul.equipped,null);});
test('first defense can start without accepting a Grace',()=>{const s=assault();assert.equal(s.state.adventure.beacon.soul.grace,false);assert.equal(B.runtime(s).wave,1);assert.equal(A.runtime(s).enemies.filter(x=>x.eventEnemy).length,2);});
test('new events never insert their IDs into ordinary defeat or cache persistence',()=>{const s=assault(),a=s.state.adventure,xp=a.xp,d=[...a.defeated],drop=[...a.drops];for(const e of A.runtime(s).enemies)if(e.eventEnemy)A.damageEnemy(s,e,1000);assert.equal(a.xp,xp);assert.deepEqual(a.defeated,d);assert.deepEqual(a.drops,drop);assert.doesNotThrow(()=>s.snapshot());});
test('complete waves opens exactly one reward, replaying request cannot double pay',()=>{const s=victory(),a=s.state.adventure,coins=a.coins,gem=a.arsenal.gems.moonstone;assert.ok(cmd(s,'beacon-reward').ok);assert.equal(a.coins,coins+15);assert.equal(a.arsenal.gems.moonstone,gem+1);reject(s,'beacon-reward');});
test('full pouch refuses defense reward atomically',()=>{for(const k of['coins','gems']){const s=victory();if(k==='coins')s.state.adventure.coins=9999;else s.state.adventure.arsenal.gems.moonstone=9999;reject(s,'beacon-reward');assert.equal(s.state.adventure.beacon.reward,false);}});
test('ordinary failure is recoverable and protects completed content',()=>{const s=assault(),a=s.state.adventure,old=s.snapshot();B.runtime(s).ward=0;step(s,.1);assert.equal(a.beacon.status,'corrupted');assert.equal(a.beacon.failures,1);for(const k of['score','retreat','notes'])assert.deepEqual(s.snapshot()[k],old[k]);for(const k of['inventory','placed','bridge'])assert.deepEqual(s.snapshot().sandbox[k],old.sandbox[k]);assert.ok(cmd(s,'beacon-defend').ok);assert.equal(B.runtime(s).ward,100);assert.equal(a.beacon.attempts,2);});
test('withdrawal loses the encounter but a reload does not invent a win',()=>{const s=assault();step(s,1);const cold=new C.Simulation(s.snapshot());assert.equal(cold.room,null);assert.equal(cold.state.adventure.beacon.complete,false);assert.equal(B.runtime(cold).phase,'idle');s.leave();step(s,.1);assert.equal(s.state.adventure.beacon.status,'corrupted');});
test('pause stops arrival movement, enemy windups, ward and timers',()=>{const s=assault();s.paused=true;const before=JSON.stringify(B.runtime(s)),old=snap(s);step(s,20);assert.equal(JSON.stringify(B.runtime(s)),before);assert.equal(snap(s),old);reject(s,'beacon-repair');});
test('repair spends actual stamina, obeys position cooldown and maximum',()=>{const s=assault(),r=B.runtime(s);reject(s,'beacon-repair');r.ward=50;assert.ok(cmd(s,'beacon-repair').ok);assert.equal(r.ward,65);assert.equal(s.state.adventure.stamina,80);reject(s,'beacon-repair');step(s,8.1);s.state.player={x:0,z:-15,yaw:0};reject(s,'beacon-repair');});
test('Oren repairs, Mara reveals and Ilan replenishes stamina on active schedules',()=>{const s=assault(),r=B.runtime(s),a=s.state.adventure;r.ward=70;r.repairAt=0;r.maraAt=0;r.ilanAt=0;a.stamina=10;A.runtime(s).enemies[0].hidden=true;step(s,.05);assert.equal(r.ward,73);assert.equal(A.runtime(s).enemies[0].hidden,false);assert.ok(a.stamina>=22);assert.ok(A.runtime(s).enemies[0].exposedUntil>a.elapsed);});
test('passive presence is not a guaranteed defense win',()=>{const s=assault();s.state.player={x:0,z:17,yaw:0};cmd(s,'companion-mode',{mode:'stay'});step(s,120);assert.equal(B.runtime(s).phase,'failed');assert.equal(s.state.adventure.beacon.complete,false);});
test('attempt cap refuses before healing or spending resources',()=>{const s=ready();s.state.adventure.beacon.attempts=9999;s.state.adventure.hp=50;s.state.adventure.tonics=0;reject(s,'beacon-defend');});
test('cinder is an explicit exclusive choice and acceptance does not corrupt',()=>{const s=victory();cmd(s,'beacon-relic',{choice:'accept'});assert.equal(s.state.adventure.beacon.soul.corruption,0);assert.equal(s.state.adventure.beacon.soul.equipped,'cinder');reject(s,'beacon-relic',{choice:'seal'});});
test('sealing a cinder imposes neither power nor corruption',()=>{const s=victory();cmd(s,'beacon-relic',{choice:'seal'});assert.deepEqual(s.state.adventure.beacon.soul,{grace:false,equipped:null,radiance:0,corruption:0,scars:[]});reject(s,'soul-equip',{power:'cinder'});});
test('replay rewards and failures cannot damage a completed chapter',()=>{const s=victory(),a=s.state.adventure;cmd(s,'beacon-reward');const coins=a.coins;cmd(s,'beacon-replay');B.runtime(s).ward=0;step(s,.1);assert.equal(a.beacon.status,'stable');assert.equal(a.beacon.complete,true);assert.equal(a.beacon.failures,0);assert.equal(a.coins,coins);reject(s,'beacon-reward');assert.doesNotThrow(()=>s.snapshot());});
test('future route records do not teleport or unlock nonexistent geography',()=>{const s=victory(),p={...s.state.player};cmd(s,'beacon-route',{route:'forest'});assert.equal(s.state.adventure.beacon.route,'forest');assert.deepEqual(s.state.player,p);reject(s,'beacon-route',{route:'heaven-now'});});
test('target cycling is nearest-first, reversible and never starts attacking',()=>{const s=hitFixture(),r=A.runtime(s);r.enemies.push({...r.enemies[0],id:'second',x:1,z:-20});cmd(s,'target-cycle');assert.equal(T.runtime(s).target,'test-foe');assert.equal(T.runtime(s).auto,false);cmd(s,'target-cycle');assert.equal(T.runtime(s).target,'second');cmd(s,'target-cycle',{reverse:true});assert.equal(T.runtime(s).target,'test-foe');step(s,1);assert.equal(r.enemies[0].hp,1000);});
test('hidden dead and very distant targets are not selectable',()=>{const s=hitFixture(),e=A.runtime(s).enemies[0];e.hidden=true;reject(s,'target-select',{id:e.id});assert.equal(T.candidates(s).length,0);e.hidden=false;e.hp=0;reject(s,'target-select',{id:e.id});e.hp=10;e.z=15;reject(s,'target-select',{id:e.id});});
test('autoattack repeatedly uses real cooldowns without moving the player',()=>{const s=hitFixture(),e=A.runtime(s).enemies[0],p={...s.state.player};cmd(s,'target-select',{id:e.id});cmd(s,'auto-toggle');step(s,1.1);assert.ok(e.hp<1000-A.stats(s.state.adventure).attack);assert.equal(s.state.player.x,p.x);assert.equal(s.state.player.z,p.z);assert.equal(s.playerPath.length,0);});
test('out of range autoattack waits rather than walking or spending stamina',()=>{const s=hitFixture(),e=A.runtime(s).enemies[0];e.z=-15;cmd(s,'target-select',{id:e.id});cmd(s,'auto-toggle');const hp=e.hp;step(s,1);assert.equal(e.hp,hp);assert.equal(s.state.player.z,-24);assert.equal(s.playerPath.length,0);assert.match(T.readiness(s),/Out of range/);});
test('selected target death stops autoattack instead of pulling a new foe',()=>{const s=hitFixture(),e=A.runtime(s).enemies[0];e.hp=1;A.runtime(s).enemies.push({...e,id:'second',hp:100});cmd(s,'target-select',{id:e.id});cmd(s,'auto-toggle');step(s,1);assert.equal(T.runtime(s).auto,false);assert.equal(A.runtime(s).enemies[1].hp,100);});
test('clear target, scene changes and restart never retain autoattack',()=>{const s=hitFixture();cmd(s,'target-cycle');cmd(s,'auto-toggle');cmd(s,'target-clear');assert.equal(T.runtime(s).auto,false);assert.equal(T.runtime(s).target,null);cmd(s,'auto-toggle');const cold=new C.Simulation(s.snapshot());assert.equal(T.runtime(cold).auto,false);s.leave();step(s,.1);assert.equal(T.runtime(s).auto,false);});
test('Brace halves guarded damage for its actual timed window',()=>{const s=hitFixture();cmd(s,'guard');assert.equal(T.mitigate(s,20),10);step(s,3.1);assert.equal(T.mitigate(s,20),20);reject(s,'guard');step(s,5);assert.ok(cmd(s,'guard').ok);});
test('Brace refuses insufficient stamina without charging a cooldown',()=>{const s=hitFixture();s.state.adventure.stamina=19;const r=T.runtime(s);reject(s,'guard');assert.equal(r.cooldowns.guard,0);});
test('Briar reveals a cloaked foe, exposes and interrupts a locked windup',()=>{const s=hitFixture(),e=A.runtime(s).enemies[0];e.hidden=true;e.mode='windup';e.timer=1;cmd(s,'companion-mode',{mode:'follow'});cmd(s,'insight');assert.equal(e.hidden,false);assert.equal(e.mode,'recover');assert.ok(e.exposedUntil>s.state.adventure.elapsed);const before=e.hp;cmd(s,'attack',{target:e.id});assert.equal(e.hp,before-Math.round(A.stats(s.state.adventure).attack*1.2));reject(s,'insight');});
test('Briar Stay prevents the companion skill',()=>{const s=hitFixture();cmd(s,'companion-mode',{mode:'stay'});reject(s,'insight');});
test('Aegis is a finite barrier, not immortality, and needs accepted Grace',()=>{const s=ready();reject(s,'spirit');cmd(s,'beacon-grace');cmd(s,'spirit');assert.equal(T.mitigate(s,20),0);assert.equal(T.runtime(s).shield,15);assert.equal(T.mitigate(s,20),5);assert.equal(T.runtime(s).shield,0);reject(s,'spirit');});
test('Cinder health cost is nonlethal and its scar is persistent but not repeated',()=>{const s=victory(),a=s.state.adventure;cmd(s,'beacon-relic',{choice:'accept'});cmd(s,'beacon-replay');cmd(s,'target-cycle');a.hp=12;reject(s,'spirit');a.hp=100;const hp=a.hp;assert.ok(cmd(s,'spirit').ok);assert.equal(a.hp,hp-12);assert.equal(a.beacon.soul.corruption,1);assert.deepEqual(a.beacon.soul.scars,['cinder-invoked']);const cold=new C.Simulation(s.snapshot());assert.equal(cold.state.adventure.beacon.soul.corruption,1);});
test('renouncing the cinder removes power and present corruption, not its history',()=>{const s=victory(),a=s.state.adventure;cmd(s,'beacon-relic',{choice:'accept'});a.beacon.soul.scars=['cinder-invoked'];a.beacon.soul.corruption=1;cmd(s,'soul-purify');assert.equal(a.beacon.relic,'renounced');assert.equal(a.beacon.soul.equipped,null);assert.equal(a.beacon.soul.corruption,0);assert.deepEqual(a.beacon.soul.scars,['cinder-invoked','cinder-renounced']);assert.equal(a.beacon.soul.radiance,1);reject(s,'soul-equip',{power:'cinder'});assert.deepEqual(new C.Simulation(s.snapshot()).snapshot(),s.snapshot());});
test('choice switching never grants damage by itself or silently starts PvP',()=>{const s=ready(),old=s.state.adventure.hp;cmd(s,'beacon-grace');cmd(s,'soul-equip',{power:null});assert.equal(s.state.adventure.hp,old);assert.equal(T.runtime(s).auto,false);assert.equal(s.state.adventure.beacon.soul.corruption,0);});
test('mutation receipts protect identical retries and reject changed choices',()=>{const s=ready();const r=s.adventureCommand('choice-once','beacon-grace',{});assert.ok(r.ok);const old=snap(s);assert.ok(s.adventureCommand('choice-once','beacon-grace',{}).duplicate);assert.equal(snap(s),old);assert.equal(s.adventureCommand('choice-once','soul-equip',{power:null}).ok,false);assert.equal(snap(s),old);});

test('first target selected after a scene change survives the next tick',()=>{const s=new C.Simulation(raw());T.runtime(s);s.state.player={x:44,z:6,yaw:0};cmd(s,'road-enter');const e={id:'scene-foe',kind:'practice',name:'Scene foe',x:0,z:15,hp:100,maxHP:100,path:[],mode:'idle',timer:0};A.runtime(s).enemies.push(e);cmd(s,'target-cycle');cmd(s,'auto-toggle');step(s,.1);assert.equal(T.runtime(s).target,'scene-foe');assert.equal(T.runtime(s).auto,true);});
