"""Offline browser acceptance. Owned HTML is injected unchanged into about:blank.
No navigation policy is altered. This does not test file:// localStorage behavior.
"""
from pathlib import Path
import json, hashlib, traceback
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'evidence07'/'regression'; OUT.mkdir(parents=True,exist_ok=True)
HTML=(ROOT/'FIRSTLIGHT_VALLEY.html').read_text()
REPORT={'build_sha256':hashlib.sha256(HTML.encode()).hexdigest(),'navigation':'owned HTML via set_content in about:blank; offline context','checks':[],'errors':[]}
def check(label,value):
    REPORT['checks'].append({'check':label,'passed':bool(value)})
    if not value: raise AssertionError(label)
ARGS=['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=gl-egl','--enable-webgl','--ignore-gpu-blocklist','--disable-gpu-sandbox']
try:
 with sync_playwright() as p:
  b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=ARGS)
  ctx=b.new_context(viewport={'width':1440,'height':900},offline=True,accept_downloads=True)
  page=ctx.new_page(); reqs=[]; errs=[]
  page.on('request',lambda r:reqs.append(r.url)); page.on('pageerror',lambda e:errs.append(str(e)))
  page.evaluate('window.__ETERNITIES_TEST_MODE=true')
  page.set_content(HTML,wait_until='load',timeout=30000)
  page.wait_for_function('window.Realm && window.Realm.diagnostics.mode === "webgl2"',timeout=20000)
  page.wait_for_timeout(1800)
  check('Real WebGL2 scene initialized offline',page.evaluate('Realm.diagnostics.mode')=='webgl2')
  check('No external asset requests',len(reqs)==0)
  check('Audio is not created before user gesture',page.evaluate('Realm.diagnostics.audio.state')=='not-created')
  page.evaluate('Realm.test.pause(true); Realm.test.render()')
  page.screenshot(path=str(OUT/'01-valley-evening.png'),timeout=30000)
  REPORT['graphics']=page.evaluate('Realm.diagnostics')
  page.evaluate('Realm.test.quality("low")')
  check('Storage failure is visible', 'MEMORY ONLY' in page.locator('#save-status').inner_text())
  before=page.evaluate('({player:Realm.state.player,yaw:Realm.diagnostics.camera.yaw})')
  page.mouse.move(700,430);page.mouse.down();page.mouse.move(850,450,steps=5);page.mouse.up();page.wait_for_timeout(150)
  after=page.evaluate('({player:Realm.state.player,yaw:Realm.diagnostics.camera.yaw,path:Realm.test.path.length})')
  check('Drag rotates without issuing a walk',before['player']==after['player'] and before['yaw']!=after['yaw'] and after['path']==0)
  half=page.evaluate('Realm.diagnostics.camera.half');page.mouse.wheel(0,180);page.wait_for_timeout(200)
  check('Wheel changes orthographic zoom',page.evaluate('Realm.diagnostics.camera.half')!=half)
  page.keyboard.press('r');page.evaluate('Realm.test.render()')
  pt=page.evaluate('Realm.project(-5,1.3,8)');page.mouse.click(pt['x'],pt['y']);page.evaluate('Realm.test.step(35)')
  check('Click follows a valid world-space path',page.evaluate('Math.hypot(Realm.state.player.x+5,Realm.state.player.z-8)<.3'))
  page.click('#inhabitants');check('All three authored people are available',page.locator('[data-action="select-resident"]').count()==3)
  page.click('[data-action="select-resident"][data-id="ilan"]');page.click('[data-action="talk"]')
  check('Authored dialogue is displayed and counted',page.locator('.quote').count()==1 and page.evaluate('Realm.state.residents[0].conversations')==1)
  page.click('#close-panel');page.click('#chronicle');page.fill('#note-text','<img src=x onerror="window.BAD=true"> My first evening.');page.click('[data-action="note"]')
  check('Notebook escapes user markup',page.locator('.note img').count()==0 and page.evaluate('window.BAD===undefined'))
  check('Notebook keeps exact user text', '<img src=x' in page.locator('.note').inner_text())
  page.click('#close-panel');page.evaluate('Realm.navigate("garden"); Realm.test.step(60)');page.click('#interact')
  check('Garden action plants and retains a flower',len(page.evaluate('Realm.state.flowers'))==1)
  page.click('#settings');page.click('[data-action="time"][data-hour="21.5"]');page.click('[data-action="weather"][data-weather="rain"]')
  check('Clock and weather controls change actual state',page.evaluate('Realm.state.hour')==21.5 and page.evaluate('Realm.state.weather')=='rain')
  page.click('#close-panel');page.evaluate('Realm.test.quality("balanced"); Realm.test.render()');page.screenshot(path=str(OUT/'02-valley-night.png'),timeout=30000)
  page.evaluate('Realm.test.quality("low"); Realm.test.setTime(19); Realm.test.step(150); Realm.navigate("home"); Realm.test.step(60)')
  page.click('#explore');page.click('[data-action="place-action"][data-id="home"]')
  check('A doorway opens a rendered interior',page.evaluate('Realm.diagnostics.scene')=='home')
  page.evaluate('Realm.test.quality("balanced"); Realm.test.render()');page.screenshot(path=str(OUT/'03-shared-house.png'),timeout=30000)
  check('Interior has actual separate geometry',page.evaluate('Realm.diagnostics.metrics.instances')>100)
  page.keyboard.press('Escape');check('Leaving returns to the outside world',page.evaluate('Realm.diagnostics.scene')=='valley')
  page.evaluate('Realm.test.quality("low")');page.click('#chronicle')
  with page.expect_download(timeout=15000) as di:page.click('[data-action="export"]')
  data=Path(di.value.path()).read_text();export=json.loads(data)
  check('Export produces portable real JSON',export['version']==page.evaluate('RealmCore.VERSION') and len(export['flowers'])==1 and len(export['notes'])==1)
  page.on('dialog',lambda d:d.accept());page.set_input_files('#import-file',{'name':'world.json','mimeType':'application/json','buffer':data.encode()});page.wait_for_timeout(300)
  check('Import restores current source state',page.evaluate('Realm.state.flowers.length')==1 and page.evaluate('Realm.state.notes.length')==1)
  # Import already closes the panel. Do not click an invisible close button.
  page.click('#sound');page.wait_for_timeout(350)
  check('Sound is enabled only by a gesture',page.evaluate('Realm.diagnostics.audio.enabled') and page.evaluate('Realm.diagnostics.audio.state')=='running')
  page.click('#sound');check('Sound can be disabled',not page.evaluate('Realm.diagnostics.audio.enabled'))
  page.click('#settings')
  with page.expect_download(timeout=15000) as pi:page.click('[data-action="capture"]')
  photo=Path(pi.value.path()).read_bytes();check('Photo action emits a real PNG',photo[:8]==b'\x89PNG\r\n\x1a\n')
  check('No unhandled JavaScript errors',not errs)
  check('No network calls during interactions',not reqs)
  REPORT['browser_errors']=errs;ctx.close()
  # Mobile is a separate offline Chromium context, not proof of iOS Safari support.
  mob=b.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True,offline=True)
  pg=mob.new_page();pg.evaluate('window.__ETERNITIES_TEST_MODE=true');pg.set_content(HTML,wait_until='load',timeout=30000);pg.wait_for_function('window.Realm',timeout=20000);pg.wait_for_timeout(800)
  check('Mobile WebGL2 renders',pg.evaluate('Realm.diagnostics.mode')=='webgl2')
  check('Mobile has no horizontal page overflow',pg.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  for sel in ['#explore','#pack-open','#craft-open','#build-open','#interact']:
   box=pg.locator(sel).bounding_box();check('Mobile control fits '+sel,box and box['x']>=0 and box['x']+box['width']<=390 and box['y']+box['height']<=844)
  pg.evaluate('Realm.test.pause(true); Realm.test.render()');pg.screenshot(path=str(OUT/'04-mobile-valley.png'),timeout=30000)
  pg.click('#explore');pg.click('[data-action="sb-open"][data-id="inhabitants"]');pg.screenshot(path=str(OUT/'05-mobile-inhabitants.png'),timeout=30000)
  box=pg.locator('#drawer').bounding_box();check('Mobile drawer stays within viewport',box and box['x']>=0 and box['y']>=0 and box['x']+box['width']<=390 and box['y']+box['height']<=844)
  pg.click('#close-panel');check('Closed mobile panel is inert',pg.locator('#drawer').evaluate('(x)=>x.inert'))
  pg.evaluate('Realm.test.quality("low"); Realm.test.render()');half=pg.evaluate('Realm.diagnostics.camera.half')
  cd=mob.new_cdp_session(pg)
  cd.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':145,'y':400,'id':1},{'x':245,'y':400,'id':2}]})
  cd.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':115,'y':400,'id':1},{'x':275,'y':400,'id':2}]})
  cd.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});pg.wait_for_timeout(200)
  check('Native two-finger gesture changes zoom',pg.evaluate('Realm.diagnostics.camera.half')!=half)
  mob.close()
  fb=b.new_context(viewport={'width':1000,'height':700},offline=True)
  q=fb.new_page();q.evaluate('window.__ETERNITIES_TEST_MODE=true; window._oldGetContext=HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext=function(type,...args){return type==="webgl2"?null:window._oldGetContext.call(this,type,...args)}; true')
  q.set_content(HTML,wait_until='load',timeout=20000);q.wait_for_function('window.Realm',timeout=10000);q.wait_for_timeout(600)
  check('Unavailable WebGL selects usable map mode',q.evaluate('Realm.diagnostics.mode')=='map')
  check('Fallback map is visible',q.locator('#map-fallback').is_visible())
  q.evaluate('Realm.navigate("garden"); Realm.test.step(60)');q.click('#interact')
  check('Fallback supports persistent local actions',q.evaluate('Realm.state.flowers.length')==1)
  q.evaluate('Realm.navigate("home"); Realm.test.step(60)');q.click('#interact')
  check('Fallback can enter the same interior',q.evaluate('Realm.diagnostics.scene')=='home')
  q.keyboard.press('Escape');check('Fallback can leave an interior',q.evaluate('Realm.diagnostics.scene')=='valley')
  q.screenshot(path=str(OUT/'06-map-fallback.png'),timeout=20000);fb.close();b.close()
except Exception as e:
 REPORT['errors'].append(str(e));REPORT['traceback']=traceback.format_exc()
finally:
 REPORT['passed']=not REPORT['errors'] and all(c['passed'] for c in REPORT['checks'])
 REPORT['checks_passed']=sum(c['passed'] for c in REPORT['checks'])
 (OUT/'BASELINE_BROWSER_TEST_REPORT.json').write_text(json.dumps(REPORT,indent=2))
 print(json.dumps(REPORT,indent=2))
