/* Fresh-world acceptance: no inventory grants, position edits or quest/kill injections.
 * Time advances in 50ms steps, using automated survival decisions; not a human playtest. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),C=require('../src/core.js'),S=require('../src/sandbox.js'),A=require('../src/adventure.js');
function journey(){let sim=new C.Simulation(),events=[],out=path.join(__dirname,'../evidence07/chapter1');fs.mkdirSync(out,{recursive:true});let seq=0,actions=0;
 const result=(r,w)=>{assert.ok(r.ok,w+': '+r.error);actions++;return r;},adv=(t,p={})=>result(sim.adventureCommand('journey-'+(++seq),t,p),t),sb=(t,p={})=>result(sim.sandboxCommand('journey-'+(++seq),t,p),t);
 const survival=()=>{if(sim.room!=='mine'||!sim.state.adventure.started)return;assert.ok(sim.state.adventure.hp>0,'Player survives without grants');let s=sim.state.adventure,r=A.runtime(sim),e=r.enemies.find(e=>e.hp>0&&Math.hypot(e.x-sim.state.player.x,e.z-sim.state.player.z)<2.6&&A.line(s,sim.state.player,e));if(s.hp<70&&s.tonics&&s.elapsed>=r.cooldowns.heal)adv('heal');if(e&&s.elapsed>=r.cooldowns.attack)adv('attack',{target:e.id});if(e&&s.stamina>=30&&s.elapsed>=r.cooldowns.pulse)adv('pulse');};
 const step=t=>{for(let i=0;i<t*20;i++){survival();sim.tick(.05);}},walk=(x,z)=>{result(sim.moveTo(x,z),'walk '+x+','+z);for(let i=0;sim.playerPath.length&&i<6000;i++)step(.05);assert.ok(Math.hypot(sim.state.player.x-x,sim.state.player.z-z)<.1,'destination reached');};
 const harvest=id=>{let n=S.NODES.find(n=>n.id===id),p=sim.state.player,q;for(let i=0;i<16;i++){let c={x:n.x+Math.sin(i*Math.PI/8)*1.55,z:n.z+Math.cos(i*Math.PI/8)*1.55};if(C.pathfind(p,c,sim.navRoom)){q=c;break;}}assert.ok(q);walk(q.x,q.z);while(sim.state.sandbox.nodes.find(m=>m.id===id).hp){sb('gather',{node:id});step(.55);}};
 walk(11,9);adv('start');events.push('Collected workshop supplies');harvest('timber-1');harvest('timber-2');harvest('stone-1');harvest('stone-2');walk(11,9);sb('craft',{recipe:'pick'});sb('craft',{recipe:'plank'});sb('craft',{recipe:'plank'});walk(0,-21.3);sb('bridge');events.push('Earned pickaxe and repaired crossing');
 walk(0,-48);fs.writeFileSync(path.join(out,'OPTIONAL_CHAPTER_START.json'),JSON.stringify(sim.snapshot(),null,2));adv('enter');walk(0,4);adv('dig',{gx:0,gz:1});step(.5);adv('dig',{gx:0,gz:1});events.push('Excavated central wall');
 walk(-4,2);step(3);assert.ok(sim.state.adventure.defeated.includes('briar-1'));adv('loot',{id:'briar-1'});walk(-8,2);adv('rescue');events.push('Rescued Briar');walk(0,-3);step(3);adv('loot',{id:'briar-2'});walk(2,-4);adv('dig',{gx:2,gz:-2});step(.5);adv('dig',{gx:2,gz:-2});walk(8,-3);step(4);assert.ok(sim.state.adventure.defeated.includes('sentinel'));adv('loot',{id:'sentinel'});adv('equip',{id:'guard_vest'});events.push('Recovered and equipped armor');
 walk(8,-8.2);step(14);assert.ok(sim.state.adventure.defeated.includes('hart'));walk(8,-10);adv('loot',{id:'hart'});adv('relic');events.push('Freed guardian; recovered relic and cache');walk(0,11);adv('leave');walk(11,9);adv('forge');adv('equip',{id:'copper_blade'});walk(0,3);adv('rest');adv('reveal');fs.writeFileSync(path.join(out,'ENVOY_BEFORE_CHOICE.json'),JSON.stringify(sim.snapshot(),null,2));adv('reward',{id:'warden_stone'});adv('equip',{id:'warden_stone'});events.push('Returned, forged weapon, heard envoy, chose gift');
 assert.ok(A.objectives(sim.state.adventure).every(q=>q.done));assert.equal(sim.state.adventure.deaths,0);let snapshot=sim.snapshot(),cold=new C.Simulation(snapshot);assert.deepEqual(cold.snapshot(),snapshot);fs.writeFileSync(path.join(out,'CHAPTER_COMPLETED.json'),JSON.stringify(snapshot,null,2));let report={status:'passed',method:'Fresh state; accepted movement and gameplay commands only. 50ms accelerated time. Automated decisions, not human balancing.',directInventoryGrants:0,playerPositionEdits:0,plantedDefeats:0,elapsedSimulationSeconds:sim.state.adventure.elapsed,acceptedCommands:actions,events,finalStats:A.stats(sim.state.adventure),hp:sim.state.adventure.hp,defeated:sim.state.adventure.defeated,companion:sim.state.adventure.companion,reward:sim.state.adventure.reward};fs.writeFileSync(path.join(out,'CHAPTER_JOURNEY_REPORT.json'),JSON.stringify(report,null,2));return report;}
if(require.main===module)console.log(JSON.stringify(journey(),null,2));module.exports={journey};
