/* Known-answer fixtures intentionally set positions/vitals for independent rule cases.
 * crossing_journey.cjs is the separate accepted-command, no-grant journey. */
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../src/core.js'),A=require('../src/adventure.js'),X=require('../src/crossing.js'),B=require('../src/beacon.js'),T=require('../src/combat.js'),AR=require('../src/arsenal.js');
const source=()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/REALM10_CHAPTER_III_BASE_EARNED.json')));let seq=0;
const cmd=(s,t,p={})=>s.adventureCommand('cross-test-'+(++seq),t,p),step=(s,t)=>{for(let i=0;i<Math.ceil(t/.05);i++)s.tick(.05);},at=(s,q)=>{s.state.player={x:q.x,z:q.z,yaw:0};s.playerPath=[];};
const snap=s=>JSON.stringify(s.snapshot());function refused(s,t,p={}){const old=snap(s);const r=cmd(s,t,p);assert.equal(r.ok,false,t);assert.equal(snap(s),old,'no mutation from refused '+t);return r;}
function road(){const s=new C.Simulation(source());at(s,{x:44,z:6});assert.ok(cmd(s,'road-enter').ok);at(s,X.GATE);return s;}
function town(){const s=road();assert.ok(cmd(s,'cross-enter').ok);return s;}
function talk(s){at(s,X.PLACES.find(q=>q.id==='keeper'));assert.ok(cmd(s,'cross-meet').ok);}
function cleared(){const s=town();talk(s);for(const e of A.runtime(s).enemies)A.damageEnemy(s,e,10000);at(s,X.CLAPPER);assert.ok(cmd(s,'cross-survey').ok);assert.ok(cmd(s,'cross-clapper').ok);at(s,X.PLACES.find(q=>q.id==='court'));assert.ok(cmd(s,'cross-repair').ok);return s;}
function finished(){const s=cleared();for(const b of X.BELLS){at(s,b);step(s,.7);assert.ok(cmd(s,'cross-ring',{id:b.id}).ok);}return s;}
test('09 save migrates without mutating original or losing chapters',()=>{const old=source(),str=JSON.stringify(old),s=C.validate(old);assert.equal(s.version,9);assert.equal(s.adventure.version,7);assert.deepEqual(s.adventure.crossing,X.fresh());assert.deepEqual(s.adventure.beacon,old.adventure.beacon);for(const k of['score','retreat','sandbox','visitor','flowers','notes'])assert.deepEqual(s[k],old[k]);assert.equal(JSON.stringify(old),str);assert.equal(s.settings.cameraCutaway,true);});
test('new world has no free entry, equipment, attunement or chapter rewards',()=>{const s=C.fresh();assert.deepEqual(s.adventure.crossing,X.fresh());assert.ok(!s.adventure.owned.some(id=>id in X.GEAR));});
for(const[name,mut]of Object.entries({wrongVersion:s=>s.version=2,missingField:s=>delete s.attuned,nonbool:s=>s.entered=1,unvisitedAttune:s=>s.attuned=true,unvisitedProject:s=>s.projects=['pantry'],unknownProject:s=>s.projects=['__proto__'],duplicateProject:s=>s.projects=['lamps','lamps'],earlyRepair:s=>s.repaired=true,earlyComplete:s=>s.complete=true,earlyReward:s=>s.reward=true}))test('strict crossing save rejects '+name,()=>{const s=C.fresh();mut(s.adventure.crossing);assert.throws(()=>C.validate(s));});
test('entry requires the defended beacon and actual gate location',()=>{let s=new C.Simulation(source());refused(s,'cross-enter');s=road();at(s,{x:0,z:17});refused(s,'cross-enter');at(s,X.GATE);s.state.adventure.beacon=B.fresh();refused(s,'cross-enter');});
test('entry resets target/auto and gives no items or health',()=>{const s=road(),a=s.state.adventure,old=snap(s);a.hp=80;a.stamina=60;T.runtime(s).target='gone';T.runtime(s).auto=true;const inv=JSON.stringify(a.owned),coins=a.coins;assert.ok(cmd(s,'cross-enter').ok);assert.equal(s.room,'crossing');assert.equal(a.crossing.entered,true);assert.equal(a.hp,80);assert.equal(a.coins,coins);assert.equal(JSON.stringify(a.owned),inv);assert.equal(T.runtime(s).auto,false);assert.equal(T.runtime(s).target,null);assert.equal(A.runtime(s).enemies.length,3);});
test('all named places, bells, encounter homes, clapper and entry are reachable',()=>{const s=town();for(const q of[...X.PLACES,...X.BELLS,...X.ENEMIES,X.CLAPPER]){assert.ok(X.walkable(q.x,q.z),JSON.stringify(q));assert.ok(C.pathfind(X.ENTRY,q,s.navRoom),'path '+(q.name||'clapper'));}});
test('buildings and outer bounds stop walking and arrows',()=>{for(const b of X.BUILDINGS){assert.equal(X.walkable(b.x,b.z),false);assert.equal(X.projectileGround(b.x,b.z),false);}for(const[x,z]of[[22,0],[0,-31],[0,29],[NaN,0]])assert.equal(X.walkable(x,z),false);assert.equal(X.line({x:-16,z:11},{x:-8,z:11}),false);});
test('stream blocks walking except bridge but not travelling arrows',()=>{assert.equal(X.walkable(X.riverX(4),4),false);assert.equal(X.projectileGround(X.riverX(4),4),true);assert.equal(X.walkable(X.riverX(18),18),true);assert.ok(C.pathfind({x:14,z:16},{x:19,z:16},{id:'crossing'}));});
test('outdoor construction and gathering cannot mutate village geography',()=>{const s=town(),v=JSON.stringify({...s.state.sandbox,recentCommands:[]});assert.equal(s.sandboxCommand('deny-place','place',{x:0,z:20}).ok,false);assert.equal(s.sandboxCommand('deny-gather','gather',{id:'timber-1'}).ok,false);assert.equal(JSON.stringify({...s.state.sandbox,recentCommands:[]}),v);});
test('public forge is a true workbench; components cost actual material',()=>{const s=town();s.state.sandbox.inventory.wood=10;at(s,X.PLACES.find(q=>q.id==='workbench'));assert.ok(AR.atBench(s));const n=s.state.sandbox.inventory.plank;assert.ok(s.sandboxCommand('plank','craft',{recipe:'plank'}).ok);assert.ok(s.state.sandbox.inventory.wood<10);assert.ok(s.state.sandbox.inventory.plank>n);at(s,X.ENTRY);assert.equal(AR.atBench(s),false);assert.equal(s.sandboxCommand('plank2','craft',{recipe:'plank'}).ok,false);});
test('meeting and clue require local proximity and are single claim',()=>{const s=town();refused(s,'cross-meet');talk(s);refused(s,'cross-meet');refused(s,'cross-inspect');at(s,X.PLACES.find(q=>q.id==='inscription'));assert.ok(cmd(s,'cross-inspect').ok);refused(s,'cross-inspect');});
test('Briar search has real location, bond, follow and route prerequisites',()=>{const s=town();refused(s,'cross-seek');talk(s);refused(s,'cross-seek');at(s,X.PLACES.find(q=>q.id==='thicket'));s.state.adventure.companion.mode='stay';refused(s,'cross-seek');s.state.adventure.companion.mode='follow';const c=A.runtime(s).companion;Object.assign(c,{...s.state.player,room:'crossing'});assert.ok(cmd(s,'cross-seek').ok);refused(s,'cross-seek');for(let i=0;i<150&&!s.state.adventure.crossing.clapperRevealed;i++)step(s,.05);assert.equal(s.state.adventure.crossing.clapperRevealed,true);assert.ok(Math.hypot(c.x-X.CLAPPER.x,c.z-X.CLAPPER.z)<5);});
test('manual close inspection works when Briar stays behind',()=>{const s=town();talk(s);s.state.adventure.companion.mode='stay';at(s,X.CLAPPER);assert.ok(cmd(s,'cross-survey').ok);refused(s,'cross-clapper');A.damageEnemy(s,A.runtime(s).enemies.find(e=>e.id==='cross-thorn'),10000);assert.ok(cmd(s,'cross-clapper').ok);refused(s,'cross-clapper');});
test('search pause keeps discovery and companion motion frozen',()=>{const s=town();talk(s);at(s,X.PLACES.find(q=>q.id==='thicket'));Object.assign(A.runtime(s).companion,{...s.state.player});cmd(s,'cross-seek');s.paused=true;let p={...A.runtime(s).companion},old=snap(s);step(s,8);assert.equal(snap(s),old);assert.equal(A.runtime(s).companion.x,p.x);refused(s,'cross-seek');});
test('new guardian uses distinct ring and circle impact rules',()=>{let e={aim:{x:0,z:0},ringMode:'outer'};assert.equal(X.inImpact(e,{x:0,z:0}),false);assert.equal(X.inImpact(e,{x:3,z:0}),true);assert.equal(X.inImpact(e,{x:7,z:0}),false);e.ringMode='inner';assert.equal(X.inImpact(e,{x:0,z:0}),true);assert.equal(X.inImpact(e,{x:3,z:0}),false);});
test('wide ring rewards entering center; next tell alternates to inner strike',()=>{const s=town();s.state.adventure.companion.mode='stay';at(s,{x:0,z:-22});step(s,1.1);let e=A.runtime(s).enemies.find(e=>e.custom==='bell');assert.equal(e.mode,'windup');assert.equal(e.ringMode,'outer');const hp=s.state.adventure.hp;step(s,1.8);assert.equal(s.state.adventure.hp,hp);step(s,2.4);assert.equal(e.ringMode,'inner');step(s,1.3);assert.ok(s.state.adventure.hp<hp);});
test('new encounters are targetable and respond to real autoattack',()=>{const s=town();at(s,{x:0,z:-22});s.state.adventure.companion.mode='stay';assert.ok(cmd(s,'target-select',{id:'cross-warden'}).ok);assert.ok(cmd(s,'auto-toggle').ok);const e=T.selected(s),hp=e.hp;step(s,1.2);assert.ok(e.hp<hp);assert.equal(s.state.player.z,-22);});
test('clear event caches pay the new roster once and persist separately',()=>{const s=town(),a=s.state.adventure,e=A.runtime(s).enemies[0];A.damageEnemy(s,e,10000);assert.ok(a.drops.includes(e.id));at(s,X.ENEMIES[0]);const coins=a.coins;assert.ok(cmd(s,'loot',{id:e.id}).ok);assert.equal(a.coins,coins+6);refused(s,'loot',{id:e.id});assert.deepEqual(new C.Simulation(s.snapshot()).state.adventure.defeated,a.defeated);});
test('bell repair requires clapper and all three clearances',()=>{const s=town();talk(s);at(s,X.PLACES.find(q=>q.id==='court'));refused(s,'cross-repair');});
test('wrong bell order restarts sequence without taking inventory',()=>{const s=cleared();const old=s.state.adventure.coins;at(s,X.BELLS[2]);assert.ok(cmd(s,'cross-ring',{id:'sun'}).ok);assert.deepEqual(X.runtime(s).tones,[]);assert.equal(s.state.adventure.coins,old);assert.equal(s.state.adventure.crossing.complete,false);refused(s,'cross-ring',{id:'__proto__'});});
test('bell cannot be played remotely or faster than its cooldown',()=>{const s=cleared();at(s,X.ENTRY);refused(s,'cross-ring',{id:'leaf'});at(s,X.BELLS[0]);assert.ok(cmd(s,'cross-ring',{id:'leaf'}).ok);refused(s,'cross-ring',{id:'leaf'});});
test('three local ordered tones complete the bell but not the reward',()=>{const s=finished();assert.equal(s.state.adventure.crossing.complete,true);assert.equal(s.state.adventure.crossing.reward,false);assert.ok(!s.state.adventure.owned.includes('chime_clasp'));});
test('Rowan reward is atomic, local and cannot be duplicated',()=>{const s=finished();refused(s,'cross-reward');at(s,X.PLACES.find(q=>q.id==='keeper'));s.state.adventure.coins=9990;refused(s,'cross-reward');s.state.adventure.coins=10;assert.ok(cmd(s,'cross-reward').ok);assert.equal(s.state.adventure.coins,28);assert.equal(s.state.adventure.owned.filter(x=>x==='chime_clasp').length,1);refused(s,'cross-reward');assert.doesNotThrow(()=>new C.Simulation(s.snapshot()));});
test('free bell playing after completion cannot reset quest or pay loot',()=>{const s=finished();step(s,.7);at(s,X.BELLS[2]);const coins=s.state.adventure.coins;assert.ok(cmd(s,'cross-ring',{id:'sun'}).ok);assert.equal(s.state.adventure.crossing.complete,true);assert.equal(s.state.adventure.coins,coins);});
test('tone entry is transient; repair, kills and clues survive reload',()=>{const s=cleared();at(s,X.BELLS[0]);cmd(s,'cross-ring',{id:'leaf'});const cold=new C.Simulation(s.snapshot());assert.equal(cold.room,null);assert.equal(cold.state.adventure.crossing.repaired,true);assert.equal(cold.state.adventure.crossing.complete,false);assert.deepEqual(X.runtime(cold).tones,[]);assert.deepEqual(cold.state.adventure.defeated,s.state.adventure.defeated);});
test('merchant exchanges fail cleanly when funds, quantities or scope fail',()=>{const s=town();refused(s,'cross-trade',{offer:'coat'});at(s,X.PLACES.find(q=>q.id==='shop'));s.state.adventure.coins=0;refused(s,'cross-trade',{offer:'coat'});refused(s,'cross-trade',{offer:'tonic'});refused(s,'cross-trade',{offer:'constructor'});s.state.adventure.ore=0;refused(s,'cross-trade',{offer:'copper'});});
test('merchant armor retains proper slot and does not heal on purchase/equip',()=>{const s=town(),a=s.state.adventure;at(s,X.PLACES.find(q=>q.id==='shop'));a.coins=24;a.hp=70;assert.ok(cmd(s,'cross-trade',{offer:'coat'}).ok);assert.equal(a.coins,0);assert.equal(a.hp,70);assert.ok(cmd(s,'equip',{id:'keeper_coat'}).ok);assert.equal(a.equipment.armor,'keeper_coat');assert.equal(a.hp,70);refused(s,'cross-trade',{offer:'coat'});});
test('ore and berries exchange deduct exactly, overflow is refused',()=>{const s=town(),a=s.state.adventure;at(s,X.PLACES.find(q=>q.id==='shop'));a.ore=2;a.coins=10;s.state.sandbox.inventory.berry=2;cmd(s,'cross-trade',{offer:'copper'});cmd(s,'cross-trade',{offer:'berries'});assert.equal(a.ore,0);assert.equal(a.coins,14);assert.equal(s.state.sandbox.inventory.berry,0);a.ore=2;a.coins=9998;refused(s,'cross-trade',{offer:'copper'});});
test('inn restores actual vitals and denies service outside its porch',()=>{const s=town(),a=s.state.adventure;a.hp=20;a.stamina=1;a.tonics=0;refused(s,'cross-rest');at(s,X.PLACES.find(q=>q.id==='inn'));const soul=JSON.stringify(a.beacon.soul);assert.ok(cmd(s,'cross-rest').ok);assert.equal(a.hp,A.stats(a).maxHP);assert.equal(a.stamina,100);assert.equal(a.tonics,3);assert.equal(JSON.stringify(a.beacon.soul),soul);});
test('common works deduct actual materials once and preserve home layout',()=>{const s=town(),a=s.state.adventure,inv=s.state.sandbox.inventory;at(s,X.PLACES.find(q=>q.id==='board'));inv.plank=4;inv.stone=6;inv.berry=4;const coins=a.coins,gems=a.arsenal.gems.ruby,layout=JSON.stringify(s.state.sandbox.placed);cmd(s,'cross-project',{id:'lamps'});cmd(s,'cross-project',{id:'pantry'});assert.equal(inv.plank,0);assert.equal(inv.stone,0);assert.equal(inv.berry,0);assert.equal(a.coins,coins+12);assert.equal(a.arsenal.gems.ruby,gems+1);assert.equal(JSON.stringify(s.state.sandbox.placed),layout);refused(s,'cross-project',{id:'lamps'});refused(s,'cross-project',{id:'pantry'});});
test('commission failure leaves supplies and flags untouched',()=>{const s=town();at(s,X.PLACES.find(q=>q.id==='board'));s.state.sandbox.inventory.plank=0;refused(s,'cross-project',{id:'lamps'});s.state.sandbox.inventory.berry=4;s.state.adventure.arsenal.gems.ruby=9999;refused(s,'cross-project',{id:'pantry'});refused(s,'cross-project',{id:'__proto__'});});
test('waystone needs discovery and physical origin, does not heal or charge',()=>{const s=town(),a=s.state.adventure;refused(s,'waystone-travel',{id:'commons'});at(s,X.WAYSTONES.bellweather);cmd(s,'cross-attune');refused(s,'cross-attune');refused(s,'waystone-travel',{id:'bellweather'});refused(s,'waystone-travel',{id:'__proto__'});a.hp=65;a.stamina=25;const coins=a.coins;assert.ok(cmd(s,'waystone-travel',{id:'commons'}).ok);assert.equal(s.room,null);assert.equal(a.hp,65);assert.equal(a.stamina,25);assert.equal(a.coins,coins);assert.ok(cmd(s,'waystone-travel',{id:'bellweather'}).ok);assert.equal(s.room,'crossing');assert.equal(a.hp,65);});
test('unattuned village cannot be fast-travelled to',()=>{const s=road();at(s,X.WAYSTONES.sunward);refused(s,'waystone-travel',{id:'bellweather'});});
test('travel refuses active attack modes and beacon assault',()=>{const s=town();at(s,X.WAYSTONES.bellweather);cmd(s,'cross-attune');let e=A.runtime(s).enemies[0];Object.assign(e,{x:2,z:17,mode:'windup'});refused(s,'waystone-travel',{id:'commons'});e.mode='idle';B.runtime(s).phase='assault';refused(s,'waystone-travel',{id:'commons'});});
test('ordinary departure is local and preserves progress',()=>{const s=town();at(s,{x:0,z:9});refused(s,'cross-leave');at(s,X.ENTRY);assert.ok(cmd(s,'cross-leave').ok);assert.equal(s.room,'road');assert.equal(s.state.player.z,-27);assert.equal(s.state.adventure.crossing.entered,true);});
test('same command receipt cannot be repurposed or pay twice',()=>{const s=town();at(s,X.WAYSTONES.bellweather);const r=s.adventureCommand('attune-id','cross-attune',{});assert.ok(r.ok);const old=snap(s);assert.ok(s.adventureCommand('attune-id','cross-attune',{}).duplicate);assert.equal(snap(s),old);assert.equal(s.adventureCommand('attune-id','cross-rest',{}).ok,false);assert.equal(snap(s),old);});
test('defeat recovery preserves crossing facts and revives outside',()=>{const s=finished();s.state.adventure.hp=1;A.runtime(s).invincible=0;A.takeDamage(s,1000);assert.equal(s.state.adventure.hp,0);refused(s,'cross-ring',{id:'sun'});assert.ok(cmd(s,'revive').ok);assert.equal(s.room,null);assert.equal(s.state.adventure.crossing.complete,true);});
test('cutaway preference is persisted and old migration defaults on',()=>{const old=source();assert.equal(C.validate(old).settings.cameraCutaway,true);const s=C.validate(old);s.settings.cameraCutaway=false;assert.equal(C.validate(s).settings.cameraCutaway,false);});
