/* Labelled synthetic boundary fixtures. Journeys separately earn their resources. */
const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),A=require('../src/adventure.js'),E=require('../src/earth.js');
const S=require('../src/earth-story.js');
let serial=0;
const cmd=(sim,t,p={})=>A.command(sim,'rain-test-'+(++serial),'earth-story-'+t,p);
function fresh(){const sim=new C.Simulation(C.fresh());sim.state.player={x:11,z:9,yaw:0};assert.ok(A.command(sim,'kit','start').ok);sim.room=E.ROOM;sim.returnPos={x:0,z:23,yaw:0};sim.state.player={...S.GIVER,yaw:0};return sim;}
function step(sim,id){sim.state.player={...S.STEPS.find(s=>s.id===id),yaw:0};return cmd(sim,'step',{id});}
function accepted(){const sim=fresh();assert.ok(cmd(sim,'accept').ok);return sim;}
function ready(route){const sim=accepted();sim.state.sandbox.inventory.wood=2;for(const id of S.ROUTES.find(r=>r.id===route).steps)assert.ok(step(sim,id).ok,id);sim.state.player={...S.GIVER,yaw:0};assert.ok(cmd(sim,'dispatch',{route}).ok);return sim;}
test('inspection and declined job create no progress; acceptance needs kit and proximity',()=>{const sim=fresh(),before=sim.snapshot();assert.equal(S.status(sim.state.adventure).accepted,false);assert.deepEqual(sim.snapshot(),before);sim.state.player={x:0,z:24,yaw:0};assert.equal(cmd(sim,'accept').ok,false);assert.equal(step(sim,'mill-root').ok,false);sim.room=null;sim.state.player={...S.GIVER,yaw:0};assert.equal(cmd(sim,'accept').ok,false);const unstarted=new C.Simulation(C.fresh());unstarted.room=E.ROOM;unstarted.state.player={...S.GIVER,yaw:0};assert.equal(cmd(unstarted,'accept').ok,false);});
test('every task uses supported reachable Earth ground',()=>{for(const point of [S.GIVER,S.DESTINATION,...S.STEPS]){assert.ok(E.walkable(point.x,point.z),point.id);assert.ok(C.pathfind(E.ENTRY,point,{id:E.ROOM}),point.id);}});
test('mill prerequisites and timber cost are atomic and charged once',()=>{const sim=accepted();assert.equal(step(sim,'mill-gate').ok,false);assert.ok(step(sim,'mill-root').ok);sim.state.sandbox.inventory.wood=1;sim.state.player={...S.STEPS.find(s=>s.id==='mill-gate'),yaw:0};let before=sim.snapshot();assert.equal(cmd(sim,'step',{id:'mill-gate'}).ok,false);assert.deepEqual(sim.snapshot(),before);sim.state.sandbox.inventory.wood=2;assert.ok(cmd(sim,'step',{id:'mill-gate'}).ok);assert.equal(sim.state.sandbox.inventory.wood,0);before=sim.snapshot();assert.equal(cmd(sim,'step',{id:'mill-gate'}).ok,false);assert.deepEqual(sim.snapshot(),before);});
for(const route of ['mill','quarry','detour'])test(route+' completes with one finite payout and no gear, XP or chapter changes',()=>{const sim=ready(route),a=sim.state.adventure,before=sim.snapshot();assert.equal(cmd(sim,'claim').ok,false);sim.state.player={...S.DESTINATION,yaw:0};assert.equal(cmd(sim,'claim').ok,false);assert.ok(cmd(sim,'arrive').ok);assert.ok(cmd(sim,'claim').ok);assert.equal(a.ore,before.adventure.ore+3);assert.equal(a.coins,before.adventure.coins+4);assert.equal(sim.state.sandbox.inventory.fiber,before.sandbox.inventory.fiber+2);for(const k of ['xp','equipment','owned','arsenal','starter','pursuit','classPath','road','beacon','crossing','companion'])assert.deepEqual(a[k],before.adventure[k],k);a.receipts=[];let again=sim.snapshot();assert.equal(cmd(sim,'claim').ok,false);assert.equal(cmd(sim,'dispatch',{route}).ok,false);assert.equal(cmd(sim,'accept').ok,false);assert.deepEqual(sim.snapshot(),again);});
test('quarry and detour never consume personal materials; both observations precede lane marking',()=>{const sim=accepted(),inv={...sim.state.sandbox.inventory};assert.equal(step(sim,'detour-mark').ok,false);assert.ok(step(sim,'detour-shelter').ok);assert.equal(step(sim,'detour-mark').ok,false);assert.ok(step(sim,'detour-ridge').ok);assert.ok(step(sim,'detour-mark').ok);assert.equal(step(sim,'quarry-grade').ok,false);assert.ok(step(sim,'quarry-reserve').ok);assert.ok(step(sim,'quarry-grade').ok);assert.deepEqual(sim.state.sandbox.inventory,inv);});
for(const capacity of ['ore','coins','fiber'])test('full '+capacity+' refuses entire payout and preserves completed entitlement',()=>{const sim=ready('quarry');sim.state.player={...S.DESTINATION,yaw:0};assert.ok(cmd(sim,'arrive').ok);const obj=capacity==='fiber'?sim.state.sandbox.inventory:sim.state.adventure;obj[capacity]=capacity==='fiber'?globalThis.RealmSandbox.MAX:9999;const before=sim.snapshot();assert.equal(cmd(sim,'claim').ok,false);assert.deepEqual(sim.snapshot(),before);obj[capacity]-=10;assert.ok(cmd(sim,'claim').ok);});
test('all durable stages survive canonical reload with no implicit rewards or reacceptance',()=>{let sim=accepted();function reload(){const old=sim.snapshot(),loaded=new C.Simulation(old);assert.deepEqual(loaded.snapshot(),old);assert.equal(loaded.room,null);sim=loaded;sim.room=E.ROOM;sim.returnPos={x:0,z:23,yaw:0};}reload();for(const id of ['detour-ridge','detour-shelter','detour-mark']){assert.ok(step(sim,id).ok);reload();}sim.state.player={...S.GIVER,yaw:0};assert.ok(cmd(sim,'dispatch',{route:'detour'}).ok);reload();sim.state.player={...S.DESTINATION,yaw:0};assert.ok(cmd(sim,'arrive').ok);reload();sim.state.player={...S.DESTINATION,yaw:0};assert.ok(cmd(sim,'claim').ok);reload();sim.state.player={...S.DESTINATION,yaw:0};const before=sim.snapshot();assert.equal(cmd(sim,'claim').ok,false);assert.deepEqual(sim.snapshot(),before);});
test('schema7 migration preserves banked XP and every older canonical field without mutating input',()=>{for(const xp of [0,29,30,79,80,149,150,259,260,9999]){const old=fresh().snapshot();old.adventure.version=7;delete old.adventure.earthStory;old.adventure.xp=xp;const text=JSON.stringify(old),out=C.validate(old);assert.equal(out.adventure.version,9);assert.deepEqual(out.adventure.earthStory,S.fresh());const a={...out.adventure};delete a.earthStory;a.version=7;assert.deepEqual(a,old.adventure);assert.equal(JSON.stringify(old),text);}});
test('current-schema missing, future and inconsistent story state refuses instead of erasing',()=>{const mutations=[s=>{delete s.adventure.earthStory;},s=>s.adventure.earthStory.version=2,s=>s.adventure.earthStory.claimed=true,s=>s.adventure.earthStory.arrived=true,s=>s.adventure.earthStory.dispatch='mill',s=>s.adventure.earthStory.steps=['mill-gate'],s=>s.adventure.earthStory.steps=['quarry-reserve','quarry-reserve'],s=>s.adventure.earthStory.steps=['unknown'],s=>s.adventure.version=10];for(const change of mutations){const s=fresh().snapshot();change(s);assert.throws(()=>C.validate(s));}});
test('other improvements remain available after claim without replaying delivery or payment',()=>{const sim=ready('quarry');sim.state.player={...S.DESTINATION,yaw:0};assert.ok(cmd(sim,'arrive').ok);assert.ok(cmd(sim,'claim').ok);const coins=sim.state.adventure.coins;for(const id of ['detour-ridge','detour-shelter','detour-mark','mill-root','mill-gate'])assert.ok(step(sim,id).ok);assert.equal(sim.state.adventure.earthStory.dispatch,'quarry');assert.equal(sim.state.adventure.coins,coins);assert.ok(C.validate(sim.snapshot()));});
