/* Labelled synthetic authority boundaries; earned journeys are separate. */
const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),A=require('../src/adventure.js'),E=require('../src/earth.js'),N=require('../src/earth-notes.js');
let id=0;const cmd=(s,t,p={})=>s.adventureCommand('notes-boundary-'+(++id),'earth-notes-'+t,p);
function source(){const s=new C.Simulation();s.state.player={x:11,z:9,yaw:0};assert.ok(s.adventureCommand('kit','start').ok);s.state.adventure.earthStory={version:1,accepted:true,steps:['quarry-reserve','quarry-grade'],dispatch:'quarry',arrived:true,claimed:false};table(s);return s;}
function table(s){s.room='observatory';s.returnPos={x:9,z:-5.8,yaw:0};s.state.player={...N.TABLE,yaw:0};}
function mark(s,p){s.room=E.ROOM;s.returnPos={x:0,z:23,yaw:0};s.state.player={...p,yaw:0};return cmd(s,'observe',{id:p.id});}
function complete(){const s=source();assert.ok(cmd(s,'accept').ok);for(const p of N.MARKS)assert.ok(mark(s,p).ok);table(s);return s;}
function refused(s,t,p={}){const before=s.snapshot();assert.equal(cmd(s,t,p).ok,false);assert.deepEqual(s.snapshot(),before);}
test('entry requires resolved delivery and physical field table; unpaid arrival is eligible',()=>{const s=source();s.state.adventure.earthStory.arrived=false;refused(s,'accept');s.state.adventure.earthStory.arrived=true;s.room=null;s.state.player={x:9,z:-5.8,yaw:0};refused(s,'accept');s.room='observatory';s.state.player={x:4,z:3,yaw:0};refused(s,'accept');table(s);assert.ok(cmd(s,'accept').ok);assert.equal(s.state.adventure.earthStory.claimed,false);refused(s,'accept');});
test('table and all marks have real connected, walkable approaches',()=>{assert.ok(C.pathfind({x:0,z:3.5},N.TABLE,'observatory'));for(const p of N.MARKS){assert.ok(E.walkable(p.x,p.z));assert.ok(C.pathfind(E.ENTRY,p,{id:E.ROOM}));}});
test('no pre-accept backfill; each accepted physical observation occurs once',()=>{const s=source();assert.equal(mark(s,N.MARKS[0]).ok,false);table(s);assert.ok(cmd(s,'accept').ok);assert.deepEqual(s.state.adventure.earthNotes.marks,[]);for(const p of [...N.MARKS].reverse()){assert.ok(mark(s,p).ok);refused(s,'observe',{id:p.id});}refused(s,'observe',{id:'unknown'});s.state.player={x:0,z:24,yaw:0};refused(s,'observe',{id:N.MARKS[0].id});});
test('table comparison rejects missing clues, obstructed or distant approach and malformed bearings atomically',()=>{const s=source();assert.ok(cmd(s,'accept').ok);refused(s,'compare',{bearing:0});for(const p of N.MARKS)assert.ok(mark(s,p).ok);refused(s,'compare',{bearing:0});table(s);for(const bearing of [15,60,90,345,-180,360,NaN,Infinity,null,'0',{},1.5])refused(s,'compare',{bearing});s.state.player={x:0,z:-3.3,yaw:0};refused(s,'compare',{bearing:0});});
for(const bearing of [0,180])for(const interpretation of ['old-road','waterworks'])test('axis '+bearing+' and honest '+interpretation+' preserve every reward and earlier system',()=>{const s=complete(),before=s.snapshot();assert.ok(cmd(s,'compare',{bearing}).ok);refused(s,'record',{interpretation:'confirmed-road-of-light'});refused(s,'record',{interpretation:['old-road']});assert.ok(cmd(s,'record',{interpretation}).ok);for(const k of ['xp','ore','coins','owned','equipment','arsenal','pursuit','starter','classPath','earthStory','road','beacon','crossing','companion'])assert.deepEqual(s.state.adventure[k],before.adventure[k],k);for(const k of ['sandbox','notes','score','retreat'])assert.deepEqual(s.state[k],before[k],k);s.state.adventure.receipts=[];refused(s,'record',{interpretation});refused(s,'record',{interpretation:interpretation==='old-road'?'waterworks':'old-road'});refused(s,'compare',{bearing});assert.ok(C.validate(s.snapshot()));});
test('each accepted, partly observed, compared and recorded stage survives reload',()=>{let s=source();function reload(){const before=s.snapshot();s=new C.Simulation(before);assert.deepEqual(s.snapshot(),before);table(s);}assert.ok(cmd(s,'accept').ok);reload();for(const p of N.MARKS){assert.ok(mark(s,p).ok);reload();}assert.ok(cmd(s,'compare',{bearing:180}).ok);reload();assert.ok(cmd(s,'record',{interpretation:'waterworks'}).ok);reload();refused(s,'record',{interpretation:'waterworks'});});
test('schema8 migration preserves unpaid delivery and all prior fields at XP boundaries without changing input',()=>{for(const xp of [0,29,30,79,80,149,150,259,260,9999]){const old=source().snapshot();old.adventure.version=8;delete old.adventure.earthNotes;old.adventure.xp=xp;const text=JSON.stringify(old),out=C.validate(old);assert.equal(out.adventure.version,9);assert.deepEqual(out.adventure.earthNotes,N.fresh());delete out.adventure.earthNotes;out.adventure.version=8;assert.deepEqual(out,old);assert.equal(JSON.stringify(old),text);}});
test('missing, future, unknown and inconsistent notes refuse without erasing state',()=>{for(const change of [w=>delete w.adventure.earthNotes,w=>w.adventure.earthNotes.version=2,w=>w.adventure.version=10,w=>w.adventure.earthNotes.marks=['orchard-stone'],w=>w.adventure.earthNotes.compared=true,w=>w.adventure.earthNotes.interpretation='old-road',w=>w.adventure.earthNotes.accepted='yes']){const w=source().snapshot();change(w);assert.throws(()=>C.validate(w));}const s=complete();for(const marks of [['unknown'],['orchard-stone','orchard-stone']]){const w=s.snapshot();w.adventure.earthNotes.marks=marks;assert.throws(()=>C.validate(w));}const w=s.snapshot();w.adventure.earthStory.arrived=false;assert.throws(()=>C.validate(w));});

test('array-coerced interpretation cannot masquerade as a stable ID in a completed save',()=>{const s=complete();assert.ok(cmd(s,'compare',{bearing:0}).ok);const w=s.snapshot();w.adventure.earthNotes.interpretation=['old-road'];assert.throws(()=>C.validate(w));});
