/* Candidate integration checks. Run after loading the reviewed schema adapter. */
'use strict';
require('../src/gathering-adapter.js');
const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),A=require('../src/adventure.js'),Q=require('../src/gathering.js'),E=require('../src/earth.js'),M=require('../src/gathering-music.js');
function fixture(){const s=new C.Simulation();s.state.adventure.started=true;s.state.adventure.earthStory={version:1,accepted:true,steps:['detour-ridge','detour-shelter','detour-mark'],dispatch:'detour',arrived:true,claimed:false};s.room=E.ROOM;s.returnPos={x:0,z:23,yaw:0};s.state.player={...Q.TABLE,yaw:0};return s;}
let serial=0;const run=(s,t,p={})=>s.adventureCommand('table-test-'+(++serial),'gathering-'+t,p);
function prepare(s){assert.ok(run(s,'accept').ok);for(const p of Q.TASKS){s.state.player={x:p.x,z:p.z,yaw:0};assert.ok(run(s,'prepare',{id:p.id}).ok);}s.state.player={...Q.TABLE,yaw:0};}
function prior(s){const a=structuredClone(s.state.adventure);for(const k of ['earthGathering','revision','receipts','elapsed'])delete a[k];return{a,score:structuredClone(s.state.score),notes:structuredClone(s.state.notes),sandbox:structuredClone(s.state.sandbox),retreat:structuredClone(s.state.retreat)};}
test('schema 9 migrates non-destructively with an unaccepted invitation',()=>{const old=fixture().state.adventure;old.version=9;delete old.earthGathering;const before=structuredClone(old),next=A.validate(old);assert.deepEqual(old,before);assert.equal(next.version,10);assert.deepEqual(next.earthGathering,Q.fresh());for(const k of Object.keys(old))if(k!=='version')assert.deepEqual(next[k],old[k]);});
test('missing current record and forward schema are refused',()=>{const a=fixture().state.adventure;assert.throws(()=>A.validate({...a,earthGathering:undefined}));assert.throws(()=>A.validate({...a,version:11}));});
test('arrival not payment opens the invitation',()=>{const s=fixture();s.state.adventure.earthStory.arrived=false;const b=s.snapshot();assert.equal(run(s,'accept').ok,false);assert.deepEqual(s.snapshot(),b);s.state.adventure.earthStory.arrived=true;assert.ok(run(s,'accept').ok);assert.equal(s.state.adventure.earthStory.claimed,false);});
test('supported places are reachable by actual pathfinder',()=>{for(const p of Q.TASKS){assert.ok(E.walkable(p.x,p.z),p.id);assert.ok(C.pathfind(Q.TABLE,p,{id:E.ROOM}),p.id);}const s=fixture();assert.ok(run(s,'accept').ok);s.state.player={x:0,z:24,yaw:0};const b=s.snapshot();assert.equal(run(s,'prepare',{id:'cloth'}).ok,false);assert.deepEqual(s.snapshot(),b);});
test('all arrangements complete silently without economy, score or campaign changes',()=>{for(const verse of Object.keys(Q.VERSES)){const s=fixture(),b=prior(s);prepare(s);assert.ok(run(s,'verse',{verse}).ok);assert.ok(run(s,'share').ok);assert.deepEqual(prior(s),b);assert.deepEqual(A.validate(s.state.adventure),s.state.adventure);}});
test('early or unknown actions change nothing',()=>{const s=fixture();assert.ok(run(s,'accept').ok);for(const [t,p]of [['verse',{verse:'mill'}],['share',{}],['prepare',{id:'other'}]]){const b=s.snapshot();assert.equal(run(s,t,p).ok,false);assert.deepEqual(s.snapshot(),b);}});
test('prototype and non-string choices are refused atomically',()=>{const s=fixture();prepare(s);for(const verse of ['__proto__','constructor','toString','',[],{},null,42]){const b=s.snapshot();assert.equal(run(s,'verse',{verse}).ok,false);assert.deepEqual(s.snapshot(),b);}});
test('completion cannot be repeated after receipt eviction',()=>{const s=fixture();prepare(s);assert.ok(run(s,'verse',{verse:'detour'}).ok);assert.ok(s.adventureCommand('first-share','gathering-share').ok);const b=s.snapshot();assert.equal(s.adventureCommand('first-share','gathering-share').duplicate,true);assert.deepEqual(s.snapshot(),b);s.state.adventure.receipts=[];const c=s.snapshot();for(const t of ['share','accept'])assert.equal(run(s,t).ok,false);assert.equal(run(s,'verse',{verse:'quarry'}).ok,false);assert.deepEqual(s.snapshot(),c);});
test('changed terms cannot reuse an accepted command identity',()=>{const s=fixture();assert.ok(s.adventureCommand('same','gathering-accept').ok);const b=s.snapshot();assert.equal(s.adventureCommand('same','gathering-prepare',{id:'cloth'}).ok,false);assert.deepEqual(s.snapshot(),b);});
test('paused, fallen and revision-saturated characters cannot progress',()=>{for(const kind of ['paused','fallen','revision']){const s=fixture();if(kind==='paused')s.paused=true;if(kind==='fallen')s.state.adventure.hp=0;if(kind==='revision')s.state.adventure.revision=1e9;const b=s.snapshot();assert.equal(run(s,'accept').ok,false);assert.deepEqual(s.snapshot(),b);}});
test('malformed durable combinations do not load',()=>{const a=fixture().state.adventure;for(const bad of [{...Q.fresh(),shared:true},{...Q.fresh(),verse:'mill'},{...Q.fresh(),accepted:true,prepared:['cloth','cloth']},{...Q.fresh(),accepted:true,prepared:['missing']},{...Q.fresh(),version:2},{...Q.fresh(),accepted:'yes'}])assert.throws(()=>Q.validate(bad,a));});
test('original arrangements are deterministic, finite, stereo and bounded',()=>{let prev;for(const id of Object.keys(Q.VERSES)){const d=M.render(id,8000);assert.equal(d.duration,26);assert.equal(d.channels.length,2);assert.deepEqual(d.channels,M.render(id,8000).channels);let peak=0,energy=0;for(const v of d.channels[0]){assert.ok(Number.isFinite(v));peak=Math.max(peak,Math.abs(v));energy+=v*v;}assert.ok(peak<1&&peak>.01&&energy>1);assert.ok(Math.abs(d.channels[0].at(-1))<.0001);if(prev)assert.notDeepEqual(prev,d.channels[0]);prev=d.channels[0];}assert.throws(()=>M.render('__proto__'));assert.throws(()=>M.render('mill',NaN));});
