/* Synthetic rule fixtures; actual command-earned traversal is in gathering_journey. */
'use strict';
require('../src/gathering-adapter.js');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createRequire}=require('node:module');
const C=require('../src/core.js'),A=require('../src/adventure.js'),Q=require('../src/gathering.js'),E=require('../src/earth.js'),M=require('../src/gathering-music.js');
function fixture(){const sim=new C.Simulation();sim.state.adventure.started=true;sim.state.adventure.earthStory={version:1,accepted:true,steps:['detour-ridge','detour-shelter','detour-mark'],dispatch:'detour',arrived:true,claimed:false};sim.room=E.ROOM;sim.returnPos={x:0,z:23,yaw:0};sim.state.player={...Q.TABLE,yaw:0};return sim;}
let serial=0;const run=(s,t,p={})=>s.adventureCommand('table-rule-'+(++serial),'gathering-'+t,p);
function prepare(s){assert.ok(run(s,'accept').ok);for(const p of Q.TASKS){s.state.player={x:p.x,z:p.z,yaw:0};assert.ok(run(s,'prepare',{id:p.id}).ok);}s.state.player={...Q.TABLE,yaw:0};}
function protectedState(s){const a=structuredClone(s.state.adventure);for(const k of ['earthGathering','revision','receipts','elapsed'])delete a[k];return{adventure:a,score:structuredClone(s.state.score),notes:structuredClone(s.state.notes),sandbox:structuredClone(s.state.sandbox),retreat:structuredClone(s.state.retreat)};}

test('schema 9 migrates without accepting the invitation or changing its payload',()=>{const s=fixture(),old=structuredClone(s.state.adventure);old.version=9;delete old.earthGathering;const before=structuredClone(old),next=A.validate(old);assert.deepEqual(old,before);assert.equal(next.version,10);assert.deepEqual(next.earthGathering,Q.fresh());for(const k of Object.keys(old))if(k!=='version')assert.deepEqual(next[k],old[k]);});
test('missing current record and unsupported future schemas are refused',()=>{const raw=fixture().state.adventure;assert.throws(()=>A.validate({...raw,earthGathering:undefined}));assert.throws(()=>A.validate({...raw,version:11}));});
test('the original schema 9 validator refuses the new schema',()=>{const file=path.resolve(__dirname,'../src/adventure.js'),scope={require:createRequire(file),module:{exports:{}}};vm.runInNewContext(fs.readFileSync(file,'utf8'),scope);assert.equal(scope.module.exports.VERSION,9);assert.throws(()=>scope.module.exports.validate(fixture().state.adventure),/version/);});
test('no invitation before arrival; arrival alone does not force payment',()=>{const s=fixture();s.state.adventure.earthStory.arrived=false;const before=s.snapshot();assert.equal(run(s,'accept').ok,false);assert.deepEqual(s.snapshot(),before);s.state.adventure.earthStory.arrived=true;assert.ok(run(s,'accept').ok);assert.equal(s.state.adventure.earthStory.claimed,false);});
test('every preparation location is supported and remote actions are rejected',()=>{const s=fixture();assert.ok(E.walkable(Q.TABLE.x,Q.TABLE.z));assert.ok(run(s,'accept').ok);for(const p of Q.TASKS)assert.ok(E.walkable(p.x,p.z),p.id);s.state.player={x:0,z:24,yaw:0};const before=s.snapshot();assert.equal(run(s,'prepare',{id:'cloth'}).ok,false);assert.deepEqual(s.snapshot(),before);});
test('all preparations and a silent finish preserve economy, scores and earlier history',()=>{const s=fixture(),before=protectedState(s);prepare(s);assert.ok(run(s,'verse',{verse:'mill'}).ok);assert.ok(run(s,'share').ok);assert.deepEqual(protectedState(s),before);assert.equal(s.state.adventure.earthGathering.shared,true);assert.equal(s.state.adventure.earthStory.dispatch,'detour');});
test('each arrangement can be chosen independently of the delivery route',()=>{for(const verse of Object.keys(Q.VERSES)){const s=fixture();prepare(s);assert.ok(run(s,'verse',{verse}).ok);assert.ok(run(s,'share').ok);assert.equal(s.state.adventure.earthGathering.verse,verse);}});
test('no early verse, early completion or unknown choice writes state',()=>{const s=fixture();assert.ok(run(s,'accept').ok);for(const [t,p]of [['verse',{verse:'mill'}],['share',{}],['prepare',{id:'other'}]]){const before=s.snapshot();assert.equal(run(s,t,p).ok,false);assert.deepEqual(s.snapshot(),before);}prepareFresh=undefined;});
test('prototype keys and non-string musical choices are refused atomically',()=>{const s=fixture();prepare(s);for(const value of ['__proto__','constructor','toString','',[],{},null,42]){const before=s.snapshot();assert.equal(run(s,'verse',{verse:value}).ok,false);assert.deepEqual(s.snapshot(),before);}});
test('completed gathering cannot be repaid or retold as a new entitlement after receipt eviction',()=>{const s=fixture();prepare(s);assert.ok(run(s,'verse',{verse:'detour'}).ok);const id='first-share';assert.ok(s.adventureCommand(id,'gathering-share').ok);const saved=s.snapshot();assert.equal(s.adventureCommand(id,'gathering-share').duplicate,true);assert.deepEqual(s.snapshot(),saved);s.state.adventure.receipts=[];const before=s.snapshot();assert.equal(run(s,'share').ok,false);assert.equal(run(s,'accept').ok,false);assert.equal(run(s,'verse',{verse:'quarry'}).ok,false);assert.deepEqual(s.snapshot(),before);});
test('command identity cannot be reused with changed terms',()=>{const s=fixture();assert.ok(s.adventureCommand('same','gathering-accept').ok);const before=s.snapshot();assert.equal(s.adventureCommand('same','gathering-prepare',{id:'cloth'}).ok,false);assert.deepEqual(s.snapshot(),before);});
test('paused, fallen and revision-saturated characters cannot progress',()=>{for(const kind of ['paused','fallen','revision']){const s=fixture();if(kind==='paused')s.paused=true;if(kind==='fallen')s.state.adventure.hp=0;if(kind==='revision')s.state.adventure.revision=1e9;const before=s.snapshot();assert.equal(run(s,'accept').ok,false);assert.deepEqual(s.snapshot(),before);}});
test('invalid durable prerequisite combinations never load as progress',()=>{const a=fixture().state.adventure;for(const bad of [{...Q.fresh(),shared:true},{...Q.fresh(),verse:'mill'},{...Q.fresh(),accepted:true,prepared:['cloth','cloth']},{...Q.fresh(),accepted:true,prepared:['missing']},{...Q.fresh(),version:2},{...Q.fresh(),accepted:'yes'}])assert.throws(()=>Q.validate(bad,a));});
test('each partial state and finished state round-trips through the current validator',()=>{const s=fixture();assert.ok(run(s,'accept').ok);for(const p of Q.TASKS){s.state.player={...p,yaw:0};assert.ok(run(s,'prepare',{id:p.id}).ok);assert.deepEqual(A.validate(s.state.adventure).earthGathering,s.state.adventure.earthGathering);}s.state.player={...Q.TABLE,yaw:0};assert.ok(run(s,'verse',{verse:'quarry'}).ok);assert.ok(run(s,'share').ok);assert.deepEqual(A.validate(s.state.adventure),s.state.adventure);});
test('original music is deterministic, stereo, finite, different by arrangement and bounded',()=>{let previous=null;for(const id of Object.keys(Q.VERSES)){const d=M.render(id,8000),again=M.render(id,8000);assert.equal(d.duration,26);assert.equal(d.channels.length,2);assert.deepEqual(d.channels,again.channels);let peak=0,energy=0;for(const v of d.channels[0]){assert.ok(Number.isFinite(v));peak=Math.max(peak,Math.abs(v));energy+=v*v;}assert.ok(peak<1&&peak>.01);assert.ok(energy>1);assert.ok(Math.abs(d.channels[0].at(-1))<.0001);if(previous)assert.notDeepEqual(d.channels[0],previous);previous=d.channels[0];}assert.throws(()=>M.render('__proto__'));assert.throws(()=>M.render('mill',NaN));});
