'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const C=require('../src/core.js'),S=require('../src/sandbox.js'),X=require('../src/creative.js');
function env(){const els=new Map(),element=id=>{if(!els.has(id))els.set(id,{hidden:false,textContent:'',innerHTML:'',disabled:false,setAttribute(){}});return els.get(id);};const g={RealmCore:C,RealmSandbox:S,RealmCreative:X,document:{getElementById:element,querySelector:element}};vm.createContext(g);for(const f of ['experience.js','sandbox-ui.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../src',f),'utf8'),g);return{g,els,element};}
function experience(g,sim){let x=Object.create(g.RealmExperience.Experience.prototype);x.h={sim:()=>sim,panel:()=>null,audio:()=>({ctx:{currentTime:3}})};x.dialog={open:false};x.playing=false;x.selectedSlot='nw';return x;}
test('creative presentation tick preserves sandbox blueprint and grid',()=>{const{g}=env(),sim=new C.Simulation();sim.presentation={buildMode:true,blueprint:{kind:'floor',gx:1,gz:1,valid:true},resource:'timber-1'};const x=experience(g,sim),before=sim.presentation;x.tick();assert.equal(sim.presentation,before);assert.equal(sim.presentation.buildMode,true);assert.equal(sim.presentation.blueprint.kind,'floor');assert.equal(sim.presentation.resource,'timber-1');});
test('creative tick still clears its own stale playing and room-selection fields',()=>{const{g}=env(),sim=new C.Simulation();sim.presentation={buildMode:true,playing:true,step:4,selectedSlot:'nw'};const x=experience(g,sim);x.tick();assert.equal(sim.presentation.playing,false);assert.equal(sim.presentation.step,-1);assert.equal(sim.presentation.selectedSlot,null);});
test('selected slot and active music never replace another presentation owner',()=>{const{g}=env(),sim=new C.Simulation();sim.presentation={blueprint:{kind:'bench'},buildMode:true};const x=experience(g,sim);x.h.panel=()=> 'retreat';x.playing=true;x.started=1;x.loopSeconds=4;x.tick();assert.equal(sim.presentation.step,8);assert.equal(sim.presentation.selectedSlot,'nw');assert.equal(sim.presentation.blueprint.kind,'bench');});
test('placement confirmation stays disabled before a tile is selected',()=>{const{g,element}=env(),sim=new C.Simulation(),u=Object.create(g.RealmSandboxUI.SandboxUI.prototype);u.api={sim:()=>sim};u.build='floor';u.cell=null;u.refreshGhost();assert.equal(element('#build-place').disabled,true);assert.equal(sim.presentation.blueprint,null);});
