"""Earlier Firstlight09 workflows on the exact Firstlight10 document, real UI and keyboard, accepted path movement.
Earned checkpoints come from command-only journeys. Specific denial/restart
fixtures are labelled. Map-backed storage is NOT native-origin evidence.
Accelerated time is NOT a human playtest or performance measurement.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
from browser_support import chromium_launch_kwargs, read_utf8
import json, hashlib, traceback, math
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'evidence10/regression09';OUT.mkdir(parents=True,exist_ok=True)
HTML=read_utf8(ROOT/'FIRSTLIGHT_VALLEY.html')
report={'method':__doc__,'build_sha256':hashlib.sha256(HTML.encode()).hexdigest(),'checks':[],'errors':[]}
errors=[];requests=[]
def check(name,v):
 report['checks'].append({'name':name,'passed':bool(v)});print(('PASS ' if v else 'FAIL ')+name,flush=True)
 if not v:raise AssertionError(name)
try:
 with sync_playwright() as pw:
  b=pw.chromium.launch(**chromium_launch_kwargs())
  ctx=b.new_context(viewport={'width':1440,'height':960},offline=True,accept_downloads=True)
  def spawn(save=None,context=ctx,fallback=False,capture=True,denied=False):
   q=context.new_page();q.on('pageerror',lambda e:errors.append(str(e)));q.on('request',lambda r:requests.append(r.url));q.on('dialog',lambda d:d.accept())
   q.evaluate('''({save,fallback,capture,denied})=>{window.__ETERNITIES_TEST_MODE=true;window.__ETERNITIES_CAPTURE_MODE=capture;window.ST=new Map(save?[['eternities.realm08.save.v7',JSON.stringify(save)]]:[]);Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>{if(denied)throw Error('Known storage-denial fixture');return ST.get(k)||null},setItem:(k,v)=>{if(denied)throw Error('Known storage-denial fixture');ST.set(k,String(v))},removeItem:k=>ST.delete(k)}});if(fallback){const old=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...args){return t==='webgl2'?null:old.call(this,t,...args)}}}''',{'save':save,'fallback':fallback,'capture':capture,'denied':denied})
   q.set_content(HTML,wait_until='load');q.wait_for_function('window.Realm');q.wait_for_timeout(1700);q.evaluate('Realm.test.quality("low");Realm.test.render()');return q
  p=spawn()
  ev=lambda js,arg=None:p.evaluate(js,arg)
  state=lambda:ev('Realm.state')
  diag=lambda:ev('Realm.diagnostics')
  def render():ev('Realm.test.render()')
  def step(t):ev('(t)=>{Realm.test.step(t);Realm.test.render()}',t)
  def close():
   if p.locator('#rpg-window').evaluate('(e)=>e.open'):p.click('#rpg-close')
   if p.locator('#story-dialog').evaluate('(e)=>e.open'):p.click('#story-close')
   if p.locator('#studio-dialog').evaluate('(e)=>e.open'):p.click('#studio-close')
   if p.locator('#drawer').evaluate('(e)=>e.classList.contains("open")'):p.click('#close-panel')
  def key(k):p.keyboard.press(k);render()
  def click(sel):p.locator(sel).first.click();render()
  def action(act,id=None):click('[data-rpg="'+act+'"]'+('[data-id="'+id+'"]' if id is not None else ''))
  def tab(t):click('#rpg-tabs [data-id="'+t+'"]')
  def walk(x,z,seconds=35):
   close();r=ev('([x,z])=>Realm.test.move(x,z)',[x,z])
   if not r['ok']:raise AssertionError('Refused route '+str((x,z))+': '+str(r))
   step(seconds);v=diag()['adventure']['player'];check('Walk reaches '+str((x,z)),math.hypot(v['x']-x,v['z']-z)<.18)
  def snapshot(name):
   ev('Realm.test.quality("balanced");Realm.test.render()');p.wait_for_timeout(100);p.screenshot(path=str(OUT/name));ev('Realm.test.quality("low");Realm.test.render()')
  check('10 boots WebGL2 in original valley',diag()['version']=='10.0.0' and diag()['mode']=='webgl2' and diag()['metrics']['instances']>3000)
  check('Audio does not start itself',diag()['audio']['state']=='not-created')
  check('One tracker replaces overlapping old dock',p.locator('#quest-tracker').is_visible() and not p.locator('.dock').is_visible())
  check('Camera begins in third person following visitor',diag()['camera']['preset']=='adventure' and diag()['camera']['projection']=='perspective' and not diag()['camera']['overview'])
  key('c');check('C opens character screen',p.locator('#rpg-heading').inner_text()=='Your character')
  check('Character screen pauses simulation',diag()['adventure']['paused'])
  check('Three real equipment slots',p.locator('.equipment-slots > button').count()==3)
  check('Rendered character portrait present',p.locator('#avatar-mount canvas').count()==1)
  before=state();key('Tab');check('Tab stays in dialog focus, never selects foe',diag()['adventure']['tactics']['target'] is None and ev('document.activeElement.closest("#rpg-window")!==null'))
  key('1');check('Skills do not leak through menu',state()==before and not diag()['adventure']['tactics']['auto'])
  tab('craft');check('Five crafting categories',p.locator('.craft-categories button').count()==5)
  check('Missing-material recipe is disabled',p.locator('.recipe-detail .primary').is_disabled())
  action('go','workshop');step(30);check('Oren navigation walks',math.hypot(state()['player']['x']-11,state()['player']['z']-9)<.1)
  key('e');check('Oren gives actual starter equipment',state()['adventure']['started'] and state()['adventure']['equipment']['weapon']=='trail_blade')
  close();key('k');check('K opens crafting',p.locator('#rpg-heading').inner_text()=='The workbench');tab('equipment')
  check('Equipped blade visible in inventory grid',p.locator('#bag-items [data-id="gear:trail_blade"]').is_visible());snapshot('09-character-start.png');close()
  material=json.loads((ROOT/'examples/REALM09_ARMORY_MATERIALS_EARNED.json').read_text());ev('(s)=>Realm.test.replace(s)',material);render();key('k')
  old=state()['sandbox']['inventory'];action('craft','trail_bow');new=state()['sandbox']['inventory']
  check('Bow crafting spends exact real materials',new['wood']==old['wood']-6 and new['fiber']==old['fiber']-4 and new['stone']==old['stone']-2)
  check('Unique bow recipe disables repeat',p.locator('[data-rpg="craft"][data-id="trail_bow"]').is_disabled())
  tab('equipment');action('item','gear:trail_bow');check('Item comparison shows actual stat changes','→' in p.locator('.compare-stats').inner_text())
  action('equip','trail_bow');check('Equip changes actual weapon',diag()['adventure']['weapon']['style']=='bow')
  p.locator('#bag-search').fill('bow');check('Bag search filters by name',p.locator('#bag-items .inventory-item').count()==1)
  p.locator('#bag-search').fill('');action('filter','materials');check('Material filter excludes weapon',p.locator('#bag-items [data-id="gear:trail_bow"]').count()==0)
  tab('craft');action('range');check('Archery court loads its three targets',diag()['scene']=='range' and len(diag()['adventure']['enemies'])==3)
  check('Seven action slots replace old battle bars',p.locator('#skillbar .skill').count()==7 and not p.locator('#battle-hud').is_visible())
  key('Tab');check('Tab selects target frame',diag()['adventure']['tactics']['target'] is not None and p.locator('#target-frame').is_visible())
  first=diag()['adventure']['tactics']['target'];key('Tab');second=diag()['adventure']['tactics']['target'];key('Shift+Tab');check('Shift Tab reverses cycle',first!=second and diag()['adventure']['tactics']['target']==first)
  check('Selection alone never attacks',not diag()['adventure']['tactics']['auto'])
  key('1');check('1 toggles visible autoattack',diag()['adventure']['tactics']['auto'] and p.locator('#skill-auto').get_attribute('aria-pressed')=='true')
  before=diag()['adventure']['player'];step(.5);check('Out-of-range auto does not move',diag()['adventure']['player']==before and not ev('Realm.test.path.length'))
  walk(0,-3,6);click('#range-begin');step(1.5);check('Auto lands physical arrows in range',sum(diag()['adventure']['range']['hits'].values())>0)
  key('3');check('Brace has actual duration and visible cooldown',diag()['adventure']['tactics']['guardUntil']>state()['adventure']['elapsed'] and bool(p.locator('#skill-guard .skill-cooldown').inner_text()))
  key('c');check('Menu stops autoattack and pauses',not diag()['adventure']['tactics']['auto'] and diag()['adventure']['paused']);close();check('Closing resumes world',not diag()['adventure']['paused'])
  key('p');key('c');close();check('Closing preserves previous manual pause',diag()['adventure']['paused']);key('p')
  action('camera','tactical');check('Tactical camera is elevated',diag()['camera']['elevation']>1);yaw=diag()['camera']['yaw'];key(']');check('Fixed orbit key rotates',abs(diag()['camera']['yaw']-yaw-.7854)<.001)
  key('r');check('R restores third person behind visitor',diag()['camera']['preset']=='adventure' and abs(diag()['camera']['yaw']-diag()['adventure']['player']['yaw']-3.141592653589793)<.001)
  key('Escape');key('Escape');check('Escape no-target opens menu instead of exiting expedition',diag()['scene']=='range' and p.locator('#rpg-window').evaluate('(e)=>e.open'))
  close();walk(0,9);key('e');check('Actual range exit preserves bow',diag()['scene']=='valley' and diag()['adventure']['weapon']['style']=='bow')
  complete=json.loads((ROOT/'examples/REALM09_ARMORY_COMPLETE_EARNED.json').read_text());ev('(s)=>Realm.test.replace(s)',complete);render();key('c');action('filter','all');action('item','gear:copper_bow')
  old=state()['adventure'];oldstats=diag()['adventure']['stats'];p.select_option('#rpg-socket','moonstone');action('socket','copper_bow')
  check('Socket swaps real gems and capacity',state()['adventure']['arsenal']['sockets']['copper_bow']=='moonstone' and state()['adventure']['arsenal']['gems']['ruby']==1 and diag()['adventure']['stats']['maxHP']==oldstats['maxHP']+18)
  check('Socket capacity change does not heal',state()['adventure']['hp']==old['hp']);snapshot('09-character-equipment.png');tab('craft');action('craft-filter','gems');snapshot('09-crafting-gems.png')
  tab('companion');p.locator('#rpg-companion-name').fill('<Briar & Dawn>');action('rename');check('Companion name safely retains special characters',state()['adventure']['companion']['name']=='<Briar & Dawn>' and p.locator('#rpg-content script').count()==0)
  action('companion','stay');check('Stay updates actual companion mode',state()['adventure']['companion']['mode']=='stay');action('companion','follow')
  close();start=json.loads((ROOT/'examples/CHAPTER_II_COMPLETE_EARNED.json').read_text());ev('(s)=>Realm.test.replace(s)',start);render()
  walk(0,3);key('e');close();walk(44,6);key('e');check('Road gateway retains chapterII scene',diag()['scene']=='road')
  walk(-10,12);key('e');check('Tessa merchant available in new interface',p.locator('#rpg-heading').inner_text()=='Tessa’s road shop')
  old=state()['adventure'];action('trade','sell-copper');check('Tessa exchange charges real copper',state()['adventure']['ore']==old['ore']-2 and state()['adventure']['coins']==old['coins']+3)
  close();walk(2,3.4);walk(2,-4);walk(0,-24);key('e');check('Lit beacon opens local meeting',p.locator('#rpg-heading').inner_text()=='The Beacon Answers')
  action('beacon-command','beacon-answer');check('Answer starts descent, not automatic assault',diag()['adventure']['beacon']['phase']=='arrival' and not p.locator('#rpg-window').evaluate('(e)=>e.open'))
  step(3);check('Family has three active routes',len(diag()['adventure']['beacon']['actors'])==3 and any(x['path'] for x in diag()['adventure']['beacon']['actors']));snapshot('09-angel-arrival.png');step(15)
  check('Family arrives before ready phase',diag()['adventure']['beacon']['phase']=='ready' and all(not x['path'] for x in diag()['adventure']['beacon']['actors']))
  key('e');action('beacon-command','beacon-grace');check('Grace requires explicit acceptance',state()['adventure']['beacon']['soul']['radiance']==1)
  action('beacon-command','beacon-defend');check('Defense spawns first breach',diag()['adventure']['beacon']['wave']==1 and len([x for x in diag()['adventure']['enemies'] if x['eventEnemy']])==2)
  key('Tab');key('1');check('Tab plus1 engages event foes',diag()['adventure']['tactics']['auto'])
  oldXP=state()['adventure']['xp'];phase_seen=set();used=set()
  for i in range(750):
   d=diag()['adventure'];a=state()['adventure'];r=d['beacon'];p0=d['player'];t=d['tactics'];near=[e for e in d['enemies'] if e['hp']>0 and e['eventEnemy']]
   if r['phase'] in ['won','failed']:break
   if r['wave'] not in phase_seen:
    phase_seen.add(r['wave']);check('Wave '+str(r['wave'])+' composition',len(near)>=2)
   if any(e['hidden'] for e in near) and p.locator('#skill-insight').is_enabled():key('4');used.add('insight')
   target=next((e for e in near if e['id']==t['target'] and not e['hidden']),None)
   if not target and any(not e['hidden'] for e in near):key('Tab');target=next((e for e in near if e['id']==diag()['adventure']['tactics']['target']),None)
   if target:
    if not diag()['adventure']['tactics']['auto']:key('1')
    distance=math.hypot(target['x']-p0['x'],target['z']-p0['z'])
    if distance>2.3 and not ev('Realm.test.path.length'):
     opts=[{'x':target['x']+math.sin(j*math.pi/8)*1.8,'z':target['z']+math.cos(j*math.pi/8)*1.8} for j in range(16)];opts.sort(key=lambda q:math.hypot(q['x']-p0['x'],q['z']-p0['z']));ev('qs=>qs.some(q=>Realm.test.move(q.x,q.z).ok)',opts)
    if distance<3.2 and a['stamina']>=55 and p.locator('#skill-special').is_enabled():key('2');used.add('special')
    if target['kind']=='siegeboss' and p.locator('#skill-guard').is_enabled() and a['stamina']>=40:key('3');used.add('guard')
    if target['kind']=='siegeboss' and 'shot' not in used:ev('Realm.test.view({half:16,elevation:1});Realm.test.render()');snapshot('09-beacon-defense.png');used.add('shot')
   if a['hp']<d['stats']['maxHP']-45 and p.locator('#skill-heal').is_enabled():key('6');used.add('heal')
   if a['beacon']['soul']['equipped']=='aegis' and r['wave']>=2 and p.locator('#skill-spirit').is_enabled() and a['stamina']>=50:key('5');used.add('aegis')
   step(.35)
  check('Three waves complete through UI attacks',diag()['adventure']['beacon']['phase']=='won' and phase_seen=={1,2,3})
  check('New skill branches used',{'special','guard','aegis'}.issubset(used))
  check('No incompatible old loot or XP entries',state()['adventure']['xp']==oldXP and all('breach' not in x for x in state()['adventure']['defeated']))
  check('Defense preserves creative content',all(state()[k]==start[k] for k in ['retreat','score','visitor','notes','flowers']))
  walk(0,-24,5);key('e');old=state()['adventure'];action('beacon-command','beacon-reward')
  check('One-time defense reward real',state()['adventure']['coins']==old['coins']+15 and state()['adventure']['arsenal']['gems']['moonstone']==old['arsenal']['gems']['moonstone']+1)
  check('Reward disables duplicate claim',p.locator('[data-id="beacon-reward"]').is_disabled())
  action('relic','accept');check('Accepting cinder alone never corrupts',state()['adventure']['beacon']['soul']['corruption']==0)
  action('chart','forest');check('Future route records intent, no teleport',state()['adventure']['beacon']['route']=='forest' and diag()['scene']=='road');snapshot('09-beacon-network.png')
  # Aegis and cinder share the spirit cooldown. Faster fights can finish while
  # the final aegis is still recovering; wait for real readiness before replay.
  remaining=max(0,diag()['adventure']['tactics']['cooldowns']['spirit']-state()['adventure']['elapsed']);step(remaining+.05)
  action('beacon-command','beacon-replay');step(1);key('Tab');hp=state()['adventure']['hp'];key('5')
  check('Cinder skill spends health and records choice',state()['adventure']['hp']==hp-12 and state()['adventure']['beacon']['soul']['corruption']==1)
  walk(0,17);key('e');step(.2);check('Replay withdrawal preserves stable story beacon',state()['adventure']['beacon']['status']=='stable' and state()['adventure']['beacon']['complete'])
  walk(44,6);key('e');walk(2,3.4);walk(2,-4);walk(0,-24);key('e');tab('soul');action('power','soul-purify')
  check('Renunciation clears corruption, not history',state()['adventure']['beacon']['soul']['corruption']==0 and state()['adventure']['beacon']['soul']['scars']==['cinder-invoked','cinder-renounced'])
  check('Separate radiance persists through redemption',state()['adventure']['beacon']['soul']['radiance']==2);snapshot('09-soul-history.png');close();action('open','more')
  with p.expect_download() as down:action('export')
  data=Path(down.value.path()).read_bytes();saved=json.loads(data);(OUT/'BROWSER_EARNED_CHAPTER_III.json').write_bytes(data)
  check('Actual save export contains new completed chapter',saved['version']==9 and saved['adventure']['beacon']['complete'])
  close();p.set_input_files('#import-file',{'name':'roundtrip.json','mimeType':'application/json','buffer':data});p.wait_for_timeout(200);render()
  check('UI import restores durable content',state()['adventure']['beacon']==saved['adventure']['beacon'] and state()['score']==saved['score'])
  cold=spawn(saved);check('Restart keeps story, never runs attack intent',cold.evaluate('Realm.state.adventure.beacon')==saved['adventure']['beacon'] and cold.evaluate('Realm.diagnostics.adventure.beacon.phase')=='idle' and not cold.evaluate('Realm.diagnostics.adventure.tactics.auto'));cold.close()
  action('open','more');action('music');check('Music remains accessible',p.locator('#studio-dialog').evaluate('(e)=>e.open'))
  rev=state()['scoreRevision'];p.locator('[data-music="cell"]').first.click();check('Actual score grid still edits',state()['scoreRevision']==rev+1)
  for fmt in ['midi','wav']:
   with p.expect_download() as dl:p.locator('[data-music="'+fmt+'"]').click()
   contents=Path(dl.value.path()).read_bytes();(OUT/dl.value.suggested_filename).write_bytes(contents);check('Real '+fmt+' export header',contents[:4]==(b'MThd' if fmt=='midi' else b'RIFF'))
  check('Export never enables ambience',not diag()['audio']['enabled']);close()
  action('open','more');action('panel','chronicle');p.locator('#note-text').fill('Chapter III: <not markup> & a road reopened.');click('[data-action="note"]')
  check('Notebook text still safe',state()['notes'][-1]['text']=='Chapter III: <not markup> & a road reopened.')
  close();action('open','more');action('panel','build');check('Construction controls remain reachable',p.locator('#drawer').is_visible() and bool(p.locator('#panel-title').inner_text()))
  close();action('open','more');action('panel','retreat');check('Room furnishing controls retained',p.locator('[data-action="furnish"]').count()>=8)
  close();action('open','more');action('panel','visitor');check('Appearance UI retained',p.locator('#visitor-name').is_visible())
  close();action('open','more');action('panel','settings');check('Graphics settings retained',p.locator('#quality').is_visible() and p.locator('#quality option').count()==3);close()
  live=spawn(saved,capture=False);live.bring_to_front();live.wait_for_function('!document.hidden',timeout=10000)
  running=live.evaluate('Realm.state.adventure.elapsed');live.wait_for_function('(t)=>Realm.state.adventure.elapsed>t',arg=running,timeout=10000)
  live.keyboard.press('c');live.wait_for_function('document.querySelector("#rpg-window").open && Realm.diagnostics.adventure.paused',timeout=10000);t0=live.evaluate('Realm.state.adventure.elapsed');live.wait_for_timeout(500)
  check('Normal RAF really pauses while character is open',live.evaluate('Realm.state.adventure.elapsed')==t0);live.keyboard.press('Escape');live.wait_for_function('!document.querySelector("#rpg-window").open',timeout=10000);live.wait_for_function('(t)=>Realm.state.adventure.elapsed>t',arg=t0,timeout=10000);check('Normal RAF resumes on close',live.evaluate('Realm.state.adventure.elapsed')>t0);live.close()
  blocked=spawn(denied=True);blocked.evaluate('Realm.test.save()');check('Storage refusal truthfully says memory-only','MEMORY ONLY' in blocked.locator('#save-status').inner_text());blocked.close()
  flat=spawn(saved,fallback=True);check('Map fallback keeps same completed story',flat.evaluate('Realm.diagnostics.mode')=='map' and flat.evaluate('Realm.state.adventure.beacon.complete'))
  flat.keyboard.press('c');check('Missing portrait does not block equipment',flat.locator('#rpg-window').evaluate('(e)=>e.open') and flat.locator('.equipment-slots > button').count()==3);flat.close()
  mobile=b.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True,offline=True);m=spawn(saved,context=mobile)
  m.locator('.rpg-nav [data-id="equipment"]').tap();m.wait_for_timeout(100);m.evaluate('Realm.test.render()');check('Touch character canvas fits its portrait mount',m.locator('#avatar-mount canvas').bounding_box()['width']<=m.locator('#avatar-mount').bounding_box()['width']+1);m.screenshot(path=str(OUT/'09-mobile-character.png'))
  check('Touch character panel fits viewport',m.evaluate('document.documentElement.scrollWidth<=innerWidth+1') and m.locator('#rpg-close').is_visible())
  m.locator('#rpg-tabs [data-id="craft"]').tap();check('Touch crafting tabs available',m.locator('.craft-categories button').count()==5)
  m.locator('#rpg-close').tap();m.screenshot(path=str(OUT/'09-mobile-hud.png'));box=m.locator('#skillbar').bounding_box();check('Touch skillbar stays on screen',box['x']>=0 and box['x']+box['width']<=391)
  mobile.close();check('No unhandled JavaScript errors',not errors);check('No external requests',not requests);ctx.close();b.close()
except Exception:
 report['errors'].append(traceback.format_exc());print(report['errors'][-1],flush=True)
finally:
 report['browser_errors']=errors;report['requests']=requests;report['checks_passed']=sum(x['passed'] for x in report['checks']);report['passed']=not report['errors'] and not errors and all(x['passed'] for x in report['checks']);(OUT/'RPG_BROWSER_REPORT.json').write_text(json.dumps(report,indent=2));print('RESULT',report['checks_passed'],report['passed'],flush=True)
 if not report['passed']:raise SystemExit(1)
