/* Standalone route module checks. Run with Node, without game/renderer dependencies.
 * The full game and browser acceptance journeys remain separate evidence. */
'use strict';
const test=require('node:test'),a=require('node:assert/strict'),R=require('../src/road.js');
test('road defaults are distinct records and start without progress',()=>{const x=R.fresh(),y=R.fresh();x.revealed.push('cart-latch');a.deepEqual(y,R.fresh());a.equal(y.entered,false);a.equal(y.reported,false);});
test('all route destinations are on terrain; river and trunks are obstacles',()=>{for(const p of[R.ENTRY,R.MERCHANT,R.BEACON,...R.ENEMIES,...R.CACHES])a.ok(R.walkable(p.x,p.z));a.ok(R.walkable(2,0));a.equal(R.walkable(-8,0),false);for(const t of R.TREES)a.equal(R.walkable(t[0],t[1]),false);});
test('visibility rejects invalid endpoints, extreme inputs, and water crossing',()=>{for(const q of[null,{}, {x:NaN,z:0},{x:Infinity,z:1},{x:Number.MAX_VALUE,z:0}]){a.equal(R.line(q,R.ENTRY),false);a.equal(R.line(R.ENTRY,q),false);}a.equal(R.line({x:-8,z:4},{x:-8,z:-4}),false);a.ok(R.line({x:2,z:3},{x:2,z:-3}));});
test('consistent completed road validates and all objectives complete',()=>{const s=R.fresh();Object.assign(s,{entered:true,revealed:['cart-latch'],claimed:['cart-latch'],cartRepaired:true,beaconLit:true,reported:true});const adv={reward:'warden_stone',companion:{bonded:true},defeated:R.ENEMIES.map(e=>e.id),road:s};a.deepEqual(R.validate(s,adv),s);a.ok(R.objectives(adv).every(o=>o.done));});
test('unearned and duplicate facts are rejected rather than reset',()=>{for(const change of[s=>s.reported=true,s=>s.claimed=['cart-latch'],s=>s.revealed=['cart-latch','cart-latch'],s=>s.cartRepaired=true,s=>s.version=99]){const s=R.fresh();change(s);a.throws(()=>R.validate(s),/Invalid road/);}});
test('road validation requires story, companion, and encounter prerequisites',()=>{const s={...R.fresh(),entered:true,revealed:['cart-latch'],claimed:['cart-latch'],cartRepaired:true,beaconLit:true};const good={reward:'dawn_blade',companion:{bonded:true},defeated:R.ENEMIES.map(e=>e.id)};for(const adv of[{...good,reward:null},{...good,companion:{bonded:false}},{...good,defeated:[]}])a.throws(()=>R.validate(s,adv),/Invalid road/);});
