/* Known-answer fixtures test refusals. road_journey.cjs independently earns
 * both chapters without position, item, defeat or story grants. */
'use strict';const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs');
const C=require('../src/core.js'),A=require('../src/adventure.js'),R=require('../src/road.js');let seq=0;
const cmd=(s,t,p={})=>s.adventureCommand('unit-road-'+(++seq),t,p),snap=s=>JSON.stringify(s.snapshot());
function step(s,t){for(let i=0;i<t*20;i++)s.tick(.05);}
function ready(){const s=new C.Simulation(JSON.parse(fs.readFileSync(require.resolve('../examples/CHAPTER_COMPLETED_EARNED.json'))));s.state.player={x:44,z:6,yaw:0};return s;}
function road(){const s=ready();a.ok(cmd(s,'road-enter').ok);return s;}
function revealed(){const s=road();s.state.adventure.road.revealed=['cart-latch'];s.state.adventure.road.claimed=['cart-latch'];s.state.adventure.defeated.push('road-prowler');s.state.player={...R.MERCHANT,yaw:0};s.state.adventure.ore=5;return s;}
function shop(){const s=revealed();a.ok(cmd(s,'cart-repair').ok);return s;}
function reject(s,t,p={}){const before=snap(s);a.equal(cmd(s,t,p).ok,false);a.equal(snap(s),before);}
test('world05 migrates without changing any prior creative/sandbox fields',()=>{const v=JSON.parse(fs.readFileSync(require.resolve('../examples/CHAPTER_COMPLETED_EARNED.json'))),old=JSON.stringify(v),n=C.validate(v);a.equal(n.version,C.VERSION);a.equal(n.adventure.version,A.VERSION);a.deepEqual(n.adventure.road,R.fresh());for(const k of['score','sandbox','retreat','notes','visitor','flowers'])a.deepEqual(n[k],v[k]);a.equal(JSON.stringify(v),old);});
test('all supported previous schemas migrate without road wins',()=>{for(const version of[2,3,4,5]){let s=C.fresh();s.version=version;if(version<=4)delete s.adventure;else{s.adventure.version=1;delete s.adventure.road;}if(version===2){delete s.score;delete s.retreat;delete s.visitor;delete s.scoreRevision;}const n=C.validate(s);a.equal(n.version,C.VERSION);a.deepEqual(n.adventure.road,R.fresh());}});
test('adapter migration writes new key and leaves previous key unchanged',()=>{const v=C.fresh();v.version=5;v.adventure.version=1;delete v.adventure.road;const data=JSON.stringify(v),m=new Map([['eternities.realm06.save.v5',data]]),store={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)},load=C.load(store);a.equal(load.status,'migrated');new C.Simulation(load.state).save(store);a.equal(m.get('eternities.realm06.save.v5'),data);a.equal(JSON.parse(m.get(C.KEY)).version,C.VERSION);});
test('gate refuses unfinished chapter without mutation',()=>{const s=new C.Simulation();s.state.player={x:44,z:6,yaw:0};reject(s,'road-enter');});
test('gate refuses remote and wrong-scene entry',()=>{const s=ready();s.state.player={x:0,z:3,yaw:0};reject(s,'road-enter');reject(road(),'road-enter');});
test('earned gift allows entry and preserves exterior restart',()=>{const s=ready(),p={...s.state.player};a.ok(cmd(s,'road-enter').ok);a.equal(s.room,'road');a.deepEqual(s.state.player,R.ENTRY);a.deepEqual(s.snapshot().player,p);a.ok(s.state.adventure.road.entered);});
test('normal road return is restricted to southern gate',()=>{const s=road();s.state.player={x:2,z:4,yaw:0};reject(s,'road-leave');s.state.player={...R.ENTRY};a.ok(cmd(s,'road-leave').ok);a.equal(s.room,null);a.equal(s.state.player.x,44);});
test('road save reopens safely outside with progress retained',()=>{const s=road();s.state.player={x:2,z:-4,yaw:0};const loaded=new C.Simulation(s.snapshot());a.equal(loaded.room,null);a.equal(loaded.state.player.x,44);a.ok(loaded.state.adventure.road.entered);});
test('all map landmarks and encounter origins walkable',()=>{for(const p of[R.ENTRY,R.MERCHANT,R.BEACON,...R.ENEMIES,...R.CACHES])a.ok(R.walkable(p.x,p.z),JSON.stringify(p));});
test('river blocks nonbridge crossings and rejects nonfinite coordinates',()=>{a.equal(R.walkable(-8,0),false);a.ok(R.walkable(2,0));for(const q of[[NaN,0],[Infinity,0],[20,20]])a.equal(R.walkable(...q),false);});
test('boulders cart tower and trunks all participate in collision',()=>{for(const o of R.OBSTACLES)a.equal(R.walkable(o.x,o.z),false);for(const t of R.TREES)a.equal(R.walkable(t[0],t[1]),false);});
test('path crosses bridge instead of cutting across water',()=>{const s=road(),start={x:-8,z:4},route=C.pathfind(start,{x:-8,z:-5},s.navRoom);a.ok(route);let prev=start;for(const q of route){a.ok(C.segment(prev,q,s.navRoom));prev=q;}a.ok(route.some(q=>q.x>=0));});
test('dodge does not tunnel through the river',()=>{const s=road();s.state.player={x:-8,z:3,yaw:Math.PI};a.ok(cmd(s,'dodge',{dx:0,dz:-1}).ok);a.ok(R.walkable(s.state.player.x,s.state.player.z));a.ok(s.state.player.z>1.2);});
test('new encounters do not enable village combat',()=>{reject(ready(),'attack',{target:'road-prowler'});});
test('melee cannot hit through solid road geometry',()=>{const s=road(),e=A.runtime(s).enemies[0];s.state.player={x:9,z:10,yaw:0};e.x=11;e.z=10;reject(s,'attack',{target:e.id});});
test('Seek needs bonded Follow fox and a nearby discoverable scent',()=>{const s=road();s.state.adventure.companion.bonded=false;reject(s,'seek');s.state.adventure.companion.bonded=true;reject(s,'seek');s.state.player={x:-9,z:5,yaw:0};cmd(s,'companion-mode',{mode:'stay'});reject(s,'seek');});
test('discovery only occurs after physical path travel',()=>{const s=road();s.state.player={x:-9,z:5,yaw:0};const c=A.runtime(s).companion;c.x=-7;c.z=6;a.ok(cmd(s,'seek').ok);a.deepEqual(s.state.adventure.road.revealed,[]);step(s,5);a.ok(s.state.adventure.road.revealed.includes('cart-latch'));});
test('Stay cancels pending scent without issuing discovery',()=>{const s=road();s.state.player={x:-9,z:5,yaw:0};a.ok(cmd(s,'seek').ok);a.ok(cmd(s,'companion-mode',{mode:'stay'}).ok);step(s,5);a.deepEqual(s.state.adventure.road.revealed,[]);a.equal(A.runtime(s).companion.seek,null);});
test('leaving cancels scent instead of revealing cache remotely',()=>{const s=road();s.state.player={x:-9,z:5,yaw:0};cmd(s,'seek');s.state.player={...R.ENTRY};cmd(s,'road-leave');step(s,5);a.deepEqual(s.state.adventure.road.revealed,[]);a.equal(A.runtime(s).companion.seek,null);});
test('unrevealed distant or already claimed cache refuses without mutation',()=>{const s=road();reject(s,'road-cache',{id:'cart-latch'});s.state.adventure.road.revealed=['cart-latch'];reject(s,'road-cache',{id:'cart-latch'});s.state.player={...R.CACHES[0],yaw:0};a.ok(cmd(s,'road-cache',{id:'cart-latch'}).ok);reject(s,'road-cache',{id:'cart-latch'});});
test('cache overflow keeps balances and unclaimed discovery',()=>{const s=road();s.state.adventure.road.revealed=['cart-latch'];s.state.player={...R.CACHES[0],yaw:0};s.state.adventure.coins=9999;reject(s,'road-cache',{id:'cart-latch'});});
test('cache retry does not duplicate rewards',()=>{const s=road();s.state.adventure.road.revealed=['cart-latch'];s.state.player={...R.CACHES[0],yaw:0};a.ok(s.adventureCommand('cache-once','road-cache',{id:'cart-latch'}).ok);const old=snap(s);a.ok(s.adventureCommand('cache-once','road-cache',{id:'cart-latch'}).duplicate);a.equal(snap(s),old);});
test('repair needs latch prowler ore and proximity',()=>{const s=road();s.state.player={...R.MERCHANT,yaw:0};reject(s,'cart-repair');const t=revealed();t.state.adventure.ore=1;reject(t,'cart-repair');t.state.adventure.ore=3;t.state.player={x:0,z:17,yaw:0};reject(t,'cart-repair');});
test('repair charges exactly once under any command id',()=>{const s=revealed();a.ok(cmd(s,'cart-repair').ok);a.equal(s.state.adventure.ore,3);a.ok(s.state.adventure.road.cartRepaired);reject(s,'cart-repair');});
test('shop refuses unopened remote and wrong-scene trades',()=>{reject(revealed(),'trade',{offer:'tonic'});const s=shop();s.state.player={x:2,z:3,yaw:0};reject(s,'trade',{offer:'mantle'});s.leave();reject(s,'trade',{offer:'mantle'});});
test('tonic purchase obeys cost capacity and idempotency',()=>{const s=shop(),v=s.state.adventure;v.tonics=1;v.coins=10;a.ok(s.adventureCommand('trade-once','trade',{offer:'tonic'}).ok);a.equal(v.coins,8);a.equal(v.tonics,2);a.ok(s.adventureCommand('trade-once','trade',{offer:'tonic'}).duplicate);a.equal(v.tonics,2);cmd(s,'trade',{offer:'tonic'});reject(s,'trade',{offer:'tonic'});});
test('changed trade offer under same id is refused',()=>{const s=shop();s.state.adventure.coins=30;s.state.adventure.tonics=1;s.adventureCommand('t','trade',{offer:'tonic'});const old=snap(s);a.equal(s.adventureCommand('t','trade',{offer:'mantle'}).ok,false);a.equal(snap(s),old);});
test('unique mantle costs 18 and can be equipped not repurchased',()=>{const s=shop(),v=s.state.adventure;v.coins=25;a.ok(cmd(s,'trade',{offer:'mantle'}).ok);a.equal(v.coins,7);a.ok(v.owned.includes('courier_mantle'));reject(s,'trade',{offer:'mantle'});a.ok(cmd(s,'equip',{id:'courier_mantle'}).ok);a.equal(v.equipment.armor,'courier_mantle');});
test('insufficient currency preserves equipment and balance',()=>{const s=shop();s.state.adventure.coins=17;reject(s,'trade',{offer:'mantle'});s.state.adventure.coins=1;s.state.adventure.tonics=0;reject(s,'trade',{offer:'tonic'});});
test('copper sale exact and bounded',()=>{const s=shop(),v=s.state.adventure;v.ore=4;v.coins=2;a.ok(cmd(s,'trade',{offer:'sell-copper'}).ok);a.equal(v.ore,2);a.equal(v.coins,5);v.coins=9997;reject(s,'trade',{offer:'sell-copper'});});
test('sunberry sale consumes actual sandbox garden produce',()=>{const s=shop();s.state.sandbox.inventory.berry=3;const v=s.state.adventure.coins;a.ok(cmd(s,'trade',{offer:'sell-berries'}).ok);a.equal(s.state.sandbox.inventory.berry,1);a.equal(s.state.adventure.coins,v+1);reject(s,'trade',{offer:'sell-berries'});});
test('unknown trade never falls through to an offer',()=>{const s=shop();reject(s,'trade',{offer:'__proto__'});reject(s,'trade',{offer:'gold',quantity:-1});});
test('pause freezes scent movement and time and refuses actions',()=>{const s=road();s.state.player={x:-9,z:5,yaw:0};cmd(s,'seek');s.paused=true;const old=snap(s),c=JSON.stringify(A.runtime(s).companion);step(s,10);a.equal(snap(s),old);a.equal(JSON.stringify(A.runtime(s).companion),c);reject(s,'seek');});
test('charge direction locks during windup rather than tracking evasion',()=>{const s=road(),e=A.runtime(s).enemies.find(e=>e.kind==='charger');s.state.player={x:0,z:-13,yaw:0};step(s,.05);a.equal(e.mode,'windup');const d={...e.chargeDir};s.state.player={x:4,z:-13,yaw:0};step(s,1.3);a.deepEqual(e.chargeDir,d);a.equal(e.mode,'charge');a.ok(Math.abs(e.x)<.01);});
test('charge sweep respects banks and hits at most once per charge',()=>{const s=road(),r=A.runtime(s),e=r.enemies.find(e=>e.kind==='charger');Object.assign(e,{x:-8,z:-4,mode:'charge',chargeDir:{x:0,z:1},chargeLeft:9,chargeHit:false});s.state.player={x:-8,z:-3,yaw:0};r.invincible=0;const old=s.state.adventure.hp;step(s,.6);a.ok(R.walkable(e.x,e.z,.35));a.equal(e.mode,'recover');a.equal(s.state.adventure.hp,old-(e.damage-A.stats(s.state.adventure).defense));});
test('leaving charge lane avoids damage',()=>{const s=road(),r=A.runtime(s),e=r.enemies.find(e=>e.kind==='charger');Object.assign(e,{mode:'charge',chargeDir:{x:0,z:1},chargeLeft:7,chargeHit:false});s.state.player={x:4,z:-15,yaw:0};r.invincible=0;const hp=s.state.adventure.hp;step(s,.5);a.equal(s.state.adventure.hp,hp);});
test('path follower routes around rock and never enters it',()=>{const s=road(),actor={x:-8,z:-10,yaw:0,path:[],nextPath:0};for(let i=0;i<200;i++){A.followPath(s,actor,{x:-2,z:-10},.05,3);a.ok(R.walkable(actor.x,actor.z));s.state.adventure.elapsed+=.05;}a.ok(Math.hypot(actor.x+2,actor.z+10)<.3);});
test('fox on invalid ground explicitly recalled rather than stranded',()=>{const s=road(),c=A.runtime(s).companion;c.x=-5;c.z=-10;step(s,.05);a.ok(R.walkable(c.x,c.z));a.ok(A.runtime(s).notices.some(x=>x.includes('recalled')));});
test('beacon requires three encounters and only rewards once',()=>{const s=road();s.state.player={...R.BEACON,yaw:0};reject(s,'beacon-light');s.state.adventure.defeated.push(...R.ENEMIES.map(e=>e.id));a.ok(cmd(s,'beacon-light').ok);reject(s,'beacon-light');});
test('return reward requires cart beacon and actual spring',()=>{const s=shop();s.state.adventure.defeated.push('road-prism','road-ram');s.state.adventure.road.beaconLit=true;reject(s,'road-report');s.leave();s.state.player={x:0,z:3,yaw:0};a.ok(cmd(s,'road-report').ok);a.ok(s.state.adventure.owned.includes('wayfarer_band'));reject(s,'road-report');});
test('new equipment and chapter facts survive round trip',()=>{const s=shop();s.state.adventure.owned.push('courier_mantle');cmd(s,'equip',{id:'courier_mantle'});const v=s.snapshot();a.deepEqual(new C.Simulation(v).snapshot(),v);});
test('inconsistent completion duplicate IDs and hidden cache claims reject',()=>{const s=ready().snapshot();for(const f of[r=>r.reported=true,r=>r.claimed=['cart-latch'],r=>r.revealed=['cart-latch','cart-latch'],r=>r.beaconLit=true,r=>r.cartRepaired=true]){const v=JSON.parse(JSON.stringify(s));f(v.adventure.road);a.throws(()=>C.validate(v),/Invalid road/);}});
test('invalid nested road data refuses rather than silently resetting',()=>{for(const road of[null,{},[],{version:2},Object.assign(R.fresh(),{entered:'yes'})]){const v=C.fresh();v.adventure.road=road;a.throws(()=>C.validate(v));}});
test('road defeat permits explicit recovery without erasing quest or inventory',()=>{const s=shop();s.state.adventure.hp=0;const v=s.state.adventure;a.ok(cmd(s,'revive').ok);a.equal(s.room,null);a.ok(v.road.cartRepaired);a.ok(v.hp>0);});
