'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../src/core.js'),S=require('../src/sandbox.js');
const fresh=()=>new C.Simulation();let seq=0;
function act(sim,type,payload={}){return sim.sandboxCommand('test-'+(++seq),type,payload);}
function step(sim,sec){for(let i=0;i<sec*20;i++)sim.tick(.05);}
function node(sim,id){let n=S.NODES.find(n=>n.id===id);sim.state.player={x:n.x+1,z:n.z,yaw:0};return n;}
function stock(sim){for(let id of Object.keys(S.ITEMS))sim.state.sandbox.inventory[id]=['axe','pick'].includes(id)?0:30;}
function unlock(sim){stock(sim);sim.state.player={x:0,z:-21.3,yaw:0};a.equal(act(sim,'bridge').ok,true);sim.state.player={x:0,z:-33,yaw:0};}
function at(sim,gx,gz,dx=.7,dz=1.8){let p=S.worldCell(gx,gz);sim.state.player={x:p.x+dx,z:p.z+dz,yaw:0};}
function place(sim,kind,gx,gz){return act(sim,'place',{kind,gx,gz,rotation:0});}

test('sandbox starts empty except four seeds and round trips',()=>{let s=fresh();a.equal(s.state.sandbox.inventory.seeds,4);a.equal(s.state.sandbox.inventory.wood,0);a.deepEqual(S.validate(S.fresh()),S.fresh());a.equal(s.state.version,C.VERSION);});
test('all village resource nodes have a walkable approach',()=>{for(let n of S.NODES.filter(n=>!n.wild)){a.ok(C.walkable(n.x+1,n.z)||C.walkable(n.x-1,n.z),n.id);}});
test('rejected gather leaves inventory and resource unchanged',()=>{let s=fresh(),before=JSON.stringify(s.state.sandbox.nodes);a.equal(act(s,'gather',{node:'timber-1'}).ok,false);a.equal(s.state.sandbox.inventory.wood,0);a.equal(JSON.stringify(s.state.sandbox.nodes),before);});
test('wood takes four hand swings and yields five timber once',()=>{let s=fresh();node(s,'timber-1');for(let i=0;i<4;i++){a.equal(act(s,'gather',{node:'timber-1'}).ok,true);step(s,.5);}a.equal(s.state.sandbox.inventory.wood,5);a.equal(act(s,'gather',{node:'timber-1'}).ok,false);});
test('cooldown rejects fast repeated swings without damage',()=>{let s=fresh();node(s,'stone-1');act(s,'gather',{node:'stone-1'});a.equal(act(s,'gather',{node:'stone-1'}).ok,false);a.equal(s.state.sandbox.nodes.find(n=>n.id==='stone-1').hp,3);});
test('axe reduces timber harvest to two swings',()=>{let s=fresh();s.state.sandbox.inventory.axe=1;node(s,'timber-1');act(s,'gather',{node:'timber-1'});step(s,.5);act(s,'gather',{node:'timber-1'});a.equal(s.state.sandbox.inventory.wood,5);});
test('fibre supplies actual resource and one seed',()=>{let s=fresh();node(s,'fibre-1');a.equal(act(s,'gather',{node:'fibre-1'}).ok,true);a.equal(s.state.sandbox.inventory.fiber,3);a.equal(s.state.sandbox.inventory.seeds,5);});
test('resource reappears after active time, not clock slider',()=>{let s=fresh();node(s,'fibre-1');act(s,'gather',{node:'fibre-1'});s.setTime(23.9);a.equal(s.state.sandbox.nodes.find(n=>n.id==='fibre-1').hp,0);step(s,91);a.equal(s.state.sandbox.nodes.find(n=>n.id==='fibre-1').hp,1);});
test('pause stops regrowth',()=>{let s=fresh();node(s,'fibre-1');act(s,'gather',{node:'fibre-1'});s.paused=true;let before=s.state.sandbox.elapsed;step(s,100);a.equal(s.state.sandbox.elapsed,before);a.equal(s.state.sandbox.nodes.find(n=>n.id==='fibre-1').hp,0);});
test('craft atomically consumes exact recipe and produces count',()=>{let s=fresh();s.state.sandbox.inventory.wood=2;a.equal(act(s,'craft',{recipe:'plank'}).ok,true);a.equal(s.state.sandbox.inventory.wood,0);a.equal(s.state.sandbox.inventory.plank,4);});
test('insufficient recipe never partially consumes',()=>{let s=fresh();s.state.sandbox.inventory.wood=1;a.equal(act(s,'craft',{recipe:'plank'}).ok,false);a.equal(s.state.sandbox.inventory.wood,1);a.equal(s.state.sandbox.inventory.plank,0);});
test('advanced tool requires proximity to workbench',()=>{let s=fresh();stock(s);a.equal(act(s,'craft',{recipe:'pick'}).ok,false);s.state.player={x:11,z:9,yaw:0};a.equal(act(s,'craft',{recipe:'pick'}).ok,true);a.equal(s.state.sandbox.inventory.pick,1);a.equal(act(s,'craft',{recipe:'pick'}).ok,false);});
test('inventory capacity refuses complete recipe before debit',()=>{let s=fresh();s.state.sandbox.inventory.plank=998;s.state.sandbox.inventory.wood=10;a.equal(act(s,'craft',{recipe:'plank'}).ok,false);a.equal(s.state.sandbox.inventory.wood,10);});
test('old accepted command cannot be replayed after save reload',()=>{let s=fresh();s.state.sandbox.inventory.wood=10;let first=s.sandboxCommand('fixed','craft',{recipe:'plank'});a.equal(first.ok,true);let next=new C.Simulation(s.snapshot());a.equal(next.sandboxCommand('fixed','craft',{recipe:'plank'}).duplicate,true);a.equal(next.state.sandbox.inventory.plank,4);a.equal(next.sandboxCommand('fixed','craft',{recipe:'block'}).ok,false);});
test('old refusal is stable inside bounded deduplication window',()=>{let s=fresh();a.equal(s.sandboxCommand('x','craft',{recipe:'plank'}).ok,false);s.state.sandbox.inventory.wood=10;a.equal(s.sandboxCommand('x','craft',{recipe:'plank'}).ok,false);a.equal(s.state.sandbox.inventory.wood,10);});
test('deduplication ledger is bounded and validated',()=>{let s=fresh();for(let i=0;i<300;i++)act(s,'nonsense');a.equal(s.state.sandbox.recentCommands.length,128);a.doesNotThrow(()=>s.snapshot());});
test('unknown and prototype inventory properties are refused',()=>{for(let id of['banana','constructor','__proto__']){let s=S.fresh();Object.defineProperty(s.inventory,id,{value:10,enumerable:true});a.throws(()=>S.validate(s));}});
test('forged negative or non-finite counts are refused',()=>{for(let v of[-1,1.5,NaN,Infinity,1000]){let s=S.fresh();s.inventory.wood=v;a.throws(()=>S.validate(s));}});
test('forged bridge and resource rosters are refused',()=>{let s=S.fresh();s.bridge='true';a.throws(()=>S.validate(s));s=S.fresh();s.nodes.pop();a.throws(()=>S.validate(s));});
test('bridge is gated until paid repair',()=>{let s=fresh();a.equal(C.walkable(0,-26,s.navRoom),false);s.state.player={x:0,z:-21.3,yaw:0};a.equal(act(s,'bridge').ok,false);stock(s);let old=s.state.sandbox.inventory.plank;a.equal(act(s,'bridge').ok,true);a.equal(s.state.sandbox.inventory.plank,old-8);a.equal(C.walkable(0,-26,s.navRoom),true);a.equal(act(s,'bridge').ok,false);});
test('unlocked bridge has a route to the homestead and back',()=>{let s=fresh();unlock(s);for(let point of[{x:0,z:-40},{x:-5,z:-32.5},{x:0,z:3}]){let p=C.pathfind(s.state.player,point,s.navRoom);a.ok(p);let q=s.state.player;for(let n of p){a.ok(C.segment(q,n,s.navRoom));q=n;}}});
test('all frontier resources have an accessible approach after repair',()=>{let s=fresh();unlock(s);for(let n of S.NODES.filter(n=>n.wild))a.ok(C.pathfind(s.state.player,{x:n.x+1,z:n.z},s.navRoom),n.id);});
test('crystal requires the crafted pick',()=>{let s=fresh();unlock(s);node(s,'crystal-1');a.equal(act(s,'gather',{node:'crystal-1'}).ok,false);s.state.sandbox.inventory.pick=1;a.equal(act(s,'gather',{node:'crystal-1'}).ok,true);});
test('building only in marked bounds and within reach',()=>{let s=fresh();unlock(s);a.equal(place(s,'wall',4,0).ok,false);a.equal(place(s,'wall',-2,-3).ok,false);});
test('a block on the player is refused without consuming inventory',()=>{let s=fresh();unlock(s);at(s,-2,0,0,0);let n=s.state.sandbox.inventory.masonry;a.equal(place(s,'masonry',-2,0).ok,false);a.equal(s.state.sandbox.inventory.masonry,n);});
test('gold lane admits deck but rejects blocking wall',()=>{let s=fresh();unlock(s);at(s,0,1);a.equal(place(s,'wall',0,1).ok,false);a.equal(place(s,'floor',0,1).ok,true);});
test('actual building changes pathfinding and reclaim restores it',()=>{let s=fresh();unlock(s);at(s,-2,1);let p=S.worldCell(-2,1);a.equal(place(s,'masonry',-2,1).ok,true);a.equal(C.walkable(p.x,p.z,s.navRoom),false);a.equal(act(s,'reclaim',{gx:-2,gz:1}).ok,true);a.equal(C.walkable(p.x,p.z,s.navRoom),true);});
test('deck and block layers may coexist; stone stacks to three only',()=>{let s=fresh();unlock(s);at(s,-2,1);a.equal(place(s,'floor',-2,1).ok,true);for(let i=0;i<3;i++)a.equal(place(s,'masonry',-2,1).ok,true);a.equal(place(s,'masonry',-2,1).ok,false);a.equal(s.state.sandbox.placed.length,4);a.doesNotThrow(()=>s.snapshot());});
test('reclaim returns exactly the topmost crafted item',()=>{let s=fresh();unlock(s);at(s,-2,1);place(s,'floor',-2,1);place(s,'masonry',-2,1);let before=s.state.sandbox.inventory.masonry;a.equal(act(s,'reclaim',{gx:-2,gz:1}).ok,true);a.equal(s.state.sandbox.inventory.masonry,before+1);a.equal(s.state.sandbox.placed[0].kind,'floor');});
test('different furniture cannot overlap the same occupied layer',()=>{let s=fresh();unlock(s);at(s,-2,1);place(s,'bench',-2,1);a.equal(place(s,'lantern',-2,1).ok,false);});
test('unsupported stacks and duplicate layers fail import',()=>{let s=fresh();unlock(s);at(s,-2,1);place(s,'masonry',-2,1);let snap=s.snapshot();snap.sandbox.placed[0].level=3;a.throws(()=>C.validate(snap));snap=s.snapshot();snap.sandbox.placed.push({...snap.sandbox.placed[0],id:2});snap.sandbox.nextId=3;a.throws(()=>C.validate(snap));});
test('construction cannot trap a player in a closed enclosure',()=>{let s=fresh();unlock(s);const b=s.state.sandbox;b.placed=[];let id=1;for(let[gx,gz]of[[-3,-1],[-2,-1],[-1,-1],[-3,0],[-1,0],[-3,1],[-1,1]])b.placed.push({id:id++,kind:'masonry',gx,gz,rotation:0,level:1,crop:null});b.nextId=id;at(s,-2,0,0,0);a.ok(S.hasExit(b,s.state.player));a.equal(place(s,'masonry',-2,1).ok,false);});
test('harvest follows plant, water, growth, then yields food and seeds',()=>{let s=fresh();unlock(s);at(s,-2,1);place(s,'bed',-2,1);let o=s.state.sandbox.placed[0],berries=s.state.sandbox.inventory.berry,seeds=s.state.sandbox.inventory.seeds;a.equal(act(s,'crop',{object:o.id}).ok,true);a.equal(o.crop.stage,'seeded');step(s,100);a.equal(o.crop.stage,'seeded');act(s,'crop',{object:o.id});a.equal(o.crop.stage,'watered');a.equal(act(s,'crop',{object:o.id}).ok,false);step(s,91);a.equal(o.crop.stage,'ripe');a.equal(act(s,'crop',{object:o.id}).ok,true);a.equal(o.crop,null);a.equal(s.state.sandbox.inventory.berry,berries+3);a.equal(s.state.sandbox.inventory.seeds,seeds+1);});
test('growing bed cannot be recycled to silently lose crop state',()=>{let s=fresh();unlock(s);at(s,-2,1);place(s,'bed',-2,1);act(s,'crop',{object:s.state.sandbox.placed[0].id});a.equal(act(s,'reclaim',{gx:-2,gz:1}).ok,false);});
test('placed workbench unlocks workbench recipes locally',()=>{let s=fresh();unlock(s);at(s,2,0);a.equal(S.station(s.state.sandbox,s.state.player),false);place(s,'workbench',2,0);a.equal(S.station(s.state.sandbox,s.state.player),true);a.equal(act(s,'craft',{recipe:'pick'}).ok,true);});
test('save on unlocked shore preserves player, crops and builds',()=>{let s=fresh();unlock(s);at(s,-2,1);place(s,'bed',-2,1);act(s,'crop',{object:s.state.sandbox.placed[0].id});let snap=s.snapshot(),copy=new C.Simulation(snap);a.deepEqual(copy.snapshot(),snap);});
test('version-three save migration preserves creative data, starts clean inventory',()=>{let old=C.fresh();old.version=3;delete old.sandbox;old.score.title='Still my song';old.notes=[{text:'My old world',day:1}];const before=JSON.stringify(old),next=C.validate(old);a.equal(next.version,C.VERSION);a.equal(next.score.title,'Still my song');a.deepEqual(next.notes,old.notes);a.equal(next.sandbox.inventory.wood,0);a.equal(JSON.stringify(old),before);});
test('migration never overwrites earlier storage key',()=>{const old=C.fresh();old.version=3;delete old.sandbox;let data=new Map([[C.LEGACY_KEY,JSON.stringify(old)]]),store={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};let loaded=C.load(store);a.equal(loaded.status,'migrated');new C.Simulation(loaded.state).save(store);a.equal(JSON.parse(data.get(C.LEGACY_KEY)).version,3);a.equal(JSON.parse(data.get(C.KEY)).version,C.VERSION);});
test('invalid bridge-state save cannot place player beyond locked crossing',()=>{let s=fresh();unlock(s);let snap=s.snapshot();snap.sandbox.bridge=false;a.throws(()=>C.validate(snap));});
test('sandbox rejects gameplay in interiors',()=>{let s=fresh();stock(s);s.state.player={x:-11,z:-1.6,yaw:0};s.enter('home');a.equal(act(s,'craft',{recipe:'plank'}).ok,false);});
test('an oversized delta cannot fast-forward the sandbox',()=>{let s=fresh();s.tick(100000);a.equal(s.state.sandbox.elapsed,.1);s.tick(NaN);a.equal(s.state.sandbox.elapsed,.1);});
test('a full end-to-end milestone fixture is consistent and restorable',()=>{let s=fresh();unlock(s);s.state.player={x:11,z:9,yaw:0};act(s,'craft',{recipe:'pick'});s.state.sandbox.stats.gathered=20;at(s,-2,1);place(s,'floor',-2,1);place(s,'bed',-2,1);let o=s.state.sandbox.placed.find(p=>p.kind==='bed');act(s,'crop',{object:o.id});act(s,'crop',{object:o.id});step(s,91);act(s,'crop',{object:o.id});at(s,2,1);place(s,'lantern',2,1);a.equal(S.objectives(s.state.sandbox).filter(m=>m.done).length,6);a.doesNotThrow(()=>new C.Simulation(s.snapshot()));});
