"""Open the exact local Firstlight build on a stable, loopback-only save origin."""
from pathlib import Path
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlsplit
from urllib.request import build_opener, HTTPRedirectHandler, ProxyHandler
import argparse
import hashlib
import socket
import webbrowser

ROOT = Path(__file__).resolve().parents[1]


class NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, *_args, **_kwargs):
        return None


class LocalServer(ThreadingHTTPServer):
    # Windows SO_REUSEADDR can bind an already occupied listening port.
    # Claim it exclusively there; Unix keeps normal restart/TIME_WAIT behavior.
    allow_reuse_address = not hasattr(socket, 'SO_EXCLUSIVEADDRUSE')

    def server_bind(self):
        if hasattr(socket, 'SO_EXCLUSIVEADDRUSE'):
            self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_EXCLUSIVEADDRUSE, 1)
        super().server_bind()


def prepare_server(root, port):
    """Return (new server, False), or (None, True) for an exact existing build."""
    root = Path(root)
    try:
        body = (root / 'FIRSTLIGHT_VALLEY.html').read_bytes()
        index = (root / 'index.html').read_bytes()
    except OSError as error:
        raise RuntimeError('Build Firstlight first with python build.py.') from error
    if not body or body != index:
        raise RuntimeError('The generated HTML outputs must be identical. Run python build.py.')
    digest = hashlib.sha256(body).hexdigest()

    class GameHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            self.respond(True)

        def do_HEAD(self):
            self.respond(False)

        def respond(self, include_body):
            if urlsplit(self.path).path not in ('/', '/index.html', '/FIRSTLIGHT_VALLEY.html'):
                self.send_error(404)
                return
            self.send_response(200)
            self.send_header('Content-Type', 'text/html; charset=utf-8')
            self.send_header('Content-Length', str(len(body)))
            self.send_header('Cache-Control', 'no-store')
            self.send_header('X-Firstlight-Build', digest)
            self.end_headers()
            if include_body:
                self.wfile.write(body)

        def log_message(self, *_args):
            pass

    try:
        server = LocalServer(('127.0.0.1', port), GameHandler)
        server.daemon_threads = True
        return server, False
    except OSError as error:
        # Reuse this origin only when it serves these exact generated bytes.
        # Never kill another server or silently choose a different save origin.
        try:
            opener = build_opener(ProxyHandler({}), NoRedirect())
            with opener.open(f'http://127.0.0.1:{port}/FIRSTLIGHT_VALLEY.html', timeout=2) as response:
                existing = response.read(len(body) + 1)
            if existing == body:
                return None, True
        except OSError:
            pass
        raise RuntimeError(f'Port {port} is unavailable or serves a different build. '
                           'Stop that local server before starting this version. '
                           'Your saved browser worlds have not been changed.') from error


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--port', type=int, default=8780,
                        help='Default 8780. Changing the port changes the browser save origin.')
    parser.add_argument('--no-browser', action='store_true', help='Serve without opening a browser.')
    args = parser.parse_args()
    if not 1024 <= args.port <= 65535:
        parser.error('Choose a fixed port between 1024 and 65535; 8780 preserves the default origin.')
    try:
        server, reused = prepare_server(ROOT, args.port)
    except RuntimeError as error:
        print(str(error), flush=True)
        return 1
    url = f'http://127.0.0.1:{args.port}/'
    print(f'Firstlight is ready: {url}', flush=True)
    print('Use your usual browser profile to resume its saved characters.', flush=True)
    if not args.no_browser:
        webbrowser.open(url)
    if reused:
        print('The matching local build is already running.', flush=True)
        return 0
    print('Keep this window open while playing. Ctrl+C stops the local server.', flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
