/* Chapter UI submits bounded commands; the domain owns outcomes. */
(function(G){'use strict';const AR=G.RealmArsenal,R=G.RealmRoad,A=G.RealmAdventure,C=G.RealmCore,$=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,act,id='',disabled=false)=>'<button data-action="adv-'+act+'" data-id="'+esc(id)+'" '+(disabled?'disabled':'')+'>'+label+'</button>';
class AdventureUI{
 constructor(api){this.api=api;this.sequence=0;this.intent=null;this.storyIndex=0;this.storyWasPaused=false;this.labelCache='';
  $('#chapter-open').onclick=()=>api.openPanel('adventure');$('#battle-strike').onclick=()=>this.run('attack');$('#battle-pulse').onclick=()=>this.run('pulse');$('#battle-dodge').onclick=()=>this.run('dodge',api.direction());$('#battle-heal').onclick=()=>this.run('heal');$('#battle-seek').onclick=()=>this.run('seek');
  $('#revive-button').onclick=()=>{if(this.run('revive').ok)$('#fallen-dialog').close();};$('#fallen-dialog').addEventListener('cancel',e=>e.preventDefault());$('#story-close').onclick=()=>this.closeStory();$('#story-dialog').addEventListener('cancel',e=>{e.preventDefault();this.closeStory();});
 }
 get sim(){return this.api.sim();}get state(){return this.sim.state.adventure;}
 reset(){this.intent=null;this.labelCache='';$('#fallen-dialog').close();if($('#story-dialog').open)$('#story-dialog').close();}
 run(type,payload={},quiet=false){const result=this.sim.adventureCommand('adv-'+Date.now()+'-'+(++this.sequence),type,payload);if(result.ok&&!result.duplicate){this.api.save();this.api.changed();if(!quiet&&result.text)this.api.toast(result.text);this.sound(type);}else if(!quiet&&result.error)this.api.toast(result.error);if(!quiet&&this.api.panel()==='adventure')this.api.renderPanel();return result;}
 sound(type){let au=this.api.audio();if(!au?.enabled||!au.ctx)return;let f={'confirmed-hit':295,heal:660,dodge:330,dig:145,rescue:523,loot:880,relic:784,guard:245,insight:590,spirit:392,'beacon-answer':784,'beacon-repair':523}[type];if(f)au.note(f,au.ctx.currentTime,.15,.035);}
 stopAuto(){this.intent=null;}
 go(id){this.intent=null;this.api.endBuild();if(A.combatScene(this.sim)){this.api.toast('Use this expedition’s southern exit before taking an outdoor route.');return false;}if(id==='mine'){if(!this.sim.state.sandbox.bridge){this.api.toast('Repair the northern crossing first. The Field guide shows the materials.');return false;}this.api.closePanel();return this.api.walk(A.MINE.x,A.MINE.z);}if(id==='road')return this.api.navigate('lookout');if(id==='workshop')return this.api.navigate('market');if(id==='spring')return this.api.navigate('commons');return false;}
 approach(q,kind,id){let sim=this.sim,best=null;const ranged=kind==='attack'&&AR.weapon(this.state).style==='bow';if(ranged&&Math.hypot(q.x-sim.state.player.x,q.z-sim.state.player.z)<10.7&&AR.aimClear(sim,sim.state.player,q)){sim.playerPath=[];this.api.closePanel();this.intent={kind,id,q};return true;}const candidates=kind==='dig'?[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dz])=>({x:q.x+dx*1.7,z:q.z+dz*1.7})):Array.from({length:12},(_,i)=>({x:q.x+Math.sin(i*Math.PI/6)*(ranged?7:1.75),z:q.z+Math.cos(i*Math.PI/6)*(ranged?7:1.75)}));
  for(const p of candidates){if(!C.walkable(p.x,p.z,sim.navRoom)||ranged&&!AR.aimClear(sim,p,q))continue;const path=C.pathfind(sim.state.player,p,sim.navRoom);if(!path)continue;let d=0,last=sim.state.player;for(const n of path){d+=Math.hypot(n.x-last.x,n.z-last.z);last=n;}if(!best||d<best.d)best={...p,d};}
  if(!best){this.api.toast('There is no open route yet. Chip an exposed wall to make a passage.');return false;}this.api.walkLocal(best.x,best.z);this.api.closePanel();this.intent={kind,id,q};return true;
 }
 screenClick(x,y){
  if(!A.combatScene(this.sim))return false;
  const base=this.sim.room?1.58:1.3,candidates=[];
  for(const e of A.runtime(this.sim).enemies){if(e.hp<=0||e.hidden)continue;
   const height=e.kind==='boss'?4.8:e.custom==='bell'?3.8:e.eventEnemy?2.2:1.5;
   const foot=this.api.project(e.x,base+.12,e.z),head=this.api.project(e.x,base+height,e.z);if(!foot?.visible&&!head?.visible)continue;
   const dx=head.x-foot.x,dy=head.y-foot.y,t=Math.max(0,Math.min(1,((x-foot.x)*dx+(y-foot.y)*dy)/(dx*dx+dy*dy||1))),radius=Math.max(12,Math.hypot(dx,dy)*(e.kind==='boss'?.24:.48));
   if(Math.hypot(x-foot.x-t*dx,y-foot.y-t*dy)<=radius)candidates.push({e,depth:foot.depth});
  }
  candidates.sort((a,b)=>a.depth-b.depth);return candidates.length?this.worldClick(candidates[0].e):false;
 }
 worldClick(p){if(!p||!A.combatScene(this.sim))return false;const s=this.state,r=A.runtime(this.sim),enemy=r.enemies.filter(e=>e.hp>0&&!e.hidden&&Math.hypot(e.x-p.x,e.z-p.z)<1.5).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];
  if(enemy){if(this.run('target-select',{id:enemy.id},true).ok){this.intent=null;this.sim.playerPath=[];const t=G.RealmCombat.runtime(this.sim);t.auto=true;}return true;}if(this.sim.room==='mine'&&!s.companion.bonded&&Math.hypot(p.x-A.FOX.x,p.z-A.FOX.z)<1.1){this.approach(A.FOX,'rescue');return true;}
  const drop=s.drops.map(id=>A.roster(this.sim).find(e=>e.id===id)).filter(Boolean).find(e=>Math.hypot(e.x-p.x,e.z-p.z)<.8);if(drop){this.approach(drop,'loot',drop.id);return true;}
  if(this.sim.room==='riverbank'||this.sim.room==='range'||this.sim.room==='crossing'){this.intent=null;return false;}if(this.sim.room==='road'){const q=R.CACHES.find(c=>s.road.revealed.includes(c.id)&&!s.road.claimed.includes(c.id)&&Math.hypot(p.x-c.x,p.z-c.z)<1.1);if(q){this.approach(q,'road-cache',q.id);return true;}this.intent=null;return false;}
  let cell=A.cellAt(p.x,p.z);if(A.validCell(cell.gx,cell.gz)&&!A.isFloor(s,cell.gx,cell.gz)){this.approach({...A.cellPoint(cell.gx,cell.gz),...cell},'dig');return true;}this.intent=null;return false;
 }
 context(){let sim=this.sim,s=this.state,p=sim.state.player;if(s.hp<=0)return'Return to the spring';if(sim.room==='range')return Math.hypot(p.x,p.z-9)<3.2?'Leave the archery court':'Tab selects · 1 autoattack · 2 Piercing Light';if(sim.room==='road')return G.RealmBeacon.near(sim)&&s.road.beaconLit?(G.RealmBeacon.runtime(sim).phase==='assault'?'Repair the ward · 20 stamina':'Speak with the envoy at the beacon'):this.roadContext();if(!sim.room&&s.reward&&Math.hypot(p.x-R.GATE.x,p.z-R.GATE.z)<3.5)return'Take the Sunward Road';if(!sim.room&&s.road.beaconLit&&s.road.cartRepaired&&!s.road.reported&&Math.hypot(p.x,p.z-3)<4)return'Tell the envoy: the beacon is alight';
  if(sim.room==='mine'){if(Math.hypot(p.x,p.z-11)<3)return'Leave the underways';if(!s.companion.bonded&&Math.hypot(p.x+8,p.z-2)<3)return'Help the briarfox';if(s.defeated.includes('hart')&&!s.relic&&Math.hypot(p.x-9,p.z+10)<3)return'Recover the white feather';if(s.drops.some(id=>{let e=A.ENEMIES.find(e=>e.id===id);return !!e&&Math.hypot(p.x-e.x,p.z-e.z)<3;}))return'Collect nearby cache';if(A.nearbyWall(s,p))return'Chip nearby stone';return'Tab selects · 1 autoattack · 2–6 skills';}
  if(sim.room)return null;if(s.started&&Math.hypot(p.x-11,p.z-9)<3.5)return'Oren’s workbench · bows, gems & practice';if(Math.hypot(p.x-A.MINE.x,p.z-A.MINE.z)<3.3&&sim.state.sandbox.bridge)return'Enter the Rootbound Underways';if(Math.hypot(p.x-11,p.z-9)<3.5&&!s.started)return'Take Oren’s expedition supplies';if(Math.hypot(p.x,p.z-3)<4&&s.started)return s.relic?'Speak with the envoy':'Rest · refill health and tonics';return null;
 }
 interact(){let sim=this.sim,s=this.state,p=sim.state.player;if(sim.room==='range'){if(Math.hypot(p.x,p.z-9)<3.2)this.run('range-leave');else this.api.openPanel('armory');return true;}if(sim.room==='road')return this.roadInteract();if(!sim.room&&s.reward&&Math.hypot(p.x-R.GATE.x,p.z-R.GATE.z)<3.5){this.run('road-enter');return true;}if(!sim.room&&s.road.beaconLit&&s.road.cartRepaired&&!s.road.reported&&Math.hypot(p.x,p.z-3)<4){this.run('road-report');return true;}if(s.hp<=0){this.run('revive');return true;}
  if(sim.room==='mine'){this.intent=null;if(Math.hypot(p.x,p.z-11)<3){this.run('leave');return true;}if(!s.companion.bonded&&Math.hypot(p.x+8,p.z-2)<3){this.run('rescue');return true;}if(s.defeated.includes('hart')&&!s.relic&&Math.hypot(p.x-9,p.z+10)<3){this.run('relic');return true;}
   const drop=s.drops.find(id=>{let e=A.ENEMIES.find(e=>e.id===id);return !!e&&Math.hypot(p.x-e.x,p.z-e.z)<3;});if(drop){this.run('loot',{id:drop});return true;}const wall=A.nearbyWall(s,p);if(wall){this.run('dig',{gx:wall.gx,gz:wall.gz});return true;}this.api.toast('Click a stone face to mine, or click an enemy to approach and strike.');return true;}
  if(sim.room)return false;if(s.started&&Math.hypot(p.x-11,p.z-9)<3.5){this.api.openPanel('armory');return true;}if(Math.hypot(p.x-A.MINE.x,p.z-A.MINE.z)<3.3&&sim.state.sandbox.bridge){this.run('enter');return true;}if(Math.hypot(p.x-11,p.z-9)<3.5&&!s.started){this.run('start');return true;}if(Math.hypot(p.x,p.z-3)<4&&s.started){if(s.relic){if(this.run('reveal').ok)this.openStory();}else this.run('rest');return true;}return false;
 }
 key(k){if($('#story-dialog').open||$('#fallen-dialog').open)return true;if(k==='8'||k==='u'){this.api.openPanel('adventure');return true;}if(A.combatScene(this.sim)&&['f','q',' ','g'].includes(k)){this.intent=null;this.run(({f:'attack',q:'pulse',' ':'dodge',g:'heal'})[k],k===' '?this.api.direction():{});return true;}if(k==='l'&&this.sim.room==='road'){this.run('seek');return true;}if(k==='escape'&&A.combatScene(this.sim)&&!this.api.panel()){this.run(this.sim.room==='riverbank'?'starter-leave':this.sim.room==='range'?'range-leave':this.sim.room==='road'?'road-leave':'leave');return true;}return false;}
 action(b){let act=b.dataset.action;if(!act?.startsWith('adv-'))return false;act=act.slice(4);const id=b.dataset.id;
  if(act==='trade')this.run('trade',{offer:b.dataset.offer});else if(act==='road-route')this.roadRoute(id);else if(act==='go')this.go(id);else if(act==='mode')this.run('companion-mode',{mode:id});else if(act==='rename')this.run('rename',{name:$('#companion-name').value});else if(act==='equip')this.run('equip',{id});
  else if(act==='seek'){if(this.sim.room==='road'){this.run('seek');return true;}if(this.sim.room!=='mine'){this.api.toast('Enter the mine first.');return true;}if(id==='fox')this.approach(A.FOX,'rescue');else if(id==='relic')this.approach(A.RELIC,'relic');else if(id==='exit')this.approach(A.ENTRANCE,'leave');else{let e=A.runtime(this.sim).enemies.find(e=>e.id===id&&e.hp>0);if(e)this.approach(e,'attack',id);else if(this.state.drops.includes(id)){const item=A.ENEMIES.find(e=>e.id===id);if(item)this.approach(item,'loot',id);}}}
  else if(act==='story'){if(this.run('reveal').ok)this.openStory();}else this.run(act);return true;
 }
 roadContext(){
  const s=this.state,p=this.sim.state.player,near=(q,n=3)=>Math.hypot(p.x-q.x,p.z-q.z)<n;
  if(near(R.ENTRY))return'Return through the waygate';if(near(R.MERCHANT))return s.road.cartRepaired?'Trade with Tessa':'Repair Tessa’s cart · latch + 2 copper';if(near(R.BEACON))return s.road.beaconLit?'The beacon is alight':'Kindle the Sunward Beacon';if(R.CACHES.some(c=>near(c)&&s.road.revealed.includes(c.id)&&!s.road.claimed.includes(c.id)))return'Collect Briar’s discovery';if(A.roster(this.sim).some(e=>near(e)&&s.drops.includes(e.id)))return'Collect encounter cache';return'Tab selects · 1 autoattack · 4 Briar · Space dodge';
 }
 roadInteract(){
  const s=this.state,p=this.sim.state.player,near=q=>Math.hypot(p.x-q.x,p.z-q.z)<3;this.intent=null;
  if(s.hp<=0){this.run('revive');return true;}if(near(R.ENTRY)){this.run('road-leave');return true;}if(near(R.MERCHANT)){if(s.road.cartRepaired)this.api.openPanel('adventure');else this.run('cart-repair');return true;}if(near(R.BEACON)){this.run('beacon-light');return true;}
  const cache=R.CACHES.find(c=>near(c)&&s.road.revealed.includes(c.id)&&!s.road.claimed.includes(c.id));if(cache){this.run('road-cache',{id:cache.id});return true;}const drop=R.ENEMIES.find(e=>near(e)&&s.drops.includes(e.id));if(drop){this.run('loot',{id:drop.id});return true;}this.run('seek');return true;
 }
 roadRoute(id){
  if(this.sim.room!=='road'){this.api.toast('Take the Sunward Road first.');return;}
  const e=A.runtime(this.sim).enemies.find(e=>e.id===id&&e.hp>0);if(e){this.approach(e,'attack',id);return;}const drop=R.ENEMIES.find(e=>e.id===id&&this.state.drops.includes(id));if(drop){this.approach(drop,'loot',id);return;}const c=R.CACHES.find(c=>c.id===id&&this.state.road.revealed.includes(id)&&!this.state.road.claimed.includes(id));if(c){this.approach(c,'road-cache',id);return;}
  const places={cart:R.MERCHANT,beacon:R.BEACON,bridge:{x:2,z:3.4},scent:{x:-9,z:5},ruins:{x:9,z:-13},exit:R.ENTRY};if(places[id]){this.intent=null;this.api.walkLocal(places[id].x,places[id].z);this.api.closePanel();}
 }
 roadPanel(){
  const s=this.state,inRoad=this.sim.room==='road',r=s.road;
  let html='<article class="road-heading"><small>CHAPTER II · THE ROAD AFTER THE PROPHECY</small><h3>The Sunward Road</h3><p>A stranded trader, a fox’s first discovery, and a beacon beyond the trees.</p>'+button('Walk to the far-water lookout','go','road')+button('Take the road','road-enter')+'</article>';
  html+=R.objectives(s).map((q,i)=>'<article class="journey-card '+(q.done?'complete':'')+'"><span class="journey-number">'+(q.done?'✓':i+1)+'</span><div><h3>'+q.title+'</h3><p>'+q.detail+'</p></div></article>').join('');
  if(inRoad){html+='<div class="section-label">Routes · actions happen on arrival</div><div class="row">'+[['cart','Tessa’s camp'],['scent','Western meadow'],['bridge','Stone bridge'],['ruins','Northern ruins'],['beacon','Sunward beacon'],['exit','Waygate home']].map(([id,n])=>button(n,'road-route',id)).join('')+'</div><div class="row">'+R.ENEMIES.map(e=>button(s.drops.includes(e.id)?'Cache: '+e.name:e.name,'road-route',e.id,s.defeated.includes(e.id)&&!s.drops.includes(e.id))).join('')+'</div><div class="row">'+button('Briar: seek a nearby scent · L','seek')+button('Kindle beacon','beacon-light')+'</div>';for(const c of R.CACHES)if(r.revealed.includes(c.id)&&!r.claimed.includes(c.id))html+=button(c.name,'road-route',c.id);}
  html+='<article class="card"><h3>Tessa’s travelling shop</h3><p>'+(r.cartRepaired?'Repair complete. Trade at the cart; quantities and prices below are exact.':'Find the latch with Briar, clear the prowler and bring 2 copper to the cart.')+'</p>'+button('Repair cart','cart-repair','',r.cartRepaired);
  if(r.cartRepaired)html+='<div class="shop-grid">'+[['tonic','Buy tonic · 2 sunmarks'],['mantle','Buy storm mantle · 18 sunmarks'],['sell-copper','Sell 2 copper · receive 3'],['sell-berries','Sell 2 sunberries · receive 1']].map(([id,n])=>'<button data-action="adv-trade" data-offer="'+id+'">'+n+'</button>').join('')+'</div>';
  html+='</article>';if(r.beaconLit&&r.cartRepaired)html+=button(r.reported?'Road reported':'Report to the envoy at home','road-report','',r.reported);return html+'<details class="chapter-previous"><summary>Chapter I and equipment below</summary><p>The mine and its earned history remain intact. This surface chapter has no online economy.</p></details>';
 }
 roadLabels(){const s=this.state,r=A.runtime(this.sim),labels=[{...R.ENTRY,y:4,text:'Waygate · home'},{...R.MERCHANT,y:3.6,text:'Tessa · '+(s.road.cartRepaired?'Road shop':'Stranded trader')},{...R.BEACON,y:5.7,text:s.road.beaconLit?'The beacon is alight':'Sunward Beacon'}];for(const e of r.enemies)if(e.hp>0&&!e.hidden)labels.push({x:e.x,z:e.z,y:e.kind==='charger'?5.3:4.15,text:e.name});for(const e of R.ENEMIES)if(s.drops.includes(e.id))labels.push({x:e.x,z:e.z,y:3,text:'◇ Cache'});for(const c of R.CACHES)if(s.road.revealed.includes(c.id)&&!s.road.claimed.includes(c.id))labels.push({...c,y:3.1,text:c.name});return labels;}
 renderPanel(name){if(name!=='adventure')return null;let s=this.state,st=A.stats(s),room=this.sim.room;let html=(s.reward?this.roadPanel():'')+'<p class="intro">CHAPTER I · The Feather Beneath Wildwood<br>A local, single-player adventure. Your home and creative work stay intact.</p>';
  html+='<div class="adventure-stats"><span><b>'+st.level+'</b>Level</span><span><b>'+st.attack+'</b>Attack</span><span><b>'+st.defense+'</b>Guard</span><span><b>'+s.xp+'</b>XP</span><span><b>'+s.ore+'</b>Copper</span><span><b>'+s.coins+'</b>Sunmarks</span></div><div class="row">'+button('Oren’s workshop','go','workshop')+button('Mine entrance','go','mine')+button('Firstlight spring','go','spring')+'</div>';
  if(!s.started)html+='<article class="card"><h3>Leave prepared.</h3><p>Take a trail blade, lantern, salve and three tonics from Oren. Craft a pickaxe and repair the northern crossing using the existing Field guide.</p>'+button('Take expedition supplies','start')+'</article>';else if(!room)html+='<div class="row">'+button('Enter mine','enter')+button('Rest at the spring','rest')+'</div>';
  html+='<div class="section-label">Your chapter</div>'+A.objectives(s).map((q,i)=>'<article class="journey-card '+(q.done?'complete':'')+'"><span class="journey-number">'+(q.done?'✓':i+1)+'</span><div><h3>'+q.title+'</h3><p>'+q.detail+'</p></div></article>').join('');
  if(room==='mine')html+='<div class="section-label">Routes in the underways</div><div class="row">'+button('Western fox alcove','seek','fox')+A.ENEMIES.map(e=>button(s.drops.includes(e.id)?'Cache: '+e.name:e.name,'seek',e.id,s.defeated.includes(e.id)&&!s.drops.includes(e.id))).join('')+button('Feather dais','seek','relic')+button('Southern exit','seek','exit')+'</div><p class="intro">Blocked routes need an exposed wall chipped away. Violet circles show where an enemy will strike. Move out before they close.</p>';
  if(s.relic)html+='<div class="row">'+button(s.reward?'Hear the envoy again':'Hear the envoy’s warning','story')+'</div>';
  html+='<div class="section-label">Equipment</div>';for(const id of s.owned){let g=A.GEAR[id],on=s.equipment[g.slot]===id;html+='<article class="card"><div class="card-header"><h3 style="color:'+g.color+'">'+g.name+'</h3><span class="badge">'+g.tier+'</span></div><p>'+g.desc+'<br>'+g.slot+' · '+(g.attack?'+'+g.attack+' attack ':'')+(g.defense?'+'+g.defense+' guard ':'')+(g.hp?'+'+g.hp+' health':'')+'</p>'+button(on?'Equipped':'Equip','equip',id,on)+'</article>';}
  if(s.started)html+='<article class="card"><h3>Copper-edged blade</h3><p>Forge at an outdoor workbench with 4 copper ore and 4 sunmarks. Materials are spent only on success.</p>'+button(s.owned.includes('copper_blade')?'Already forged':'Forge copper blade','forge','',s.owned.includes('copper_blade'))+'</article>';
  html+='<div class="section-label">Your companion</div>';if(s.companion.bonded)html+='<article class="card"><h3>'+esc(s.companion.name)+' · Briarfox</h3><p>Follows paths and helps against engaged enemies. Stay stops following and combat assistance. Follow recalls across scenes. Reload starts the fox beside you. No companion death or evolution in this chapter.</p><label for="companion-name">Name</label><input id="companion-name" maxlength="24" value="'+esc(s.companion.name)+'"><div class="row">'+button('Keep name','rename')+button('Follow & assist','mode','follow',s.companion.mode==='follow')+button('Stay','mode','stay',s.companion.mode==='stay')+'</div></article>';else html+='<p class="intro">An injured animal is hiding in the western alcove. Oren included one story salve. Free the alcove before approaching.</p>';
  return html+'<div class="notice">F strike · Q sweep · Space dodge · G tonic · E interact. P pauses the world. No online items, server or live AI. Safe resurrection preserves your home, excavation and completed encounters.</div>';
 }
 openStory(){this.intent=null;this.api.clearKeys();this.api.closePanel();this.storyIndex=0;this.storyWasPaused=this.sim.paused;this.sim.paused=true;this.paintStory();$('#story-dialog').showModal();}
 paintStory(){let q=A.STORY[this.storyIndex];$('#story-speaker').textContent=q.speaker.toUpperCase();$('#story-title').textContent=q.title;$('#story-body').textContent=q.body;let area=$('#story-buttons');area.replaceChildren();const btn=(text,fn)=>{let b=document.createElement('button');b.textContent=text;b.onclick=fn;area.append(b);};if(this.storyIndex<A.STORY.length-1)btn('Listen',()=>{this.storyIndex++;this.paintStory();});else if(this.state.reward)btn('Return to the valley',()=>this.closeStory());else for(const id of['dawn_edge','warden_stone'])btn(A.GEAR[id].name+' · '+(id==='dawn_edge'?'Power':'Endurance'),()=>{this.sim.paused=false;const res=this.run('reward',{id});this.sim.paused=true;if(res.ok)this.closeStory();});}
 closeStory(){if($('#story-dialog').open)$('#story-dialog').close();this.sim.paused=this.storyWasPaused;this.api.clearKeys();}
 tick(){let sim=this.sim,s=this.state,r=A.runtime(sim),mine=A.combatScene(sim);A.syncScene(sim);
  if(this.intent&&!sim.paused&&!sim.playerPath.length&&s.hp>0){let i=this.intent;
   if(i.kind==='attack'){let e=r.enemies.find(e=>e.id===i.id&&e.hp>0);if(!e)this.intent=null;else if(Math.hypot(e.x-sim.state.player.x,e.z-sim.state.player.z)>=AR.weapon(s).reach||!(AR.weapon(s).style==='bow'?AR.aimClear(sim,sim.state.player,e):A.visible(sim,sim.state.player,e))){if(s.elapsed>(this.nextApproach||0)){this.nextApproach=s.elapsed+.8;this.approach(e,'attack',e.id);}}else{const t=G.RealmCombat.runtime(sim);t.target=e.id;t.auto=true;this.intent=null;}}
   else if(i.kind==='dig'){if(A.isFloor(s,i.q.gx,i.q.gz))this.intent=null;else if(s.elapsed>=r.cooldowns.dig){if(!this.run('dig',{gx:i.q.gx,gz:i.q.gz},true).ok)this.intent=null;}}
   else{this.run(i.kind,['loot','road-cache'].includes(i.kind)?{id:i.id}:{},false);this.intent=null;}
  }
  while(r.notices.length)this.api.toast(r.notices.shift());if(s.hp<=0){this.intent=null;if(!$('#fallen-dialog').open)$('#fallen-dialog').showModal();}
  document.body.classList.toggle('in-mine',mine);$('#battle-hud').hidden=!mine;$('#battle-seek').hidden=sim.room!=='road';$('#battle-seek').disabled=!s.companion.bonded||s.companion.mode!=='follow'||!!r.companion.seek;let st=A.stats(s);$('#hp-label').textContent=Math.ceil(s.hp)+' / '+st.maxHP+' HEALTH';$('#hp-fill').style.width=(s.hp/st.maxHP*100)+'%';$('#stamina-fill').style.width=s.stamina+'%';$('#battle-level').textContent=st.level;$('#battle-stats').textContent=st.attack+' ATK · '+st.defense+' GUARD · '+s.xp+' XP';$('#tonic-label').textContent=s.tonics+' tonics · G';$('#battle-pulse').disabled=s.elapsed<r.cooldowns.pulse||s.stamina<30;$('#battle-dodge').disabled=s.elapsed<r.cooldowns.dodge||s.stamina<22;$('#battle-heal').disabled=!s.tonics||s.hp>=st.maxHP||s.elapsed<r.cooldowns.heal;
  let next=(s.reward?R.objectives(s):A.objectives(s)).find(q=>!q.done);$('#chapter-next').textContent=next?next.title:'A road restored; a home kept';$('#chapter-open > span').textContent=s.reward?'CHAPTER II':'CHAPTER I';$('#chapter-open > strong').textContent=s.reward?'The Sunward Road':'The feather beneath Wildwood';
  // Keep the selected dig target visible through unrelated music/UI refreshes.
  if(sim.presentation){sim.presentation.attackTarget=this.intent?.kind==='attack'?this.intent.id:null;const w=this.intent?.kind==='dig'?this.intent.q:null;sim.presentation.digCell=w?{gx:w.gx,gz:w.gz,valid:A.diggableFrom(s,sim.state.player,w.gx,w.gz)}:null;}
  this.labels();
 }
 labels(){let sim=this.sim,s=this.state,r=A.runtime(sim),labels=[];if(sim.room==='range'){labels.push({x:0,y:4.6,z:11.5,text:'Workshop · south gate'});for(const e of r.enemies)labels.push({x:e.x,y:4.55,z:e.z,text:e.name});}else if(sim.room==='road'){labels.push(...this.roadLabels());if(this.state.beacon.introduced){const br=G.RealmBeacon.runtime(sim);labels.push({x:0,y:5.1+Math.max(0,br.phase==='arrival'?(1-br.time/8)*7:0),z:-24.3,text:'The envoy · holding the road'});for(const q of br.actors)labels.push({x:q.x,y:3.9,z:q.z,text:q.id[0].toUpperCase()+q.id.slice(1)+' · '+(q.path.length?'arriving':q.role)});}}else if(sim.room==='mine'){labels.push({x:0,y:3.8,z:12.5,text:'↑ Lantern exit'});if(!s.companion.bonded)labels.push({x:-8,y:3.2,z:2,text:'An injured briarfox'});for(const e of r.enemies)if(e.hp>0&&!e.hidden)labels.push({x:e.x,y:e.kind==='boss'?5.7:4.18,z:e.z,text:e.name});for(const id of s.drops){let e=A.ENEMIES.find(e=>e.id===id);if(!e)continue;labels.push({x:e.x,y:3,z:e.z,text:'◇ Cache'});}if(s.defeated.includes('hart')&&!s.relic)labels.push({x:9,y:3.8,z:-10,text:'✦ White feather'});}else if(!sim.room){if(s.reward)labels.push({x:R.GATE.x,y:4.4,z:R.GATE.z,text:'The Sunward Road'});if(sim.state.sandbox.bridge)labels.push({x:0,y:5.5,z:-48,text:'The Rootbound Underways'});if(s.angelSeen)labels.push({x:-2.3,y:4.8,z:4.7,text:'The envoy'});}if(s.companion.bonded&&r.companion.room===sim.room)labels.push({x:r.companion.x,y:(sim.room===G.RealmCosmos?.ROOM?G.RealmCosmos.height(r.companion.x,r.companion.z):sim.room?1.58:1.31)+1.45,z:r.companion.z,text:s.companion.name+' · '+(s.companion.mode==='stay'?'waiting':r.companion.status||'following')});
  if(sim.room==='road'&&G.RealmBeacon.runtime(sim).phase==='assault'){const chosen=G.RealmCombat.selected(sim);labels=labels.filter(l=>l.text===chosen?.name||l.text.startsWith('The envoy')||l.text.startsWith(s.companion.name+' ·'));}
  let root=$('#adventure-labels');if(!sim.state.settings.labels){root.replaceChildren();return;}const visible=labels.map(l=>({...l,p:this.api.project(l.x,l.y,l.z)})).filter(l=>l.p?.visible);const signature=visible.map(l=>l.text).join('|');if(signature!==this.labelCache||root.children.length!==visible.length){root.replaceChildren();for(let l of visible){let e=document.createElement('span');e.className='adventure-label';e.textContent=l.text;root.append(e);}this.labelCache=signature;}visible.forEach((l,i)=>{let e=root.children[i];e.style.left=l.p.x+'px';e.style.top=l.p.y+'px';});
 }
}
G.RealmAdventureUI={AdventureUI};})(globalThis);
