/* Interface, camera and local persistence. Nothing in this file calls a server.
 * Residents use explicit routines and authored dialogue, not a hidden AI API. */
(function(){'use strict';const C=RealmCore,X=RealmCreative,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui={canvas:$('#world'),map:$('#map-fallback'),drawer:$('#drawer'),body:$('#drawer-body'),title:$('#panel-title'),toast:$('#toast')};let loaded=C.load({getItem:k=>localStorage.getItem(k)}),sim=new C.Simulation(loaded.state),engine=null,art=null,experience=null,sandbox=null,adventure=null,arsenal=null,rpg=null,errors=[],scene=null,panel=null,lastFocus=null,selected=null,follow=null,commandCount=0,target=null,toastTimer=0,elapsed=0,lastFrame=0,frames=0,fps=0,fpsStart=performance.now(),lastUi=0,lastSave=0,saveState=['loaded','migrated'].includes(loaded.status)?'saved':'new',preserveExisting=!!loaded.preserveExisting;let camera={yaw:.76,elevation:.88,half:17,center:[sim.state.player.x,1.7,sim.state.player.z],overview:false,preset:'follow'};
function error(e){errors.push(String(e.message||e));console.error(e);}window.addEventListener('error',e=>{error(e.error||e.message);$('#loading').classList.add('hidden');});window.addEventListener('unhandledrejection',e=>error(e.reason));
function toast(text){ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),4200);}
function fallback(reason){engine=null;art=null;ui.canvas.style.display='none';ui.map.style.display='block';$('#fallback-banner').style.display='block';$('#fallback-banner').textContent=reason||'3D is unavailable. Explore the same local world using this map.';document.getElementById('labels').replaceChildren();resize();}
try{engine=new RealmEngine.Engine(ui.canvas);engine.quality=sim.state.settings.quality;art=new RealmArt.WorldArt(engine);}catch(e){errors.push('Handled graphics fallback: '+e.message);fallback();}
function resize(){let w=innerWidth,h=innerHeight;if(engine)engine.resize(w,h,devicePixelRatio||1);ui.map.width=Math.round(w*(devicePixelRatio||1));ui.map.height=Math.round(h*(devicePixelRatio||1));if(camera.overview)camera.half=sim.room==='range'?Math.max(19,17/Math.max(.35,innerWidth/innerHeight)):sim.room==='crossing'?33:sim.room==='road'?30:sim.room==='mine'?17:sim.room?7:Math.max(36,39/Math.max(.55,w/h));updateCamera(1);}
function updateCamera(dt){if(!engine)return;let desired;if(camera.tour&&!sim.room){camera.tourTime=(camera.tourTime||0)+dt;let spots=[[0,1.7,2,23,.72],[14,1.8,3,19,.87],[33,2,1,17,1.05],[37,2,-1,14,1.23],[23,2,3,23,.85],[0,1.7,2,23,.72]],f=(camera.tourTime%60)/12,i=Math.min(4,Math.floor(f)),u=f-i;u=u*u*(3-2*u);let a=spots[i],b=spots[i+1];desired=a.slice(0,3).map((v,j)=>v+(b[j]-v)*u);camera.half=a[3]+(b[3]-a[3])*u;camera.yaw=a[4]+(b[4]-a[4])*u;}else if(sim.room==='range')desired=camera.overview?[0,2,0]:[sim.state.player.x,2,sim.state.player.z];else if(sim.room==='crossing')desired=camera.overview?[0,2,-1]:[sim.state.player.x,2,sim.state.player.z];else if(sim.room==='road')desired=camera.overview?[0,1.7,-3]:[sim.state.player.x,2,sim.state.player.z];else if(sim.room==='mine')desired=camera.overview?[0,2,-1]:[sim.state.player.x,2,sim.state.player.z];else if(sim.room)desired=[0,2,0];else if(camera.overview)desired=[10,1.7,-10];else{let p=follow?sim.state.residents.find(r=>r.id===follow):sim.state.player;desired=[p.x,1.9,p.z];}let factor=1-Math.exp(-Math.max(dt,.001)*2.6);for(let i=0;i<3;i++)camera.center[i]+=(desired[i]-camera.center[i])*factor;let d=75,ce=Math.cos(camera.elevation),eye=[camera.center[0]+Math.sin(camera.yaw)*ce*d,camera.center[1]+Math.sin(camera.elevation)*d,camera.center[2]+Math.cos(camera.yaw)*ce*d];engine.setCamera({eye,target:camera.center.slice(),half:camera.half,aspect:innerWidth/innerHeight});}
function cameraPreset(mode='follow'){
 camera.tour=false;follow=null;camera.preset=mode;camera.overview=mode==='wide';
 if(mode==='follow'){camera.yaw=.76;camera.elevation=.88;camera.half=sim.room==='mine'?12:sim.room==='range'?14:sim.room&&sim.room!=='road'&&sim.room!=='crossing'?7:17;}
 if(mode==='tactical'){camera.elevation=1.08;camera.half=sim.room==='mine'?16:sim.room==='range'?17:sim.room&&sim.room!=='road'&&sim.room!=='crossing'?8:21;}
 if(mode==='wide')resize();updateCamera(1);rpg?.cameraPaint(mode);
}
function switchScene(){if(scene===sim.room)return;scene=sim.room;camera.tour=false;if(engine){if(scene==='crossing')RealmCrossingArt.make(art,sim);else if(scene==='range')RealmArsenalArt.court(art);else if(scene==='road')RealmRoadArt.make(art,sim);else if(scene==='mine')RealmAdventureArt.cave(art,sim);else if(scene)art.makeInterior(scene,sim.state.retreat);else art.makeExterior();}cameraPreset('follow');camera.center=[sim.state.player.x,2,sim.state.player.z];target=null;follow=null;labelsRebuild();resize();}
function save(){if(preserveExisting){saveState='preserved';renderStatus();return{ok:false,error:'Existing storage could not be read. Export a JSON backup; it has not been overwritten.'};}let r=sim.save({setItem:(k,v)=>localStorage.setItem(k,v)});saveState=r.ok?'saved':'unavailable';renderStatus();return r;}
function renderStatus(){$('#save-status').innerHTML=saveState==='saved'?'<i class="dot"></i>SAVED ON THIS DEVICE':saveState==='new'?'<i class="dot"></i>LOCAL WORLD':'MEMORY ONLY · EXPORT TO KEEP';}
function command(type,payload){let r=sim.act('ui-'+Date.now()+'-'+(++commandCount),type,payload);if(r.ok)save();if(r.text)toast(r.text);else if(r.error)toast(r.error);return r;}
function navigate(id){if(RealmAdventure.combatScene(sim)){toast('Use this area’s exit before choosing a valley destination.');return false;}adventure?.stopAuto();sandbox?.stopAuto();sandbox?.endBuild();camera.tour=false;let l=C.LANDMARKS.find(x=>x.id===id);if(!l)return false;if(sim.room){sim.leave();switchScene();}let r=sim.moveTo(l.x,l.z);if(r.ok){target={x:l.x,z:l.z};follow=null;camera.overview=false;camera.half=innerWidth<650?18:17;toast('Walking to '+l.short.toLowerCase()+'.');}else toast(r.error);return r.ok;}
function action(id){if(RealmAdventure.combatScene(sim)){toast('Use this area’s exit before interacting with valley locations.');return;}let l=C.LANDMARKS.find(l=>l.id===id);if(!l)return;if(sim.room){sim.leave();switchScene();save();return;}if(Math.hypot(sim.state.player.x-l.x,sim.state.player.z-l.z)>3.4){navigate(id);toast('Walk closer, then interact at '+l.short.toLowerCase()+'.');return;}if(l.kind==='interior'){let r=sim.enter(id);if(r.ok){switchScene();save();closePanel();toast('Welcome inside. Press E or Escape to return.');}else toast(r.error);}else if(id==='garden'){command('plant');}else if(id==='stage'){if(sim.gathering){experience.open();return;}let r=command('gather');if(r.ok){let playing=experience.play();toast(playing?'Your piece is playing. Ilan, Mara and Oren are walking to the stage.':'The family is walking here. Enable sound to play your piece.');}}else if(id==='market'){sim.event('workshop','You inspected Oren’s portable music stand project.');save();openPanel('inhabitants');selectResident('oren');}else{sim.event('rest',id==='shore'?'You spent a quiet moment beside the water.':id==='commons'?'You rested under the Firstlight tree.':'You rested at '+l.name+'.');save();toast(id==='shore'?'The valley keeps its own small rhythm.':'There is nothing you have to finish right now.');}}
function closest(){let p=sim.state.player,b=null,d=3.4;for(let l of C.LANDMARKS){let dd=Math.hypot(p.x-l.x,p.z-l.z);if(dd<d){b=l;d=dd;}}return b;}
function interact(){if(rpg?.interact())return;if(adventure?.interact())return;if(sandbox?.interact())return;if(sim.room){sim.leave();switchScene();save();toast('Back beneath the open sky.');return;}let l=closest();if(l)action(l.id);else toast('Approach a doorway, garden, stage or pier. Explore lists every destination.');}
function openPanel(name){if(rpg?.intercept(name))return;if(rpg?.dialog.open)rpg.close();RealmCombat.stop(sim);adventure?.stopAuto();keys.clear();if(name!=='build')sandbox?.endBuild();if(experience?.dialog.open)experience.close();if(panel===name){closePanel();return;}lastFocus=document.activeElement;panel=name;ui.drawer.inert=false;ui.drawer.classList.add('open');document.body.classList.add('panel-open');for(let el of document.querySelectorAll('[data-panel]'))el.setAttribute('aria-pressed',el.dataset.panel===name?'true':'false');renderPanel();$('#close-panel').focus({preventScroll:true});}
function closePanel(){panel=null;ui.drawer.classList.remove('open');ui.drawer.inert=true;document.body.classList.remove('panel-open');for(let el of document.querySelectorAll('[data-panel]'))el.setAttribute('aria-pressed','false');if(lastFocus&&document.contains(lastFocus))lastFocus.focus({preventScroll:true});}
const button=(label,act,extra='')=>'<button data-action="'+act+'" '+extra+'>'+label+'</button>';
function renderPanel(){if(!panel)return;let s=sim.state,html='',custom=arsenal?.renderPanel(panel)??adventure?.renderPanel(panel)??sandbox?.renderPanel(panel)??experience?.renderPanel(panel);if(custom!==null&&custom!==undefined){ui.title.textContent=({armory:'The Bow & Gem',adventure:sim.state.adventure.reward?'The Sunward Road':'The Feather Beneath Wildwood',pack:'A little room to carry things',craft:'From gathered to made',build:'Your Wildwood homestead',journey:'A home beyond the valley',retreat:'A place of your own',visitor:'Your visitor'})[panel]||'Firstlight';ui.body.innerHTML=custom;return;}if(panel==='explore'){ui.title.textContent='Places to become';html='<div class="row"><button data-action="sb-open" data-id="journey">Wildwood field guide</button><button data-action="sb-open" data-id="armory">Bows & gems</button><button data-action="open-visitor">Visitor</button><button data-action="open-retreat">My room</button><button data-action="sb-open" data-id="inhabitants">Inhabitants</button><button data-action="sb-open" data-id="chronicle">Chronicle</button></div>'+'<p class="intro">Choose a path. The valley is walkable; the far mountains are scenery. Cross the eastern bridge to your retreat and the blossom garden. Four doors open into rendered interiors.</p>'+C.LANDMARKS.map(l=>'<article class="card"><div class="card-header"><h3>'+esc(l.short)+'</h3><span class="badge">'+(s.visited.includes(l.id)?'discovered':'unvisited')+'</span></div><p>'+esc(l.description)+'</p><div class="row">'+button('Walk here','walk','data-id="'+l.id+'"')+button(l.action,'place-action','data-id="'+l.id+'"')+'</div></article>').join('');}
 else if(panel==='inhabitants'){ui.title.textContent='Lives in the valley';html='<p class="intro">Ilan, Mara and Oren are an authored family simulation. Their routines, encounters and project counters persist locally. No Luna instance or language model is connected.</p>';if(selected){let p=C.PROFILES.find(p=>p.id===selected),r=s.residents.find(r=>r.id===selected),run=sim.runs.get(selected),l=C.LANDMARKS.find(x=>x.id===run.goal);html+='<div class="card"><div class="card-header"><span class="avatar" style="background:'+p.color+'44">'+p.name[0]+'</span><div><h3>'+p.name+'</h3><small>'+p.role+' · '+(run.inside?'At home':run.walking?'On the way':l.short)+'</small></div></div><p>'+esc(p.kin)+'. '+esc(p.description)+'</p><div class="project"><small>'+esc(p.projectKind)+'</small><strong>'+esc(p.project)+'</strong><div class="progress"><i style="width:'+Math.round(r.progress*100)+'%"></i></div><small>Local routine progress · not verified creative output</small></div>'+(p.tracks?'<p>'+p.tracks.map((t,i)=>(i+1)+'. '+esc(t)).join('<br>')+'</p>':'')+'<div id="dialogue-slot"></div><div class="row">'+button('Exchange a few words','talk','data-id="'+p.id+'"')+button(follow===p.id?'Stop following':'Follow','follow','data-id="'+p.id+'"')+button('Walk to their place','resident-walk','data-id="'+p.id+'"')+'</div></div>';}
 html+=C.PROFILES.filter(p=>p.id!==selected).map(p=>{let r=s.residents.find(x=>x.id===p.id),run=sim.runs.get(p.id),l=C.LANDMARKS.find(x=>x.id===run.goal);return'<article class="card"><div class="card-header"><span class="avatar" style="background:'+p.color+'44">'+p.name[0]+'</span><div><h3>'+p.name+'</h3><small>'+p.role+' · '+(run.inside?'At home':l.short)+'</small></div></div><p>'+esc(p.project)+'</p>'+button('Meet '+p.name,'select-resident','data-id="'+p.id+'"')+'</article>';}).join('');html+='<div class="notice">The small turquoise helper near the exchange is a looping service-agent visualization, not another resident.</div>';}
 else if(panel==='chronicle'){ui.title.textContent='Your small chronicle';html='<p class="intro">Your notes, discoveries and encounters live in this browser, not in a cloud account. Export a backup to carry them elsewhere.</p><div class="row">'+button('Export world JSON','export')+button('Import world JSON','import')+'</div><div class="section-label">Leave a note</div><textarea id="note-text" maxlength="1200" aria-label="Your local notebook entry" placeholder="Something you want to remember about this place…"></textarea><div class="row" style="margin-top:9px">'+button('Keep this note','note')+'<small class="muted">'+s.notes.length+' / 20 notes</small></div>';if(s.notes.length)html+='<div class="section-label">Notebook</div>'+s.notes.slice().reverse().map(n=>'<article class="card"><small class="muted">DAY '+n.day+'</small><div class="note">'+esc(n.text)+'</div></article>').join('');html+='<div class="section-label">Things that actually happened here</div>'+(s.journal.length?s.journal.slice().reverse().slice(0,50).map(j=>'<div class="journal-entry"><small>DAY '+j.day+' · '+formatHour(j.hour)+' · '+esc(j.kind)+'</small>'+esc(j.text)+'</div>').join(''):'<p class="intro">The page is still open. Go somewhere.</p>');}
 else if(panel==='settings'){ui.title.textContent='Light & atmosphere';html='<p class="intro">Shape this local evening. Changing the clock changes the residents’ schedules. Pause stops simulation—not just animation.</p><div class="setting"><label for="time-slider">Time of day <span id="slider-hour">'+formatHour(s.hour)+'</span></label><input id="time-slider" type="range" min="0" max="23.9" step=".1" value="'+s.hour+'"></div><div class="row">'+button('Morning','time','data-hour="9"')+button('Golden hour','time','data-hour="17.2"')+button('Night','time','data-hour="21.5"')+'</div><div class="row"><button data-action="open-visitor">Visitor appearance</button><button data-action="open-retreat">My retreat</button></div><div class="section-label">Weather</div><div class="row">'+button('Clear','weather','data-weather="clear" aria-pressed="'+(s.weather==='clear')+'"')+button('Rain','weather','data-weather="rain" aria-pressed="'+(s.weather==='rain')+'"')+'</div><div class="divider"></div><div class="setting"><label for="quality">Graphics</label><select id="quality"><option value="low" '+(s.settings.quality==='low'?'selected':'')+'>Low · no reflection/shadow pass</option><option value="balanced" '+(s.settings.quality==='balanced'?'selected':'')+'>Balanced · water reflections + shadows</option><option value="high" '+(s.settings.quality==='high'?'selected':'')+'>High · higher render resolution</option></select></div>'+[['timeFlow','Let the hours pass'],['labels','Place and inhabitant labels'],['reducedMotion','Reduced environmental motion'],['cameraCutaway','Cut away scenery hiding your character']].map(([k,label])=>'<div class="setting check"><label for="setting-'+k+'">'+label+'</label><input id="setting-'+k+'" data-setting="'+k+'" type="checkbox" '+(s.settings[k]?'checked':'')+'></div>').join('')+'<div class="row">'+button(sim.paused?'Resume time':'Pause time','pause')+button('Capture a photo','capture')+button('Hide interface','photo')+'</div><div class="divider"></div><p class="intro" id="help-text"><kbd>WASD / arrows</kbd> walk · <kbd>E</kbd> interact / leave<br><kbd>C</kbd> character · <kbd>I</kbd> inventory · <kbd>K</kbd> craft<br><kbd>J</kbd> journal · <kbd>Tab</kbd> target · <kbd>1</kbd> autoattack<br><kbd>2–6</kbd> skills · <kbd>Space</kbd> dodge<br><kbd>R</kbd> follow camera · <kbd>[ ]</kbd> rotate · <kbd>M</kbd> map<br><kbd>P</kbd> pause · <kbd>H</kbd> photo mode · <kbd>Escape</kbd> close / leave<br>On touch: tap to walk, drag to orbit, pinch to zoom.</p><div class="notice">All art and sound are procedural. Rendering and simulation run on your device. No assets, accounts, analytics or AI APIs are fetched.</div><div class="divider"></div>'+button('Start a fresh local world','reset','class="danger wide"')+'<p class="legal">This is a local exploration prototype. It does not contain a sentient resident, connect to Luna2, or implement multiplayer. Simulated routines are not evidence of inner experience.</p>';}
 ui.body.innerHTML=html;}
function selectResident(id){selected=id;if(panel!=='inhabitants'){panel=null;openPanel('inhabitants');}else renderPanel();}
ui.body.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;if(arsenal?.action(b)||adventure?.action(b)||sandbox?.action(b)||experience?.action(b))return;let id=b.dataset.id;switch(b.dataset.action){case'open-visitor':openPanel('visitor');break;case'open-retreat':openPanel('retreat');break;case'walk':navigate(id);closePanel();break;case'place-action':action(id);break;case'select-resident':selectResident(id);break;case'talk':{let r=command('talk',{id});if(r.ok){let slot=$('#dialogue-slot');if(slot)slot.innerHTML='<div class="quote">“'+esc(r.text)+'”</div><small class="muted">Authored local dialogue · no model request</small>';}break;}case'follow':follow=follow===id?null:id;camera.overview=false;camera.half=innerWidth<650?17:14;toast(follow?'Following '+C.PROFILES.find(p=>p.id===id).name+'. Movement is still yours.':'Camera returned to your visitor.');renderPanel();break;case'resident-walk':navigate(sim.runs.get(id).goal);closePanel();break;case'plant':command('plant');break;case'note':{let r=command('note',{text:$('#note-text').value});if(r.ok)renderPanel();break;}case'export':exportWorld();break;case'import':$('#import-file').click();break;case'time':sim.setTime(+b.dataset.hour);renderPanel();save();break;case'weather':sim.state.weather=b.dataset.weather;renderPanel();save();break;case'pause':experience?.stop();sim.paused=!sim.paused;renderPanel();toast(sim.paused?'The local world is paused.':'The local world is moving again.');break;case'photo':closePanel();togglePhoto();break;case'capture':capture();break;case'reset':if(confirm('Start a new local world? Export your current world first to keep your notes and flowers.')){preserveExisting=false;applyWorld(C.fresh());save();toast('A fresh page.');}break;}});
ui.body.addEventListener('input',e=>{if(e.target.id==='time-slider'){sim.setTime(+e.target.value);$('#slider-hour').textContent=formatHour(sim.state.hour);}});ui.body.addEventListener('change',e=>{experience?.changed(e);if(e.target.id==='quality'){sim.state.settings.quality=e.target.value;if(engine)engine.quality=e.target.value;resize();save();}if(e.target.dataset.setting){sim.state.settings[e.target.dataset.setting]=e.target.checked;if(e.target.dataset.setting==='reducedMotion'){document.body.classList.toggle('reduced',e.target.checked);if(engine)engine.reducedMotion=e.target.checked;}save();}if(e.target.id==='time-slider')save();});
function download(data,name,type){let url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportWorld(){download(JSON.stringify(sim.snapshot(),null,2),'Firstlight-Valley-day-'+sim.state.day+'.json','application/json');toast('World exported. Keep the JSON with your HTML.');}
function applyWorld(state){rpg?.reset();adventure?.reset();sandbox?.endBuild();sandbox?.stopAuto();experience?.stop();if(experience){experience.scoreUndo=[];experience.scoreRedo=[];experience.selectedSlot='nw';}if(experience?.dialog.open)experience.close();audio.disable();sim=new C.Simulation(state);scene=Symbol('rebuild');switchScene();selected=null;follow=null;closePanel();document.body.classList.toggle('reduced',sim.state.settings.reducedMotion);if(engine)engine.quality=sim.state.settings.quality;resize();sandbox?.reset();}
$('#import-file').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw new Error('Save exceeds the 1 MB import limit.');let s=C.validate(JSON.parse(await f.text()));if(!confirm('Replace this local world with the selected save? Export first to keep the current one.'))return;preserveExisting=false;applyWorld(s);save();toast('World restored. Sound remains off until you enable it.');}catch(err){toast('Import refused: '+err.message);}finally{e.target.value='';}});
function capture(){if(!engine){toast('Photo capture requires the 3D renderer; JSON export still works.');return;}try{art.update(sim,elapsed,target);engine.render(elapsed,sim.state.hour,sim.state.weather==='rain');ui.canvas.toBlob(blob=>{if(blob){download(blob,'Firstlight-Valley.png','image/png');toast('Your view captured as a PNG.');}else toast('The browser could not capture that frame.');},'image/png');}catch(e){toast('Photo unavailable: '+e.message);}}
function togglePhoto(){document.body.classList.toggle('photo-mode');if(document.body.classList.contains('photo-mode'))toast('Press H to return.');}
// Web Audio: one quiet soundscape and one original pentatonic motif; opt-in only.
const audio={ctx:null,master:null,enabled:false,nodes:[],lastChirp:0,enable(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=0;this.master.connect(this.ctx.destination);let len=this.ctx.sampleRate*3,b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0),r=C.rng(73);for(let i=0;i<len;i++)d[i]=(r()-.5)*.24;let src=this.ctx.createBufferSource();src.buffer=b;src.loop=true;let filt=this.ctx.createBiquadFilter();filt.type='lowpass';filt.frequency.value=450;src.connect(filt).connect(this.master);src.start();this.nodes.push(src);for(let f of[130.81,196,261.63]){let o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.013;o.connect(g).connect(this.master);o.start();this.nodes.push(o);}}this.ctx.resume().catch(()=>{});this.master.gain.setTargetAtTime(.55,this.ctx.currentTime,.3);this.enabled=true;this.paint();return true;}catch(e){this.enabled=false;toast('Audio unavailable in this browser.');return false;}},disable(){experience?.stop();if(this.ctx&&this.master)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.1);this.enabled=false;this.paint();},paint(){$('#sound').setAttribute('aria-pressed',String(this.enabled));$('#sound').setAttribute('aria-label',this.enabled?'Disable ambient sound':'Enable ambient sound');$('#sound').textContent=this.enabled?'♪':'♫';},toggle(){this.enabled?this.disable():this.enable();},note(freq,start,duration,level=.06){let c=this.ctx;if(!c)return;let o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(level,start+.025);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g).connect(this.master);o.start(start);o.stop(start+duration+.05);o.onended=()=>{o.disconnect();g.disconnect();};},melody(){if(!this.enabled)return;let t=this.ctx.currentTime+.1;[0,7,12,9,7,4,2,4,7,12,9,0].forEach((n,i)=>this.note(261.63*Math.pow(2,n/12),t+i*.37,1.3,.055));},tick(t){if(!this.enabled||t-this.lastChirp<8||sim.state.hour>20||sim.state.hour<6)return;this.lastChirp=t;let now=this.ctx.currentTime;this.note(1700+Math.sin(t)*200,now,.12,.012);this.note(2200,now+.17,.18,.011);}};
experience=new RealmExperience.Experience({sim:()=>sim,command,save,saved:()=>saveState==='saved',toast,download,closePanel,navigate,action,renderPanel,panel:()=>panel,audio:()=>audio,clearKeys:()=>keys.clear(),redrawRoom:()=>{if(sim.room==='retreat'&&art){art.makeRetreat(sim.state.retreat);labelsRebuild();}}});
$('#now-playing').onclick=()=>experience.open();
function walkSandbox(x,z){if(RealmAdventure.combatScene(sim)){toast('Use the southern lantern exit first.');return false;}adventure?.stopAuto();camera.tour=false;if(sim.room){sim.leave();switchScene();}let result=sim.moveTo(x,z);if(result.ok){target={x,z};camera.overview=false;camera.half=17;follow=null;}else toast(result.error);return result.ok;}
sandbox=new RealmSandboxUI.SandboxUI({sim:()=>sim,sequence:{n:0},time:()=>elapsed,save,toast,openPanel,closePanel,renderPanel,panel:()=>panel,walk:walkSandbox});
function walkAdventure(x,z){camera.tour=false;follow=null;camera.overview=false;camera.half=sim.room==='mine'?12:17;let r=sim.moveTo(x,z);if(r.ok)target={x,z};else toast(r.error);return r.ok;}
adventure=new RealmAdventureUI.AdventureUI({sim:()=>sim,save,toast,openPanel,closePanel,renderPanel,panel:()=>panel,navigate,walk:walkSandbox,walkLocal:walkAdventure,changed:switchScene,endBuild:()=>sandbox.endBuild(),clearKeys:()=>keys.clear(),audio:()=>audio,project:(x,y,z)=>engine?.project(x,y,z),direction:()=>{let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);return dx||dz?{dx:dx*Math.cos(camera.yaw)+dz*Math.sin(camera.yaw),dz:-dx*Math.sin(camera.yaw)+dz*Math.cos(camera.yaw)}:{dx:Math.sin(sim.state.player.yaw),dz:Math.cos(sim.state.player.yaw)};}});


arsenal=new RealmArsenalUI.ArsenalUI({sim:()=>sim,adventure:()=>adventure,openPanel,closePanel,renderPanel,panel:()=>panel,walk:walkAdventure,endBuild:()=>{sandbox?.endBuild();sandbox?.stopAuto();keys.clear();}});

rpg=new RealmRPGUI.RPGUI({sim:()=>sim,adventure:()=>adventure,closePanel,openPanel,endBuild:()=>{sandbox.endBuild();sandbox.stopAuto();},clearKeys:()=>keys.clear(),focusWorld:()=>ui.canvas.focus({preventScroll:true}),toast,save,exportWorld,panel:()=>panel,camera:cameraPreset,rotate:a=>{camera.yaw+=a;camera.tour=false;},direction:()=>adventure.api.direction(),music:()=>experience.open(),gather:id=>sandbox.seek(id),walkLocal:walkAdventure,audio:()=>audio,project:(x,y,z)=>engine?.project(x,y,z)});
// Input distinguishes clicks from drags, with two-finger zoom on touch screens.
let pointers=new Map(),gesture=null,keys=new Set();function zoom(k){camera.tour=false;camera.half=C.clamp?C.clamp(camera.half*k,6,52):Math.max(6,Math.min(52,camera.half*k));camera.overview=false;}
function pointerDown(e){e.currentTarget.focus({preventScroll:true});camera.tour=false;if(e.button!==0&&e.pointerType!=='touch')return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)gesture={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,pinch:false};else if(pointers.size===2){let p=[...pointers.values()];gesture.pinch=true;gesture.moved=true;gesture.distance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);}}
function pointerMove(e){if(sandbox?.build&&engine){sandbox.cursor(engine.groundAt(e.clientX,e.clientY,1.3));}if(!pointers.has(e.pointerId)||!gesture)return;let before=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){let p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(gesture.distance>1&&d>1)zoom(gesture.distance/d);gesture.distance=d;return;}let distance=Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y);if(distance>6)gesture.moved=true;if(gesture.moved&&!gesture.pinch){camera.yaw-=(e.clientX-before.x)*.007;camera.elevation=Math.max(.39,Math.min(1.2,camera.elevation+(e.clientY-before.y)*.004));}}
function pointerUp(e){if(!pointers.has(e.pointerId)||!gesture)return;let click=!gesture.moved&&!gesture.pinch;pointers.delete(e.pointerId);if(click){let p=engine?engine.groundAt(e.clientX,e.clientY,sim.room?1.58:1.3):mapToWorld(e.clientX,e.clientY);if(adventure?.worldClick(p)||sandbox?.worldClick(p,e.pointerType==='touch')){if(!pointers.size)gesture=null;return;}let r=sim.moveTo(p.x,p.z);if(r.ok){target=p;follow=null;camera.overview=false;}else toast('That point is outside the walkable ground. Choose a path or use Explore.');}if(!pointers.size)gesture=null;}
for(let canvas of[ui.canvas,ui.map]){canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(e.deltaY*.001));},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());}
window.addEventListener('keydown',e=>{
 if(document.querySelector('dialog[open]'))return;
 if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;
 const k=e.key.toLowerCase();
 if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){
  if(!panel){e.preventDefault();keys.add(k);}return;
 }
 if(e.repeat){if(k==='tab'||/^[1-6]$/.test(k)||k===' ')e.preventDefault();return;}
 if(rpg?.key(e)){e.preventDefault();return;}
 if(adventure?.key(k)||sandbox?.key(k)){e.preventDefault();return;}
 if(k==='e'){e.preventDefault();interact();}
 if(k==='v'){cameraPreset(camera.overview?'follow':'wide');}
 if(k==='m')audio.toggle();
 if(k==='p'){experience?.stop();RealmCombat.stop(sim);sim.paused=!sim.paused;toast(sim.paused?'Simulation paused.':'Simulation resumed.');}
 if(k==='h')togglePhoto();
 if(k==='escape'){if(document.body.classList.contains('photo-mode'))togglePhoto();else if(panel)closePanel();else if(sim.room){sim.leave();switchScene();}}
});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();RealmCombat.stop(sim);adventure?.stopAuto();}});
window.addEventListener('blur',()=>{keys.clear();RealmCombat.stop(sim);adventure?.stopAuto();});
for(let el of document.querySelectorAll('[data-panel]'))el.addEventListener('click',()=>openPanel(el.dataset.panel));$('#settings').onclick=()=>openPanel('settings');$('#close-panel').onclick=closePanel;$('#sound').onclick=()=>audio.toggle();$('#tour').onclick=()=>{if(sim.room){toast('The cinematic tour begins outside. Leave this room first.');return;}camera.tour=!camera.tour;camera.tourTime=0;toast(camera.tour?'A slow camera tour. Click, drag or walk to take back the view.':'Tour stopped.');};$('#overview').onclick=()=>{camera.tour=false;camera.overview=!camera.overview;follow=null;if(camera.overview)resize();};$('#interact').onclick=interact;$('#context').onclick=()=>{if(rpg?.crossing.context()?.startsWith('M · '))rpg.open('atlas');else interact();};$('#photo').onclick=()=>{openPanel('settings');};$('#photo-exit').onclick=togglePhoto;$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){toast('Fullscreen is not available in this preview. Open the saved HTML in a full browser.');}};
function formatHour(h){let m=Math.floor(h*60);return String(Math.floor(m/60)%24).padStart(2,'0')+':'+String(m%60).padStart(2,'0');}
let labelNodes=[];function labelsRebuild(){let c=$('#labels');c.replaceChildren();labelNodes=[];if(!engine)return;if(!sim.room){for(let l of C.LANDMARKS){let e=document.createElement('span');e.className='world-label';e.textContent=l.short;c.appendChild(e);labelNodes.push({e,l});}}for(let p of C.PROFILES){let e=document.createElement('span');e.className='world-label resident';e.textContent=p.name;c.appendChild(e);labelNodes.push({e,id:p.id});}}
function updateLabels(){if(!engine)return;$('#labels').style.display=sim.state.settings.labels?'block':'none';for(let n of labelNodes){let p,show=true;if(n.l)p=engine.project(n.l.x,n.l.kind==='interior'?5.8:2.4,n.l.z-1);else{let r=sim.state.residents.find(r=>r.id===n.id),run=sim.runs.get(n.id);if(sim.room){let i=C.PROFILES.findIndex(p=>p.id===n.id),pos=[[-3.1,1.1],[3.2,1.1],[2,3.2]][i];if(sim.room==='home'&&run.inside)p=engine.project(pos[0],3.45,pos[1]);else if((sim.room==='atelier'&&n.id==='ilan'&&run.goal==='atelier')||(sim.room==='observatory'&&n.id==='mara'&&run.goal==='observatory'))p=engine.project(2.5,3.45,1.1);else show=false;}else{p=engine.project(r.x,3.25,r.z);show=!run.inside;}}if(!p||!show||!p.visible){n.e.style.display='none';continue;}n.e.style.display='flex';n.e.style.left=p.x+'px';n.e.style.top=p.y+'px';}}
function mapDraw(canvas,full=false){if(sim.room==='crossing')return RealmCrossingUI.mapCanvas(canvas,sim,full);if(sim.room==='range')return mapRange(canvas,full);if(sim.room==='road'){mapRoad(canvas,full);return;}if(sim.room==='mine'){mapMine(canvas,full);return;}let g=canvas.getContext('2d');if(!g)return;let w=canvas.width,h=canvas.height,scale=sim.room?(full?Math.min(w,h)/17:w/16):(full?Math.min(w,h)/108:w/108),centerX=sim.room?w/2:w/2-10*scale,centerY=full?h*.53:h*.48;g.clearRect(0,0,w,h);g.fillStyle=full?'#233f49':'#19363c';g.fillRect(0,0,w,h);let tx=x=>centerX+x*scale,tz=z=>centerY+(z+(sim.room?0:10))*scale;g.fillStyle='#647e66';g.beginPath();if(sim.room){g.rect(tx(-5.5),tz(-4.5),11*scale,9*scale);}else{for(let i=0;i<=100;i++){let a=i/100*Math.PI*2,r=C.landRadius(Math.cos(a),Math.sin(a));let x=tx(Math.cos(a)*r),z=tz(Math.sin(a)*r);i?g.lineTo(x,z):g.moveTo(x,z);} }g.fill();if(!sim.room){g.beginPath();g.ellipse(tx(37),tz(2),12.1*scale,11.6*scale,0,0,Math.PI*2);g.fill();g.fillRect(tx(20),tz(.3),9*scale,3.4*scale);g.beginPath();g.ellipse(tx(0),tz(-40),11.4*scale,12.4*scale,0,0,Math.PI*2);g.fill();if(sim.state.sandbox.bridge)g.fillRect(tx(-1.4),tz(-30.6),2.8*scale,8*scale);}if(sim.room){g.fillStyle='#9c875e';g.fillRect(tx(-5.3),tz(-4.2),10.6*scale,8.4*scale);g.fillStyle='#665545';if(sim.room==='retreat'){for(let i of sim.state.retreat.items){let o=X.obstacles({...sim.state.retreat,items:[i]})[0];if(o)g.fillRect(tx(o.x-o.w/2),tz(o.z-o.d/2),o.w*scale,o.d*scale);}}else g.fillRect(tx(-1.4),tz(-2.45),2.8*scale,1.9*scale);}else{g.strokeStyle='#b3b69a80';g.lineWidth=full?6:2;for(let l of C.LANDMARKS){g.beginPath();g.moveTo(tx(l.x>25?28:0),tz(l.x>25?2:3));g.lineTo(tx(l.x),tz(l.z));g.stroke();}g.fillStyle='#ad9d77';g.fillRect(tx(-1.5),tz(20),3*scale,9*scale);g.fillStyle='#3b594c';for(let o of C.OBSTACLES){if(o.r){g.beginPath();g.arc(tx(o.x),tz(o.z),o.r*scale,0,Math.PI*2);g.fill();}else g.fillRect(tx(o.x-o.w/2),tz(o.z-o.d/2),o.w*scale,o.d*scale);}for(let l of C.LANDMARKS){g.fillStyle=sim.state.visited.includes(l.id)?'#ddc489':'#a9bba4';g.beginPath();g.arc(tx(l.x),tz(l.z),full?5:2.8,0,Math.PI*2);g.fill();if(full){g.fillStyle='#e9e9cf';g.font=Math.max(11,w/95)+'px system-ui';g.textAlign='center';g.fillText(l.short,tx(l.x),tz(l.z)-12);}}}
 if(!sim.room){for(let n of RealmSandbox.NODES){g.fillStyle=RealmSandbox.ITEMS[n.kind].color;g.fillRect(tx(n.x)-2,tz(n.z)-2,4,4);}for(let p of sim.state.sandbox.placed){let w=RealmSandbox.worldCell(p.gx,p.gz);g.fillStyle=RealmSandbox.ITEMS[p.kind].color;g.fillRect(tx(w.x)-2,tz(w.z)-2,4,4);}}
 if(!sim.room)for(let r of sim.state.residents){g.fillStyle=C.PROFILES.find(p=>p.id===r.id).color;g.beginPath();g.arc(tx(r.x),tz(r.z),full?6:3.5,0,Math.PI*2);g.fill();}let p=sim.state.player;g.fillStyle='#f9df9b';g.beginPath();g.arc(tx(p.x),tz(p.z),full?7:4.5,0,Math.PI*2);g.fill();g.strokeStyle='#faf1c6';g.lineWidth=1;g.beginPath();g.arc(tx(p.x),tz(p.z),full?11:7,0,Math.PI*2);g.stroke();}
function mapRange(canvas,full){const g=canvas.getContext('2d');if(!g)return;const w=canvas.width,h=canvas.height,sc=(full?Math.min(w,h):w)/36,tx=x=>w/2+x*sc,tz=z=>h/2+z*sc;g.fillStyle='#28483e';g.fillRect(0,0,w,h);g.fillStyle='#b4b493';g.fillRect(tx(-14),tz(-13),28*sc,26*sc);for(const o of RealmArsenal.RANGE.pillars){g.fillStyle='#6d765e';g.beginPath();g.arc(tx(o.x),tz(o.z),o.r*sc,0,Math.PI*2);g.fill();}for(const e of RealmAdventure.runtime(sim).enemies){g.fillStyle='#c68764';g.beginPath();g.arc(tx(e.x),tz(e.z),.7*sc,0,Math.PI*2);g.fill();if(full){g.fillStyle='#24382e';g.font='13px sans-serif';g.textAlign='center';g.fillText(e.name,tx(e.x),tz(e.z)-12);}}for(const q of RealmArsenal.runtime(sim).arrows){g.strokeStyle='#d4857e';g.beginPath();g.moveTo(tx(q.x),tz(q.z));g.lineTo(tx(q.x-q.dx*.7),tz(q.z-q.dz*.7));g.stroke();}const p=sim.state.player;g.fillStyle='#fff8d2';g.beginPath();g.arc(tx(p.x),tz(p.z),5,0,Math.PI*2);g.fill();}
function mapRoad(canvas,full){
 const g=canvas.getContext('2d');if(!g)return;const w=canvas.width,h=canvas.height,sc=(full?Math.min(w,h):w)/65,ox=w/2,oy=h/2+3*sc,tx=x=>ox+x*sc,tz=z=>oy+z*sc;g.fillStyle='#214c55';g.fillRect(0,0,w,h);
 for(let x=-18;x<=18;x+=.8)for(let z=-29;z<=23;z+=.8)if(RealmRoad.walkable(x,z,0)){g.fillStyle='#849a70';g.fillRect(tx(x),tz(z),.83*sc,.83*sc);}
 const dot=(p,color,size)=>{g.fillStyle=color;g.beginPath();g.arc(tx(p.x),tz(p.z),size,0,Math.PI*2);g.fill();};for(const p of[RealmRoad.ENTRY,RealmRoad.MERCHANT,RealmRoad.BEACON])dot(p,'#e8cca0',4);for(const e of RealmAdventure.runtime(sim).enemies)if(e.hp>0&&!e.hidden)dot(e,'#d69b9b',4);for(const c of RealmRoad.CACHES)if(sim.state.adventure.road.revealed.includes(c.id)&&!sim.state.adventure.road.claimed.includes(c.id))dot(c,'#dfdba8',4);const f=RealmAdventure.runtime(sim).companion;if(sim.state.adventure.companion.bonded&&f.room===sim.room)dot(f,'#d6a677',3);dot(sim.state.player,'#fff0bd',5);
}
function mapMine(canvas,full){let g=canvas.getContext('2d');if(!g)return;let w=canvas.width,h=canvas.height,scale=(full?Math.min(w,h):w)/36,ox=w/2,oy=h/2;g.fillStyle='#162d37';g.fillRect(0,0,w,h);let a=sim.state.adventure;for(let x=-7;x<=7;x++)for(let z=-7;z<=7;z++){g.fillStyle=RealmAdventure.isFloor(a,x,z)?'#788b79':RealmAdventure.mineral(x,z)?'#9a8068':'#334e57';g.fillRect(ox+(x*2-1)*scale,oy+(z*2-1)*scale,2*scale-1,2*scale-1);}for(let e of RealmAdventure.runtime(sim).enemies){if(e.hp<=0)continue;g.fillStyle='#dba59e';g.beginPath();g.arc(ox+e.x*scale,oy+e.z*scale,full?5:3,0,Math.PI*2);g.fill();}g.fillStyle='#f4d9a3';g.beginPath();g.arc(ox+sim.state.player.x*scale,oy+sim.state.player.z*scale,full?6:4,0,Math.PI*2);g.fill();}
function mapToWorld(x,y){if(sim.room==='crossing'){let sc=Math.min(innerWidth,innerHeight)/68;return{x:(x-innerWidth/2)/sc,z:(y-innerHeight/2)/sc-1};}if(sim.room==='range'){let sc=Math.min(innerWidth,innerHeight)/36;return{x:(x-innerWidth/2)/sc,z:(y-innerHeight/2)/sc};}if(sim.room==='road'){let sc=Math.min(innerWidth,innerHeight)/65;return{x:(x-innerWidth/2)/sc,z:(y-innerHeight/2)/sc-3};}if(sim.room==='mine'){let sc=Math.min(innerWidth,innerHeight)/36;return{x:(x-innerWidth/2)/sc,z:(y-innerHeight/2)/sc};}let w=innerWidth,h=innerHeight,sc=Math.min(w,h)/(sim.room?17:108);return{x:(x-w/2)/sc+(sim.room?0:10),z:(y-h*.53)/sc-(sim.room?0:10)};}$('#minimap').onclick=()=>rpg.open('atlas');

function refreshUI(){let s=sim.state;$('#tour').setAttribute('aria-pressed',String(!!camera.tour));$('#time-display').textContent=formatHour(s.hour);$('#day-display').textContent='DAY '+String(s.day).padStart(2,'0')+' · '+(sim.paused?'PAUSED':s.weather==='rain'?'RAIN':s.hour>20||s.hour<6?'NIGHT':s.hour>16?'GOLDEN HOUR':'DAYLIGHT');$('#fps').textContent=engine?Math.round(fps)+' FPS · '+s.settings.quality.toUpperCase():'MAP VIEW';$('#discovery').textContent=s.visited.length+' / '+C.LANDMARKS.length+' PLACES DISCOVERED';let l=sim.room==='crossing'?{short:'Bellweather Crossing',description:'A village to meet. A silence to break. A road home.'}:sim.room==='range'?{short:'The Archery Court',description:'Take a breath. Find your distance. Let the arrow travel.'}:sim.room==='road'?{short:'The Sunward Road',description:'A traveller to help. A trail to follow. A light to bring home.'}:sim.room==='mine'?{short:'The Rootbound Underways',description:'Copper in the walls. A heartbeat beneath the roots.'}:sim.room?C.LANDMARKS.find(l=>l.id===sim.room):closest(),sbContext=rpg?.crossing.context()||(RealmBeacon.near(sim)&&sim.state.adventure.road.beaconLit?(RealmBeacon.runtime(sim).phase==='assault'?'Repair ward · E · 20 stamina':'The envoy at the beacon · E'):null)||adventure?.context()||sandbox?.context();$('#place-name').textContent=sim.room?l.short:sim.state.player.z<-29?'Wildwood Reach':'Firstlight Valley';$('#place-kicker').textContent=sim.room==='crossing'?'THE BELL ROAD · CHAPTER IV':sim.room==='range'?'THE PRACTICE COURT · A NEW DISCIPLINE':sim.room==='road'?(s.adventure.beacon.introduced?'THE BEACON ANSWERS · CHAPTER III':'BEYOND THE VALLEY · CHAPTER II'):sim.room==='mine'?'BENEATH WILDWOOD · CHAPTER I':sim.room?'A PRIVATE PLACE · LOCAL INTERIOR':'THE REALM · FIRST INHABITED DISTRICT';$('#place-description').textContent=sim.room?l.description:'Gather. Make. Grow. A new shore to call your own.';$('#context').style.display=(l||sbContext)&&!sandbox?.build?'flex':'none';let contextKey=sbContext?.match(/^([A-Z0-9]+) · /)?.[1]||'E';$('#context kbd').textContent=contextKey;$('#context-text').textContent=RealmAdventure.combatScene(sim)?sbContext?.replace(/^([A-Z0-9]+) · /,''):sim.room?'Return to the valley':sbContext|| (l?l.action:'');mapDraw($('#minimap'));renderStatus();}
function frame(now){let dt=lastFrame?Math.min((now-lastFrame)/1000,.1):.016;lastFrame=now;frames++;if(now-fpsStart>1500){fps=frames*1000/(now-fpsStart);frames=0;fpsStart=now;}if(!document.hidden){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if((dx||dz)&&!sim.paused){sandbox?.stopAuto();adventure?.stopAuto();camera.tour=false;sim.manual(dx*Math.cos(camera.yaw)+dz*Math.sin(camera.yaw),-dx*Math.sin(camera.yaw)+dz*Math.cos(camera.yaw),dt);camera.overview=false;follow=null;target=null;sim.walking=true;}sim.tick(dt);if((dx||dz)&&!sim.paused)sim.walking=true;elapsed+=sim.paused?0:dt;if(!sim.playerPath.length)target=null;switchScene();updateCamera(dt);experience?.tick();sandbox?.tick();adventure?.tick();arsenal?.tick();rpg?.tick();if(engine){if(sim.room==='retreat'&&art.layoutRevision!==sim.state.retreat.revision)art.makeRetreat(sim.state.retreat);engine.reducedMotion=sim.state.settings.reducedMotion;art.update(sim,elapsed,target);engine.render(elapsed,sim.state.hour,sim.state.weather==='rain');updateLabels();}else mapDraw(ui.map,true);audio.tick(elapsed);if(now-lastUi>350){refreshUI();lastUi=now;}if(elapsed-lastSave>6){save();lastSave=elapsed;}}if(!G_CAPTURE)requestAnimationFrame(frame);}
// Keep a read-only-ish diagnostics surface for inspection; this local prototype is not a security boundary.
const G_CAPTURE=!!window.__ETERNITIES_CAPTURE_MODE;
window.Realm={get state(){return sim.snapshot();},get diagnostics(){let g=engine?.gl,dbg=g?.getExtension('WEBGL_debug_renderer_info');return{version:'10.0.0',mode:engine?'webgl2':'map',scene:sim.room||'valley',networkDependencies:0,liveAI:false,multiplayer:false,adventure:{tactics:JSON.parse(JSON.stringify(RealmCombat.runtime(sim))),beacon:JSON.parse(JSON.stringify(RealmBeacon.runtime(sim))),crossing:JSON.parse(JSON.stringify(RealmCrossing.runtime(sim))),player:{...sim.state.player},paused:sim.paused,intent:adventure?.intent||null,stats:RealmAdventure.stats(sim.state.adventure),weapon:RealmArsenal.weapon(sim.state.adventure),arrows:RealmArsenal.runtime(sim).arrows.map(a=>({...a})),range:{...RealmArsenal.runtime(sim).range},enemies:RealmAdventure.runtime(sim).enemies.map(e=>({id:e.id,x:e.x,z:e.z,hp:e.hp,maxHP:e.maxHP,hidden:!!e.hidden,eventEnemy:!!e.eventEnemy,kind:e.kind,ringMode:e.ringMode,custom:e.custom,mode:e.mode,timer:e.timer,aim:e.aim})),companion:{...RealmAdventure.runtime(sim).companion}},sandbox:{bridge:sim.state.sandbox.bridge,objects:sim.state.sandbox.placed.length,elapsed:sim.state.sandbox.elapsed,autoGather:sandbox?.auto||null,buildMode:sandbox?.build||null},saveState,fps,errors:errors.slice(),camera:{...camera},metrics:engine?.metrics||null,reflection:engine?.reflectionInfo||null,cutaway:{enabled:!!engine?.cutaway,focus:engine?.cutawayFocus||null},renderer:dbg?g.getParameter(dbg.UNMASKED_RENDERER_WEBGL):null,music:{playing:experience?.playing||false,scoreRevision:sim.state.scoreRevision,playingRevision:experience?.playingRevision,step:experience?.step},gathering:sim.gathering?{...sim.gathering}:null,layoutRevision:sim.state.retreat.revision,audio:{enabled:audio.enabled,state:audio.ctx?.state||'not-created'}};},navigate,export:()=>JSON.stringify(sim.snapshot(),null,2),project:(x,y,z)=>engine?.project(x,y,z)};
if(window.__ETERNITIES_TEST_MODE||location.search.includes('test'))window.Realm.test={step(seconds){let p=sim.paused;sim.paused=false;for(let t=0;t<seconds;t+=.05){sim.tick(.05);adventure?.tick();arsenal?.tick();rpg?.tick();}sim.paused=p;elapsed+=seconds;switchScene();refreshUI();},setTime:h=>sim.setTime(h),enter:id=>{let r=sim.enter(id);switchScene();return r;},leave:()=>{let r=sim.leave();switchScene();return r;},act:(...args)=>sim.act(...args),save,replace:applyWorld,pause:v=>{sim.paused=v;},weather:v=>{sim.state.weather=v;},layout:()=>sim.state.retreat,openStudio:()=>experience.open(),openPanel,quality:v=>{sim.state.settings.quality=v;if(engine)engine.quality=v;resize();},render(){experience?.tick();sandbox?.tick();adventure?.tick();arsenal?.tick();rpg?.tick();if(engine){if(sim.room==='retreat'&&art.layoutRevision!==sim.state.retreat.revision)art.makeRetreat(sim.state.retreat);updateCamera(1);art.update(sim,elapsed,target);engine.render(elapsed,sim.state.hour,sim.state.weather==='rain');updateLabels();}else mapDraw(ui.map,true);refreshUI();},captureFrame(t,yaw){elapsed=t;if(yaw!==undefined)camera.yaw=yaw;this.render();return ui.canvas.toDataURL('image/png');},view(v){Object.assign(camera,v);updateCamera(1);},sandbox:(id,type,payload)=>sim.sandboxCommand(id,type,payload),adventure:(id,type,payload)=>{let r=sim.adventureCommand(id,type,payload);switchScene();return r;},move:(x,z)=>sim.moveTo(x,z),sandboxPanel:()=>sandbox.paint(),presentation:()=>JSON.parse(JSON.stringify(sim.presentation||{})),get path(){return sim.playerPath;}};
window.addEventListener('resize',resize);window.addEventListener('pagehide',save);ui.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback('Graphics context lost. Your local state is intact; use the map and export a backup.');toast('Graphics paused; world state preserved.');});document.body.classList.toggle('reduced',sim.state.settings.reducedMotion);labelsRebuild();resize();refreshUI();save();if(loaded.status==='migrated')toast('Your earlier world was copied into Realm 10. The original save was not changed.');setTimeout(()=>$('#loading').classList.add('hidden'),400);if(G_CAPTURE){if(window.Realm.test)window.Realm.test.render();}else requestAnimationFrame(frame);
})();
