/* Armory menu and practice HUD. Commands validate actual position and inventory. */
(function(G){'use strict';const A=G.RealmAdventure,AR=G.RealmArsenal,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,id='',disabled=false)=>'<button data-action="ar-'+action+'" data-id="'+esc(id)+'" '+(disabled?'disabled':'')+'>'+text+'</button>';
class ArsenalUI{
 constructor(api){this.api=api;$('#range-begin').onclick=()=>this.run('range-start');$('#range-stop').onclick=()=>this.run('range-stop');$('#range-menu').onclick=()=>api.openPanel('armory');}
 get sim(){return this.api.sim();} get state(){return this.sim.state.adventure;}
 run(t,p={}){if(t.startsWith('range-')){this.api.adventure().stopAuto();this.api.endBuild();}const r=this.api.adventure().run(t,p);if(this.api.panel()==='armory')this.api.renderPanel();return r;}
 key(k){if(k==='9'){this.api.openPanel('armory');return true;}return false;}
 action(b){const v=b.dataset.action;if(!v?.startsWith('ar-'))return false;const act=v.slice(3),id=b.dataset.id;
 if(act==='go')this.api.adventure().go('workshop');else if(act==='craft')this.run('arsenal-craft',{id});else if(act==='equip'){this.api.adventure().stopAuto();this.run('equip',{id});}else if(act==='socket'){const gem=$('#socket-'+id).value;this.run('socket',{weapon:id,gem:gem||null});}
 else if(act==='target'){const e=A.runtime(this.sim).enemies.find(e=>e.id===id);if(e)this.api.adventure().approach(e,'attack',id);}else if(act==='leave-route'){this.api.closePanel();this.api.walk(AR.RANGE.entry.x,AR.RANGE.entry.z);}
 else this.run(act);return true;}
 renderPanel(name){if(name!=='armory')return null;const s=this.state,st=A.stats(s),w=AR.weapon(s),r=AR.runtime(this.sim),inv=this.sim.state.sandbox.inventory;
 let html='<div class="armory-hero"><span class="overline">A DIFFERENT WAY THROUGH THE WORLD</span><h3>Bow, blade & a little light.</h3><p>Real travelling arrows. One removable gem per weapon. Choose a style, not a permanent class.</p></div><div class="adventure-stats"><span><b>'+st.attack+'</b>Attack</span><span><b>'+st.maxHP+'</b>Max health</span><span><b>'+s.ore+'</b>Copper</span><span><b>'+s.coins+'</b>Sunmarks</span></div><p class="intro">Equipped: '+esc(A.GEAR[s.equipment.weapon]?.name||'No weapon')+' · '+w.style+'<br>F '+w.primary+' · Q '+w.special+'. Arrows use 6 stamina, not inventory ammunition.</p>';
 if(!s.started)html+='<article class="card"><h3>Start at Oren’s workshop</h3><p>Take your expedition supplies, then gather materials for a bow.</p>'+button('Take expedition supplies','start')+'</article>';
 html+='<div class="row">'+button('Walk to Oren','go')+button('Enter practice court','range-enter','',!!this.sim.room)+'</div>';
 if(this.sim.room==='range')html+='<article class="card"><h3>Three bells, twice each.</h3><p>Hit all three targets twice in 30 active seconds. The right target moves. No damage, XP grind or lost items. First medal gives an amber and 5 sunmarks; repeats only improve your time.</p><p>Best: '+(s.arsenal.bestTime?s.arsenal.bestTime.toFixed(2)+'s':'Not yet completed')+'</p><div class="row">'+button('Begin round','range-start','',r.range.active)+button('End round','range-stop','',!r.range.active)+button('Walk to exit','leave-route')+'</div><div class="row">'+AR.RANGE.targets.map(t=>button(t.name,'target',t.id)).join('')+'</div>'+button('Leave through south gate','range-leave')+'</article>';
 html+='<div class="section-label">Craft at an outdoor workbench</div>';
 for(const[id,q]of Object.entries(AR.RECIPES)){const costs=[...Object.entries(q.materials).map(([k,n])=>n+' '+G.RealmSandbox.ITEMS[k].name+' ('+(inv[k]||0)+')'),...(q.ore?[q.ore+' copper']:[]),...(q.coins?[q.coins+' sunmarks']:[])];html+='<article class="card"><h3>'+q.name+'</h3><p>'+costs.join(' · ')+(q.requires?'<br>Requires the trail bow; the original is kept.':'')+'</p>'+button(q.gear&&s.owned.includes(q.gear)?'Already made':'Craft','craft',id,!!q.gear&&s.owned.includes(q.gear))+'</article>';}
 html+='<div class="section-label">Loose gems</div><div class="gem-pouch">'+Object.entries(AR.GEMS).map(([id,g])=>'<span style="--gem:'+g.css+'"><i>◆</i><b>'+s.arsenal.gems[id]+'</b>'+g.name+'</span>').join('')+'</div><p class="intro">A gem belongs to its weapon. Only the equipped weapon’s gem applies. Replacing or removing one returns it intact; it does not repair or heal you.</p>';
 for(const id of s.owned.filter(id=>A.GEAR[id]?.slot==='weapon')){const g=A.GEAR[id],gem=s.arsenal.sockets[id],on=s.equipment.weapon===id;html+='<article class="card socket-card"><div class="card-header"><h3>'+g.name+'</h3><span class="badge">'+(on?'Equipped':g.style||'blade')+'</span></div><p>'+g.desc+'</p><div class="row">'+button(on?'Equipped':'Equip','equip',id,on)+'</div><label for="socket-'+id+'">One socket · '+(gem?AR.GEMS[gem].name:'empty')+'</label><select id="socket-'+id+'"><option value="">Empty · reclaim current gem</option>'+Object.entries(AR.GEMS).map(([k,v])=>'<option value="'+k+'" '+(k===gem?'selected':'')+'>'+v.name+' · '+v.desc+'</option>').join('')+'</select>'+button('Apply socket at workbench','socket',id)+'</article>';}
 return html+'<div class="notice">The blade remains useful at close range. Bows aim where a target is at release, not where it will move. Arrows stop at walls and solid obstacles, but can cross the road’s water. No online item authority.</div>';
 }
 tick(){const sim=this.sim,s=this.state,r=AR.runtime(sim),inside=sim.room==='range',w=AR.weapon(s);document.body.classList.toggle('in-range',inside);$('#range-round').hidden=!inside;if(inside){const left=Math.max(0,30-(s.elapsed-r.range.start));$('#range-clock').textContent=r.range.active?left.toFixed(1)+'s · ARCHERY ROUND':'THE ARCHERY COURT';$('#range-progress').textContent=r.range.active?AR.RANGE.targets.map(t=>(r.range.hits[t.id]||0)+'/2').join('   ·   '):r.range.message;$('#range-begin').disabled=r.range.active||w.style!=='bow';$('#range-stop').disabled=!r.range.active;}
 const strike=$('#battle-strike'),pulse=$('#battle-pulse');strike.querySelector('small').textContent=w.style==='bow'?'Arrow · F':'Strike · F';strike.title=w.primary+' · F';pulse.querySelector('small').textContent=w.style==='bow'?'Pierce · Q':'Sweep · Q';pulse.title=w.special+' · Q';strike.disabled=s.elapsed<r.cooldowns.attack||s.stamina<w.stamina;}
}
G.RealmArsenalUI={ArsenalUI};})(globalThis);
