/* Map, contextual services and Chapter IV workspace. No UI grants rewards. */
(function(G){'use strict';const X=G.RealmCrossing,A=G.RealmAdventure,T=G.RealmCombat,C=G.RealmCore,$=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,act,id='',off=false,cls='')=>'<button data-rpg="'+act+'" data-id="'+esc(id)+'" '+(off?'disabled ':'')+'class="'+cls+'">'+text+'</button>';
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
function points(sim){if(sim.room==='crossing'){let q=X.PLACES.filter(p=>p.id!=='thicket'||sim.state.adventure.crossing.met).map(p=>({...p}));const s=sim.state.adventure.crossing;if(s.clapperRevealed&&!s.clapper)q.push({id:'clapper',name:'The lost clapper',...X.CLAPPER,kind:'clue'});if(s.repaired)q.push(...X.BELLS.map(b=>({...b,id:'bell-'+b.id,kind:'bell'})));return q;}
 if(sim.room==='road')return[{id:'road-exit',name:'Firstlight Valley',x:0,z:17,kind:'gate'},{id:'road-trader',name:'Tessa’s cart',x:-10,z:12,kind:'shop'},{id:'road-bridge',name:'River bridge',x:2,z:0,kind:'gate'},{id:'sunward',name:'Sunward Beacon',x:0,z:-24,kind:'waystone'},...(sim.state.adventure.beacon.complete?[{id:'cross-enter',name:'To Bellweather Crossing',...X.GATE,kind:'gate'}]:[])];
 if(!sim.room)return [...C.LANDMARKS.map(p=>({...p,kind:p.id==='commons'?'waystone':'place'})),...(sim.state.adventure.started?G.RealmStarter.points(sim):[])];
 return[];
}
function projection(sim,w,h){return sim.room==='crossing'?{scale:Math.min(w,h)/68,ox:w/2,oy:h/2+Math.min(w,h)/68}:sim.room==='road'?{scale:Math.min(w,h)/62,ox:w/2,oy:h/2+3*Math.min(w,h)/62}:{scale:Math.min(w/90,h/95),ox:w*.30,oy:h*.63};}
function mapCanvas(canvas,sim,full=false){const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width,h=canvas.height,{scale:s,ox,oy}=projection(sim,w,h),p=(x,z)=>[ox+x*s,oy+z*s];ctx.clearRect(0,0,w,h);ctx.fillStyle='#142d31';ctx.fillRect(0,0,w,h);
 ctx.fillStyle='#45614f';const[qx,qy]=p(-21,-30);ctx.fillRect(qx,qy,42*s,58*s);ctx.strokeStyle='#648b89';ctx.lineWidth=2.4*s;ctx.beginPath();for(let z=-30;z<=28;z++){let[x,y]=p(X.riverX(z),z);z===-30?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();
 ctx.strokeStyle='#b6ad8a';ctx.lineWidth=2*s;ctx.beginPath();for(const[x,z]of[[0,25],[0,5],[0,-18]]){let[px,py]=p(x,z);z===25?ctx.moveTo(px,py):ctx.lineTo(px,py);}ctx.stroke();ctx.strokeRect(...p(14,16.5),4*s,3*s);
 for(const b of X.BUILDINGS){let[x,y]=p(b.x-b.w/2,b.z-b.d/2);ctx.fillStyle='#a9a587';ctx.fillRect(x,y,b.w*s,b.d*s);}for(const tree of X.TREES){let[x,y]=p(tree[0],tree[1]);ctx.fillStyle=tree[3]===3?'#b49aae':'#73976d';ctx.beginPath();ctx.arc(x,y,1.3*s,0,Math.PI*2);ctx.fill();}
 for(const e of A.runtime(sim).enemies.filter(e=>e.hp>0&&!e.hidden)){let[x,y]=p(e.x,e.z);ctx.fillStyle='#d79091';ctx.beginPath();ctx.arc(x,y,Math.max(2,s*.6),0,Math.PI*2);ctx.fill();}
 for(const q of points(sim)){let[x,y]=p(q.x,q.z);ctx.fillStyle=q.kind==='waystone'?'#ecd19a':'#d8ddc5';ctx.fillRect(x-2,y-2,4,4);}
 if(sim.playerPath.length){ctx.strokeStyle='#ead1a0';ctx.lineWidth=1.6;ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(...p(sim.state.player.x,sim.state.player.z));for(const q of sim.playerPath)ctx.lineTo(...p(q.x,q.z));ctx.stroke();ctx.setLineDash([]);}
 const[x,y]=p(sim.state.player.x,sim.state.player.z);ctx.fillStyle='#fff0c3';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#142b29';ctx.stroke();ctx.fillStyle='#d3d9c4';ctx.font='12px sans-serif';ctx.fillText('N',w/2-4,14);
}
function mapSVG(sim){const w=420,h=450,{scale:s,ox,oy}=projection(sim,w,h),p=(x,z)=>[ox+x*s,oy+z*s],f=n=>Number(n).toFixed(2);let htm='<rect width="420" height="450" rx="14" fill="#163238"/>';
 if(sim.room==='crossing'){let[x,y]=p(-21,-30);htm+='<rect x="'+f(x)+'" y="'+f(y)+'" width="'+f(42*s)+'" height="'+f(58*s)+'" rx="8" fill="#415f50"/>';let d='';for(let z=-30;z<=28;z++)d+=(z===-30?'M':'L')+p(X.riverX(z),z).map(f).join(' ');htm+='<path d="'+d+'" fill="none" stroke="#729eaa" stroke-width="'+f(2.4*s)+'"/>';for(const b of X.BUILDINGS){let[x,y]=p(b.x-b.w/2,b.z-b.d/2);htm+='<rect x="'+f(x)+'" y="'+f(y)+'" width="'+f(b.w*s)+'" height="'+f(b.d*s)+'" fill="#bbb69b" stroke="#ded0ad"/>';}}
 else if(sim.room==='road'){let[x,y]=p(0,-3);htm+='<ellipse cx="'+f(x)+'" cy="'+f(y)+'" rx="'+18*s+'" ry="'+26*s+'" fill="#415f50"/>';let yy=p(0,0)[1];htm+='<path d="M '+p(-17,0).map(f).join(' ')+' Q '+p(0,1).map(f).join(' ')+' '+p(17,0).map(f).join(' ')+'" fill="none" stroke="#769caa" stroke-width="'+3.6*s+'"/>';let[xx,by]=p(0,-2.5);htm+='<rect x="'+xx+'" y="'+by+'" width="'+4*s+'" height="'+5*s+'" fill="#bcae8e"/>';}
 else if(!sim.room){for(const[x,z,r]of[[0,0,24],[37,2,12],[0,-40,12]]){let[px,py]=p(x,z);htm+='<circle cx="'+px+'" cy="'+py+'" r="'+r*s+'" fill="#446752"/>';}htm+='<path d="M '+p(20,2).join(' ')+' L '+p(29,2).join(' ')+' M '+p(0,-23).join(' ')+' L '+p(0,-29).join(' ')+'" stroke="#bbad8e" stroke-width="'+3*s+'"/>';}
 else htm+='<text x="210" y="200" text-anchor="middle" fill="#e2dac4">Interior / expedition</text><text x="210" y="224" text-anchor="middle" fill="#b5c8bf">Use its local route controls.</text>';
 if(sim.playerPath.length){let d='M '+p(sim.state.player.x,sim.state.player.z).join(' ');for(const q of sim.playerPath)d+=' L '+p(q.x,q.z).join(' ');htm+='<path d="'+d+'" stroke="#f0d49c" fill="none" stroke-width="2" stroke-dasharray="5 4"/>';}
 const poi=points(sim);for(let i=0;i<poi.length;i++){let q=poi[i],[x,y]=p(q.x,q.z);htm+='<g role="button" tabindex="0" data-rpg="cross-walk" data-id="'+q.id+'" aria-label="Walk to '+esc(q.name)+'" class="atlas-pin"><circle cx="'+f(x)+'" cy="'+f(y)+'" r="10" fill="'+(q.kind==='waystone'?'#d8ba7d':'#293f3c')+'" stroke="#d2c6a3"/><text x="'+f(x)+'" y="'+f(y+3.5)+'" text-anchor="middle" fill="'+(q.kind==='waystone'?'#263833':'#f3dfb6')+'" font-size="10">'+(i+1)+'</text><title>'+esc(q.name)+'</title></g>';}
 for(const e of A.runtime(sim).enemies.filter(e=>e.hp>0&&!e.hidden)){let[x,y]=p(e.x,e.z);htm+='<path d="M '+x+' '+(y-5)+' l 5 5 -5 5 -5 -5z" fill="#cf7d88"><title>'+esc(e.name)+'</title></path>';}
 let[x,y]=p(sim.state.player.x,sim.state.player.z);htm+='<circle cx="'+f(x)+'" cy="'+f(y)+'" r="4" fill="#fff8da" stroke="#0c2325" stroke-width="2"/><text x="210" y="19" text-anchor="middle" fill="#d9d5bc" font-size="11">NORTH</text><text x="14" y="435" fill="#c5cbb5" font-size="11">● You · ◆ Hostile · Numbered places</text>';
 return '<svg id="cross-atlas-map" viewBox="0 0 420 450" role="img" aria-label="Local map with numbered destinations">'+htm+'</svg>';
}
class CrossingUI{
 constructor(rpg){this.rpg=rpg;this.toneSerial=0;this.labelTime=-1;this.uiRoom=null;this.destination=null;
 const n=document.createElement('button');n.dataset.rpg='open';n.dataset.id='atlas';n.setAttribute('aria-label','Map · M');n.title='Map · M';n.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2V5zm6-2v16m6-14v16"/></svg><span>Map</span><kbd>M</kbd>';$('.rpg-nav').insertBefore(n,$('.rpg-nav [data-id="more"]'));
 const root=document.createElement('div');root.id='cross-place-labels';root.setAttribute('aria-hidden','true');$('#hud').append(root);
 const compass=document.createElement('div');compass.id='cross-route-hint';compass.hidden=true;$('#hud').append(compass);
 rpg.dialog.addEventListener('keydown',e=>{const target=e.target;if((e.key==='Enter'||e.key===' ')&&target.matches('.atlas-pin')){e.preventDefault();this.action(target);}if(e.key.toLowerCase()==='m'&&rpg.tab==='atlas'&&!target.matches('input,textarea,select')){e.preventDefault();rpg.close();}});
 }
 get sim(){return this.rpg.sim;}get state(){return this.rpg.state.crossing;}
 run(type,p={}){return this.rpg.run(type,p);}
 walk(id){const q=points(this.sim).find(q=>q.id===id);if(!q)return;this.rpg.close();const r=this.rpg.api.walkLocal(q.x,q.z);if(!r)return false;this.destination={...q,room:this.sim.room};this.rpg.api.toast('Walking to '+q.name+'. E interacts when you arrive.');return r;}
 action(el){const act=el.dataset.rpg,id=el.dataset.id;
 if(act==='cross-walk'){this.walk(id);return true;}
 if(act==='cross-do'){const was=this.sim.room,res=this.run(id);if(res.ok&&was!==this.sim.room){this.rpg.close();this.destination=null;}return true;}
 if(act==='cross-trade'){this.run('cross-trade',{offer:id});return true;}
 if(act==='cross-project'){this.run('cross-project',{id});return true;}
 if(act==='cross-ring'){this.run('cross-ring',{id});return true;}
 if(act==='cross-travel'){const r=this.run('waystone-travel',{id});if(r.ok){this.destination=null;this.rpg.close();this.rpg.api.camera('follow');}return true;}
 return false;}
 page(tab){const s=this.state,a=this.rpg.state,sim=this.sim,owned=id=>a.owned.includes(id),near=id=>X.near(sim,X.PLACES.find(q=>q.id===id));
 const section=(title,p,buttons='')=>'<article class="cross-card"><h3>'+title+'</h3><p>'+p+'</p>'+buttons+'</article>';
 if(tab==='atlas')return{title:'The roads you know',html:'<div class="cross-atlas-layout"><section class="cross-map-panel">'+mapSVG(sim)+'<p class="fineprint">Select a numbered marker or a named destination. Local routes walk through real collision; the map is not unrestricted teleportation.</p></section><section class="cross-atlas-list"><small>LOCAL PLACES · '+esc(sim.room==='crossing'?'BELLWEATHER':sim.room==='road'?'SUNWARD ROAD':!sim.room?'FIRSTLIGHT VALLEY':sim.room.toUpperCase())+'</small>'+points(sim).map((q,i)=>btn('<b>'+String(i+1).padStart(2,'0')+'</b><span><strong>'+esc(q.name)+'</strong><small>'+Math.round(distance(q,sim.state.player))+' paces · '+esc(q.kind||'place')+'</small></span>','cross-walk',q.id)).join('')+(sim.room==='crossing'&&s.met&&!s.clapperRevealed?section('Briar’s search','Use the charcoal track as your starting point. Ask Briar to seek, then follow on foot. Enemy targeting does not interrupt this explicit search command.',btn('Ask Briar to seek','cross-do','cross-seek',distance(sim.state.player,X.CLAPPER)>12||a.companion.mode!=='follow','primary')):'')+'<h3>Roads of Light</h3><p class="fineprint">Begin at a known waystone. No healing or rewards are granted by travel.</p>'+Object.entries(X.WAYSTONES).map(([id,q])=>{let reason=X.travelCheck(sim,id);return section(esc(q.name),esc(reason||'The road is open from your current waystone.'),btn(reason?'Unavailable':'Travel here','cross-travel',id,!!reason,'primary'));}).join('')+'</section></div>'};
 if(tab==='keeper')return{title:'Rowan · keeper of the watch bell',html:'<div class="cross-service"><div class="cross-portrait keeper">♧</div><div><small>CHAPTER IV · THE BELL ROAD</small><h3>'+(s.reward?'A sound carried home':s.complete?'The valley heard you':'A village waiting for an answer')+'</h3><p>'+(s.reward?'“Keep the clasp. Not as proof that you belong here. As a reminder that you already do.”':s.complete?'“I heard the bell before I saw you coming. For a moment I thought I was remembering it. Then the birds took wing.”':'“A road can open without anyone knowing where it leads. Our watch bell used to guide people through the wood. Find its clapper, and perhaps it can do that again.”')+'</p><p class="muted">'+(s.met?'The listening stone north of the square preserves its three-tone order. Briar may catch the clapper’s scent near the charcoal track.':'This is a new local quest after the beacon defense. You may explore the village before accepting.')+'</p><div class="button-row">'+btn('Help restore the bell','cross-do','cross-meet',s.met||!near('keeper'),'primary')+btn('Accept clasp & 18 sunmarks','cross-do','cross-reward',!s.complete||s.reward||!near('keeper'),'primary')+btn('View local map','open','atlas')+'</div></div></div>'};
 if(tab==='inn')return{title:'The Wayfarer’s Rest',html:'<div class="cross-service"><div class="cross-portrait inn">⌂</div><div><small>NELLA · PORCH SERVICE</small><h3>A place between journeys</h3><p>“Sit for a moment. The world will still need saving when you have eaten.”</p><p>A free rest restores health, stamina and your three tonics. It does not advance the story or undo soul choices. This porch is the inn’s working service point; its interior is not built yet.</p>'+btn('Rest & refill','cross-do','cross-rest',!near('inn')||X.hostile(sim),'primary')+'</div></div>'};
 if(tab==='town-shop')return{title:'Edda’s provisions',html:'<div class="cross-shop"><section><small>LOCAL MERCHANT</small><h3>'+a.coins+' sunmarks</h3><p>Buy deliberately, inspect in Character, and equip what suits your build. Exchanges use your actual inventory and cannot be undone by closing this menu.</p></section>'+section('Keeper’s coat','+9 guard · +30 maximum health. A unique weatherproof armor piece. Equipping capacity does not heal you.',btn(owned('keeper_coat')?'Already owned':'Buy · 24 sunmarks','cross-trade','coat',owned('keeper_coat')||a.coins<24||!near('shop'),'primary'))+section('Trail tonic','2 sunmarks each · '+a.tonics+' / 3 carried. Nella offers a free full rest nearby.',btn('Buy one · 2 sunmarks','cross-trade','tonic',a.coins<2||a.tonics>=3||!near('shop')))+section('Copper exchange','Two copper → three sunmarks. You carry '+a.ore+' copper.',btn('Sell 2 copper','cross-trade','copper',a.ore<2||!near('shop')))+section('Fresh sunberries','Two sunberries → one sunmark. You carry '+sim.state.sandbox.inventory.berry+'.',btn('Sell 2 berries','cross-trade','berries',sim.state.sandbox.inventory.berry<2||!near('shop')))+'</div>'};
 if(tab==='works')return{title:'The common works',html:'<div class="cross-projects"><p class="lead">Two voluntary commissions. Real supplies, visible changes, one reward each. Your home is never claimed or altered.</p>'+Object.entries(X.PROJECTS).map(([id,q])=>section(q.name,q.detail+'<br><br>'+Object.entries(q.materials).map(([k,n])=>esc(G.RealmSandbox.ITEMS[k].name)+': '+sim.state.sandbox.inventory[k]+' / '+n).join(' · '),btn(s.projects.includes(id)?'Completed':'Contribute these supplies','cross-project',id,s.projects.includes(id)||!near('board')||Object.entries(q.materials).some(([k,n])=>sim.state.sandbox.inventory[k]<n),'primary'))).join('')+'</div>'};
 if(tab==='listening')return{title:'The listening stone',html:section('Three tones, one road','<blockquote>Leaf takes the first breath.<br>Wave carries it onward.<br>Sun answers at last.</blockquote><p>The names, order and physical markers also work with sound muted. You never need to distinguish colors or pitch to solve the court.</p>',btn(s.inscription?'Kept in your journal':'Copy the inscription','cross-do','cross-inspect',s.inscription||!near('inscription'),'primary'))};
 if(tab==='waystone')return{title:'Bellweather waystone',html:section(s.attuned?'The route remembers you':'A road back to Firstlight','Attunement is free. It connects the village to your discovered anchors; it does not change your health, equipment or allegiance.',btn(s.attuned?'Already attuned':'Attune this waystone','cross-do','cross-attune',s.attuned||!near('waystone'),'primary')+btn('Open travel map','open','atlas'))};
 if(tab==='bells')return{title:'The watch-bell court',html:section(s.complete?'A voice for the valley':s.repaired?'Leaf → Wave → Sun':'The missing voice',s.complete?'The bell has answered. Return to Rowan; you may still play the resonators.':s.repaired?'Ring the three marked resonators in order. Stand beside each one to strike it. A mistaken note only restarts the short sequence; no items are lost.':'Recover the clapper and clear the prowler, tuner and Keeper. The repair costs the recovered quest part, not new materials.',btn(s.repaired?'Bell repaired':'Repair with the clapper','cross-do','cross-repair',s.repaired||!s.clapper||!X.ENEMIES.every(e=>a.defeated.includes(e.id))||!near('court'),'primary'))+'<div class="bell-controls">'+X.BELLS.map(b=>section(esc(b.name),(X.runtime(sim).tones.includes(b.id)?'Sounded in order.':'Move beside this resonator.')+' '+Math.round(distance(b,sim.state.player))+' paces.',btn('Ring '+b.id,'cross-ring',b.id,!s.repaired||!X.near(sim,b,2.3),'primary')+btn('Walk beside it','cross-walk','bell-'+b.id,!s.repaired))).join('')+'</div>'};
 return null;}
 journal(){const a=this.rpg.state,s=this.state;return'<div class="cross-journal"><header><small>CHAPTER IV · BELLWEATHER CROSSING</small><h3>The Bell Road</h3><p>One returning light reaches beyond your home. Find the village that heard it, give its watch bell a voice, and bring something back.</p></header><ol class="cross-steps">'+X.objectives(a).map(q=>'<li class="'+(q.done?'done':'')+'"><span>'+ (q.done?'✓':'○')+'</span><div><strong>'+esc(q.title)+'</strong><p>'+esc(q.detail)+'</p></div></li>').join('')+'</ol><div class="button-row">'+btn('Open local map · M','open','atlas')+btn('Beacon & soul choices','open','beacon')+btn('Older adventures','panel','explore')+'</div>'+(s.inscription?'<blockquote>Leaf takes the first breath. Wave carries it onward. Sun answers at last.</blockquote>':'')+'<p class="fineprint">The monastery, ruined kingdom and living-forest anchors remain future campaign routes. Bellweather is their first shared approach, not three completed new regions.</p></div>';}
 context(){const sim=this.sim,s=this.state,p=sim.state.player;if(sim.room==='road'&&this.rpg.state.beacon.complete&&distance(p,X.GATE)<2)return 'E · Bellweather Crossing · northern road';if(sim.room!=='crossing')return null;
 if(s.clapperRevealed&&!s.clapper&&distance(p,X.CLAPPER)<2.8)return'E · Recover the bronze clapper';
 for(const d of this.rpg.state.drops.map(id=>X.ENEMIES.find(e=>e.id===id)).filter(Boolean)){if(distance(p,d)<2.3)return'E · Collect encounter cache';}
 if(s.repaired){const b=X.BELLS.find(b=>distance(p,b)<2.3);if(b)return'E · Ring '+b.name;}
 const q=X.PLACES.map(q=>({...q,d:distance(p,q)})).filter(q=>q.d<2.65).sort((a,b)=>a.d-b.d)[0];if(q)return'E · '+q.name;
 if(s.met&&!s.clapperRevealed&&distance(p,X.CLAPPER)<12)return'M · Ask Briar to seek on the map · E inspects nearby clues';return'M · Bellweather map · TAB selects · 1 autoattack';}
 interact(){const sim=this.sim,a=this.rpg.state,s=this.state,p=sim.state.player;if(sim.room==='road'&&a.beacon.complete&&distance(p,X.GATE)<2){this.run('cross-enter');return true;}if(sim.room!=='crossing')return false;
 const drop=a.drops.map(id=>X.ENEMIES.find(e=>e.id===id)).filter(Boolean).find(d=>distance(p,d)<2.3);if(drop){this.run('loot',{id:drop.id});return true;}
 if(distance(p,X.CLAPPER)<2.5&&s.met&&!s.clapper){this.run(s.clapperRevealed?'cross-clapper':'cross-survey');return true;}
 if(s.repaired){const b=X.BELLS.map(b=>({...b,d:distance(p,b)})).filter(b=>b.d<2.3).sort((a,b)=>a.d-b.d)[0];if(b){this.run('cross-ring',{id:b.id});return true;}}
 const q=X.PLACES.map(q=>({...q,d:distance(p,q)})).filter(q=>q.d<2.8).sort((a,b)=>a.d-b.d)[0];if(q){if(q.id==='exit')this.run('cross-leave');else if(q.id==='thicket')this.run('cross-seek');else this.rpg.open(({keeper:'keeper',inn:'inn',shop:'town-shop',board:'works',workbench:'craft',waystone:'waystone',inscription:'listening',court:'bells'})[q.id]||'atlas');}else this.rpg.api.toast('Explore on foot. M marks services and the northern trail.');return true;}
 tick(){const sim=this.sim,a=this.rpg.state,s=this.state,r=X.runtime(sim),sel=T.selected(sim);
 if(this.uiRoom!==sim.room){this.uiRoom=sim.room;this.destination=null;this.toneSerial=r.toneSerial;}
 if(a.beacon.complete&&this.rpg.quest==='story'){const tasks=X.objectives(a),next=tasks.find(q=>!q.done)||{title:'The bell is ringing again',detail:'Return home, help with the common works, or test a new build. M opens discovered roads.'};$('#tracked-chapter').textContent='CHAPTER IV · THE BELL ROAD';$('#tracked-title').textContent=next.title;$('#tracked-detail').textContent=next.detail;$('#tracked-progress').textContent=tasks.filter(q=>q.done).length+' / '+tasks.length+' · Journal J';}
 if(sel?.custom==='bell'){ $('#target-rank').textContent='ELITE · HUSHBOUND KEEPER';if(sel.mode==='windup')$('#target-state').textContent=sel.ringMode==='outer'?'WIDE RING — step INTO its quiet center':'INNER STRIKE — step OUT of the circle';}
 if(sim.room==='crossing'){$('#skill-insight').title='Briar exposes an enemy; away from combat, seeks the lost clapper. The map also has an explicit Seek action.';if(s.met&&!s.clapperRevealed&&r.seek)$('#combat-help').textContent='Briar has a scent. Follow your companion into the north-west thicket.';}
 if(r.toneSerial!==this.toneSerial){this.toneSerial=r.toneSerial;const au=this.rpg.api.audio(),b=X.BELLS.find(b=>b.id===r.tone);if(b&&au?.enabled&&au.ctx?.state==='running'){for(const[ratio,amp]of[[1,.12],[2.01,.045],[2.72,.018]])au.note(b.note*ratio,au.ctx.currentTime,1.6,amp);}}
 const root=$('#cross-place-labels');root.replaceChildren();if(sim.room==='crossing'&&sim.state.settings.labels&&!this.rpg.dialog.open){const near=points(sim).filter(q=>q.id!=='thicket'||s.met).map(q=>({...q,d:distance(q,sim.state.player)})).filter(q=>q.d<10).sort((a,b)=>a.d-b.d).slice(0,3);for(const q of near){const pos=this.rpg.api.project(q.x,q.kind==='person'?3.5:2.8,q.z);if(!pos?.visible)continue;const el=document.createElement('span');el.textContent=q.name;el.style.left=pos.x+'px';el.style.top=pos.y+'px';root.append(el);}}
 const hint=$('#cross-route-hint');hint.hidden=!this.destination||this.destination.room!==sim.room||this.rpg.dialog.open;if(!hint.hidden){let d=distance(sim.state.player,this.destination);hint.textContent=(d<1?'Arrived · E to interact':'Walking · '+Math.round(d)+' paces')+' · '+this.destination.name;if(!sim.playerPath.length&&d>1){hint.textContent='Route stopped · '+this.destination.name;this.destination=null;}}
 }
}
G.RealmCrossingUI={CrossingUI,mapCanvas,mapSVG,points,projection};})(globalThis);
