/* Real local creative workspaces over the same simulation state. */
(function(G){'use strict';const X=RealmCreative,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
class Experience{
 constructor(hooks){this.h=hooks;this.selectedSlot='nw';this.source=null;this.playing=false;this.started=0;this.playingRevision=-1;this.loopSeconds=1;this.step=-1;this.scoreUndo=[];this.scoreRedo=[];this.dialog=document.getElementById('studio-dialog');this.lastFocus=null;
  document.getElementById('studio-open').onclick=()=>this.open();document.getElementById('studio-close').onclick=()=>this.close();
  this.dialog.addEventListener('cancel',()=>this.onClosed());this.dialog.addEventListener('close',()=>this.onClosed());
  this.dialog.addEventListener('click',e=>{let b=e.target.closest('[data-music]');if(b)this.musicAction(b);});
  this.dialog.addEventListener('change',e=>{let score=X.clone(this.sim.state.score);if(e.target.id==='score-title')score.title=e.target.value.trim()||'Untitled evening';else if(e.target.id==='score-tempo')score.bpm=+e.target.value;else if(e.target.id==='score-voice')score.voice=e.target.value;else return;let result=this.commit(score);if(!result.ok)this.render();});
  this.dialog.addEventListener('keydown',e=>{if(e.key==='Escape')return;e.stopPropagation();let cell=e.target.closest('[data-music="cell"]');if(cell&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();let i=+cell.dataset.index,dr={ArrowLeft:-1,ArrowRight:1,ArrowUp:-16,ArrowDown:16}[e.key],n=Math.max(0,Math.min(191,i+dr)),next=this.dialog.querySelector('[data-index="'+n+'"]');cell.tabIndex=-1;if(next){next.tabIndex=0;next.focus();}}});
  document.getElementById('score-import').addEventListener('change',async e=>{const owner=this.sim,revision=owner.state.scoreRevision;let f=e.target.files[0];if(!f)return;try{if(f.size>30000)throw Error('Score file exceeds 30 KB.');let s=X.validateScore(JSON.parse(await f.text()));if(this.sim!==owner||owner.state.scoreRevision!==revision)throw Error('The character or composition changed while the file was loading. Open the intended music desk and import again.');if(confirm('Replace the current composition? Export it first to keep a separate copy.')){this.commit(s);this.render();}}catch(err){this.h.toast('Score import refused: '+err.message);}finally{e.target.value='';}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)this.stop();});
 }
 get sim(){return this.h.sim();}
 open(){this.h.closePanel();this.lastFocus=document.activeElement;this.h.clearKeys();this.render();this.dialog.showModal();this.paint();document.getElementById('score-title').focus();}
 close(){this.dialog.close();}
 onClosed(){this.h.clearKeys();if(this.lastFocus&&document.contains(this.lastFocus))this.lastFocus.focus({preventScroll:true});}
 commit(score,history=true){let old=X.clone(this.sim.state.score);let result=this.h.command('set-score',{score,expectedRevision:this.sim.state.scoreRevision});if(result.ok){if(history){this.scoreUndo.push(old);if(this.scoreUndo.length>24)this.scoreUndo.shift();this.scoreRedo=[];}if(this.playing)this.play(false);this.paint();}return result;}
 paint(){if(!this.dialog.open)return;let s=this.sim.state;for(let b of this.dialog.querySelectorAll('[data-music="cell"]')){let row=+b.dataset.row,col=+b.dataset.col,val=row<8?s.score.melody[row][col]:row===8?s.score.bass[col]:s.score.drums[row-9][col];b.classList.toggle('on',!!val);b.setAttribute('aria-pressed',String(!!val));}document.getElementById('score-revision').textContent='Revision '+s.scoreRevision+' · '+(this.h.saved()?'saved on this device':'memory only — export to keep');let b=document.getElementById('music-play');b.textContent=this.playing?'■ Stop':'▶ Play loop';b.setAttribute('aria-pressed',String(this.playing));document.getElementById('music-state').textContent=this.playing?'Playing your score · '+s.score.bpm+' BPM':'Silent until you press Play';}
 render(){let s=this.sim.state.score,rows=[...X.LABELS,'Bass','Kick','Snare','Shaker'];let grid='<div class="step-head"><span>VOICE</span>'+Array.from({length:16},(_,i)=>'<span class="beat-label" data-beat="'+i+'">'+(i%2===0?(i/2+1):'·')+'</span>').join('')+'</div>';
 rows.forEach((name,r)=>{grid+='<div class="step-row '+(r===8?'bass':r>8?'percussion':'')+'"><span class="note-label">'+name+'</span>'+Array.from({length:16},(_,c)=>{let on=r<8?s.melody[r][c]:r===8?s.bass[c]:s.drums[r-9][c];return'<button data-music="cell" data-row="'+r+'" data-col="'+c+'" data-index="'+(r*16+c)+'" tabindex="'+(r===5&&c===0?0:-1)+'" class="note-cell '+(on?'on':'')+(c%4===0?' measure':'')+'" aria-label="'+name+', step '+(c+1)+'" aria-pressed="'+!!on+'"></button>';}).join('')+'</div>';});
 document.getElementById('studio-body').innerHTML='<div class="score-meta"><label>PIECE TITLE<input id="score-title" maxlength="64" value="'+esc(s.title)+'"></label><label>TEMPO<input id="score-tempo" type="number" min="50" max="160" step="1" value="'+s.bpm+'"></label><label>INSTRUMENT<select id="score-voice">'+X.VOICES.map(v=>'<option '+(s.voice===v?'selected':'')+' value="'+v+'">'+({felt:'Felt keys',glass:'Glass bells',plucked:'Plucked strings'}[v])+'</option>').join('')+'</select></label></div><div class="transport"><button id="music-play" data-music="play" class="primary">▶ Play loop</button><span id="music-state">Silent until you press Play</span><div class="transport-spacer"></div><button data-music="undo" aria-label="Undo score edit">↶</button><button data-music="redo" aria-label="Redo score edit">↷</button></div><div class="score-scroll" aria-label="Two-bar D minor sequencer"><div class="step-grid" role="group" aria-label="Musical notes and rhythm">'+grid+'</div></div><div class="score-caption">D MINOR · 16 EIGHTH-NOTE STEPS · 2 BARS <span>Click a cell. Arrow keys move; Space toggles.</span></div><div class="score-bottom"><div><div class="section-label">Original starting points</div><div class="row"><button data-music="preset" data-id="firstlight">Firstlight</button><button data-music="preset" data-id="rain">Rain on glass</button><button data-music="preset" data-id="lanterns">Lanterns</button><button data-music="clear">Clear</button></div></div><div><div class="section-label">Take your work with you</div><div class="row"><button data-music="wav">↓ WAV audio</button><button data-music="midi">↓ MIDI</button><button data-music="json">↓ Editable score</button><button data-music="import">Import</button></div></div></div><div class="score-footer"><span id="score-revision"></span><button data-music="stage">Take it to the amphitheatre →</button></div><p class="score-honesty">Your notes become real, locally synthesized audio. The residents do not compose this for you. No AI, samples, microphone access, or external services.</p>';
 // paint() also runs while the dialog is not open (initial render).
 let was=this.dialog.open;if(!was){let st=this.sim.state;document.getElementById('score-revision').textContent='Revision '+st.scoreRevision+' · kept with your local world';}
 this.paint();
 }
 musicAction(b){let s=X.clone(this.sim.state.score);switch(b.dataset.music){case'cell':{let row=+b.dataset.row,col=+b.dataset.col,arr=row<8?s.melody[row]:row===8?s.bass:s.drums[row-9];arr[col]=1-arr[col];this.commit(s);break;}case'play':this.playing?this.stop():this.play();break;case'preset':if(confirm('Use this original starting pattern? Undo is available for this session.')){this.commit(X.preset(b.dataset.id));this.render();}break;case'clear':if(confirm('Clear the notes and rhythm? Your title and tempo will remain.')){s.melody=s.melody.map(r=>r.map(()=>0));s.bass=s.bass.map(()=>0);s.drums=s.drums.map(r=>r.map(()=>0));this.commit(s);this.render();}break;case'undo':case'redo':{let undo=b.dataset.music==='undo',src=undo?this.scoreUndo:this.scoreRedo,dst=undo?this.scoreRedo:this.scoreUndo;if(!src.length){this.h.toast('No more score history in this session.');break;}let next=src.pop();dst.push(s);this.commit(next,false);this.render();break;}case'wav':this.exportAudio();break;case'midi':this.h.download(X.midi(s,2),this.filename()+'.mid','audio/midi');this.sim.event('export','You exported “'+s.title+'” as editable MIDI.');this.h.save();this.h.toast('MIDI exported. Import it into your DAW.');break;case'json':this.h.download(JSON.stringify(s,null,2),this.filename()+'.score.json','application/json');this.h.toast('Editable score exported.');break;case'import':document.getElementById('score-import').click();break;case'stage':this.close();this.h.navigate('stage');this.h.toast('At the stage, press E to invite the family and play your piece.');break;}}
 filename(){return(this.sim.state.score.title.replace(/[^a-z0-9 -]/gi,'').trim().replace(/\s+/g,'-')||'Firstlight-piece').slice(0,64);}
 play(record=true){this.stop();try{let audio=this.h.audio();if(!audio.enable())return false;let c=audio.ctx,pcm=X.renderPCM(this.sim.state.score,1,22050,true),buffer=c.createBuffer(2,pcm.left.length,pcm.sampleRate);buffer.copyToChannel(pcm.left,0);buffer.copyToChannel(pcm.right,1);let src=c.createBufferSource(),gain=c.createGain();src.buffer=buffer;src.loop=true;src.loopEnd=pcm.loopSeconds;gain.gain.value=.68;src.connect(gain);gain.connect(audio.master);this.started=c.currentTime+.045;this.loopSeconds=pcm.loopSeconds;this.source=src;this.gain=gain;this.playingRevision=this.sim.state.scoreRevision;this.playing=true;src.start(this.started);if(record){this.sim.event('music','You played “'+this.sim.state.score.title+'”, score revision '+this.playingRevision+'.');this.h.save();}this.paint();return true;}catch(e){this.stop();this.h.toast('Playback unavailable: '+e.message);return false;}}
 stop(){if(this.source){try{this.source.stop();this.source.disconnect();this.gain.disconnect();}catch(_){}}this.source=null;this.playing=false;this.step=-1;this.paint();}
 async exportAudio(){const owner=this.sim,score=X.clone(owner.state.score),filename=this.filename();let b=this.dialog.querySelector('[data-music="wav"]');if(b)b.disabled=true;try{await new Promise(r=>setTimeout(r,30));if(this.sim!==owner)throw Error('Character changed. Start the export again from their music desk.');let s=score,pcm=X.renderPCM(s,2,44100,true);this.h.download(X.wav(pcm),filename+'.wav','audio/wav');this.sim.event('export','You rendered “'+s.title+'” to a stereo WAV file.');this.h.save();this.h.toast('Stereo WAV rendered and exported. Your own notes, outside the realm.');}catch(e){this.h.toast('Audio export failed: '+e.message);}finally{if(b)b.disabled=false;}}
 tick(){if(this.playing){let c=this.h.audio().ctx;this.step=c?Math.floor(Math.max(0,c.currentTime-this.started)/this.loopSeconds*16)%16:-1;}else this.step=-1;this.sim.presentation=Object.assign(this.sim.presentation||{},{selectedSlot:this.h.panel()==='retreat'?this.selectedSlot:null,playing:this.playing,step:this.step});if(this.dialog.open)for(let el of this.dialog.querySelectorAll('[data-col],[data-beat]')){let c=+(el.dataset.col??el.dataset.beat);el.classList.toggle('current-step',this.playing&&c===this.step);}let pill=document.getElementById('now-playing');pill.hidden=!this.playing;document.getElementById('now-title').textContent=this.playing?this.sim.state.score.title:'';}
 renderPanel(name){if(name==='retreat'){let h=this.sim.state.retreat,item=h.items.find(i=>i.slot===this.selectedSlot);return '<p class="intro">A room you can actually change. Eight furniture positions, a clear doorway, and your own palette. Your layout travels with the exported world.</p><div class="row"><button data-action="retreat-walk">'+(this.sim.room==='retreat'?'You are inside':'Walk to your retreat')+'</button><button data-action="retreat-view">Inspect the room</button></div><div class="room-plan" role="group" aria-label="Choose a furniture position">'+X.SLOTS.map(s=>'<button data-action="slot" data-id="'+s.id+'" class="room-slot '+(this.selectedSlot===s.id?'selected':'')+'" style="left:'+(50+s.x*8.6)+'%;top:'+(50+s.z*10)+'%" aria-pressed="'+(this.selectedSlot===s.id)+'" aria-label="'+s.label+'">'+this.icon(h.items.find(i=>i.slot===s.id)?.kind)+'<small>'+s.label+'</small></button>').join('')+'<span class="room-door">ENTRY · KEPT CLEAR</span></div><div class="section-label">'+X.SLOTS.find(s=>s.id===this.selectedSlot).label+' · '+(item?X.FURNITURE[item.kind].name:'empty')+'</div><div class="furniture-list">'+Object.entries(X.FURNITURE).map(([k,f])=>'<button data-action="furnish" data-kind="'+k+'" aria-pressed="'+(item?.kind===k)+'">'+this.icon(k)+' <span>'+f.name+'</span></button>').join('')+'</div><div class="row" style="margin-top:12px"><button data-action="rotate-furniture">↻ Rotate</button><button data-action="remove-furniture">Remove</button><button data-action="layout-undo">↶ Undo</button><button data-action="layout-redo">↷ Redo</button></div><div class="section-label">Wall colour</div><div class="row">'+Object.entries(X.WALLS).map(([k,v])=>'<button class="palette" data-action="wall" data-value="'+k+'" aria-pressed="'+(h.wall===k)+'"><i style="background:#'+v.toString(16)+'"></i>'+k+'</button>').join('')+'</div><div class="section-label">Floor</div><div class="row">'+Object.keys(X.FLOORS).map(k=>'<button data-action="floor" data-value="'+k+'" aria-pressed="'+(h.floor===k)+'">'+k+'</button>').join('')+'</div><p class="legal">Layout revision '+h.revision+'. Undo/redo is session-local; accepted furniture is saved. No purchases or crafting currency.</p>';}
 if(name==='visitor'){let v=this.sim.state.visitor;return'<p class="intro">Choose the appearance of your local visitor. This is not a resident identity, an account, or a copy of your personal history.</p><label class="intro" for="visitor-name">DISPLAY NAME</label><input id="visitor-name" maxlength="32" value="'+esc(v.name)+'">'+[['skin',X.SKINS,'Skin'],['cloak',X.CLOAKS,'Cloak'],['hair',X.HAIR,'Hair']].map(([k,colors,title])=>'<div class="section-label">'+title+'</div><div class="swatch-row">'+colors.map((c,i)=>'<button style="--swatch:'+c+'" class="visitor-swatch" data-action="visitor-color" data-field="'+k+'" data-value="'+i+'" aria-label="'+title+' option '+(i+1)+'" aria-pressed="'+(v[k]===i)+'"></button>').join('')+'</div>').join('')+'<div class="divider"></div><p class="intro">Your name, colours, notebook, composition and retreat all travel in one exported world file.</p><button data-action="export">Export your world</button>';}
 return null;}
 icon(k){return{piano:'♬',shelf:'▥',sofa:'▰',desk:'▱',plant:'♧',lantern:'✦',easel:'▧',rug:'◇',cushions:'◈'}[k]||'＋';}
 decorate(home){let r=this.h.command('decorate',{home,expectedRevision:this.sim.state.retreat.revision});if(r.ok){this.h.redrawRoom();this.h.renderPanel();}return r;}
 action(b){let a=b.dataset.action,h=X.clone(this.sim.state.retreat),item=h.items.find(i=>i.slot===this.selectedSlot);switch(a){case'slot':this.selectedSlot=b.dataset.id;this.h.renderPanel();break;case'furnish':h.items=h.items.filter(i=>i.slot!==this.selectedSlot);h.items.push({slot:this.selectedSlot,kind:b.dataset.kind,rotation:item?.rotation||0});this.decorate(h);break;case'rotate-furniture':if(item){item.rotation=(item.rotation+1)%4;this.decorate(h);}break;case'remove-furniture':h.items=h.items.filter(i=>i.slot!==this.selectedSlot);this.decorate(h);break;case'layout-undo':case'layout-redo':{let r=this.h.command(a);if(r.ok){this.h.redrawRoom();this.h.renderPanel();}break;}case'wall':h.wall=b.dataset.value;this.decorate(h);break;case'floor':h.floor=b.dataset.value;this.decorate(h);break;case'retreat-walk':this.h.navigate('retreat');this.h.closePanel();break;case'retreat-view':if(this.sim.room==='retreat'){this.h.closePanel();}else this.h.action('retreat');break;case'visitor-color':{let v=X.clone(this.sim.state.visitor);v[b.dataset.field]=+b.dataset.value;this.h.command('appearance',{visitor:v});this.h.renderPanel();break;}default:return false;}return true;}
 changed(e){if(e.target.id==='visitor-name'){let v=X.clone(this.sim.state.visitor);v.name=e.target.value.trim()||'Visitor';this.h.command('appearance',{visitor:v});}}
}
G.RealmExperience={Experience};
})(globalThis);
