(function(G){'use strict';
const P=G.RealmPursuit;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,id='',disabled=false)=>`<button data-rpg="${action}" data-id="${esc(id)}" ${disabled?'disabled':''}>${label}</button>`;
class PursuitUI{
 constructor(ui){this.ui=ui;this.selected=null;}
 action(el){const act=el.dataset.rpg,id=el.dataset.id,a=this.ui.state;if(!['pursuit-pin','pursuit-start','pursuit-sample','pursuit-claim','pursuit-fit'].includes(act))return false;
  let p={}; if(act==='pursuit-pin')p={weapon:id||null}; if(act==='pursuit-start')p={after:a.pursuit.claimed}; if(act==='pursuit-claim')p={run:a.pursuit.active?.id}; if(act==='pursuit-fit')p={weapon:id.split(':')[0],step:Number(id.split(':')[1])};
  if(act==='pursuit-route'){const q=id==='oren'?G.RealmStarter.OREN:G.RealmStarter.GATE;this.ui.close();this.ui.api.walkLocal(q.x,q.z);return true;}
  if(act==='pursuit-craft'){this.ui.close();this.ui.run('arsenal-craft',{id});return true;}
  const r=this.ui.run(act,p);if(r?.text)this.ui.api.toast(r.text);this.ui.paint();return true;
 }
 page(tab){return tab==='pursuit'?{title:'Field guide',html:this.html()}:null;}
 html(){const a=this.ui.state,p=a.pursuit||{claimed:0,active:null,pinned:null,fittings:{}};const cat=P.catalogue(a)||[],pin=cat.find(x=>x.id===p.pinned),run=p.active;
  const card=x=>{const c=P.compare(a,x.id)||{},fit=p.fittings[x.id]||0,n=P.recipe(a,x.id),w=c.beforeWeapon||{},after=c.afterWeapon||{},cost=n?.materials||{},have=(k)=>k==='ore'?a.ore:k==='coins'?a.coins:(this.ui.sim.state.sandbox.inventory[k]||0),enough=n&&Object.entries(cost).every(([k,v])=>have(k)>=v)&&(have('ore')>=n.ore)&&(have('coins')>=n.coins),atBench=!!(G.RealmArsenal&&G.RealmArsenal.atBench(this.ui.sim));let action=x.owned&&n?btn(`Fit ${n.name}`,'pursuit-fit',`${x.id}:${fit+1}`,!enough||!atBench):x.owned?'<span class="fineprint">Two fittings complete</span>':n?btn(n.type==='forge'?'Craft at Oren':'Craft prerequisite','pursuit-craft',n.id,!enough):'';return `<article class="guide-gear ${pin?.id===x.id?'is-pinned':''}"><div><small>${esc(x.style)} · tier ${esc(x.tier)}</small><h4>${esc(x.name)}</h4><p>${x.owned?'Owned':esc(x.source?.label||'Source unavailable')} ${x.source?.requires?` · requires ${esc(x.source.requires)}`:''}</p></div><div class="guide-stats"><span>Equipped <b>${w.attack??'—'} atk</b></span><span>Selected <b>${c.selected?.attack??'—'} atk</b></span><span>Next <b>${c.next?.attack??'—'} atk</b></span><span>Reach <b>${w.reach??'—'}</b></span><span>Cadence <b>${w.cooldown??'—'}</b></span><span>Stamina <b>${w.stamina??'—'}</b></span><span>Guard <b>${c.current?.defense??'—'}</b></span><span>Health <b>${c.current?.maxHP??'—'}</b></span><span>Socket <b>${c.socket||'retained'}</b></span><span>Oren temper <b>${fit?'retained':'—'}</b></span></div><p class="fineprint">${n?`Next cost: ${n.ore||0} ore · ${n.coins||0} sunmarks · ${Object.entries(cost).map(([k,v])=>v+' '+k).join(', ')||'no fibre'}. ${enough?'Materials ready':'Gather materials or run a survey'}.`:''}</p><div class="button-row">${x.pinnable?btn(pin?.id===x.id?'Unpin':'Pin project','pursuit-pin',pin?.id===x.id?'':x.id):'<span class="fineprint">Story source · once only</span>'}${action}</div></article>`;};
  return `<div class="pursuit-guide"><div class="guide-intro"><small>FIELD GUIDE · ONE PINNED PROJECT</small><h3>Find an upgrade worth hunting</h3><p>Choose one real weapon, follow its recorded source, and compare the next fitting before spending anything. Walk to Oren for craft and claim; Gather materials or run a survey when supplies are missing.</p></div><section class="guide-project"><div class="guide-project-head"><div><small>PROJECT TRACKER</small><h4>${pin?esc(pin.name):'No equipment pinned'}</h4></div><strong>${p.claimed} survey${p.claimed===1?'':'s'} paid</strong></div>${run?`<p class="guide-active"><b>Riverbank survey ${esc(run.id.split('/').pop())}</b> · defeat west and east survey skitters, then collect west and east samples. Oren is paused until claim. Undefeated skitters recover on reload.</p>${btn('Walk to riverbank','pursuit-route','riverbank')}${btn('Return to Oren to claim','pursuit-route','oren')}${btn('Claim 3 ore · 4 sunmarks · 2 fibre','pursuit-claim','',!P.complete(a)||!this.ui.api.walkLocal)}`:btn('Start repeatable riverbank survey','pursuit-start','',!!run)}<p class="fineprint">Every completed run pays exactly 3 copper ore, 4 sunmarks and 2 meadow fibre, with 0 XP. Partial progress saves and resumes; two finite fittings per weapon.</p></section><section class="guide-list">${cat.map(card).join('')}</section></div>`;
 }
}
G.RealmPursuitUI={PursuitUI};
})(globalThis);

