/* Human controls for the local sandbox. The domain rechecks every action. */
(function(G){'use strict';const S=G.RealmSandbox,C=G.RealmCore;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=id=>'<i class="item-icon" style="--item:'+S.ITEMS[id].color+'">'+S.ITEMS[id].glyph+'</i>';
class SandboxUI{
 constructor(api){this.api=api;this.auto=null;this.build=null;this.rotation=0;this.cell=null;this.fxTime=0;this.lastRevision=-1;this.lastUI=0;this.lastCursor=0;
  $('#journey-open').onclick=()=>api.openPanel('journey');$('#build-exit').onclick=()=>this.endBuild();$('#build-rotate').onclick=()=>this.rotate();$('#build-place').onclick=()=>this.place();$('#build-remove').onclick=()=>{this.build='reclaim';this.refreshGhost();this.paint();};
 }
 get sim(){return this.api.sim();}get state(){return this.sim.state.sandbox;}
 run(type,payload={}){if(this.sim.paused){this.api.toast('Resume the world before changing it.');return{ok:false};}let r=this.sim.sandboxCommand('play-'+Date.now()+'-'+(++this.api.sequence.n),type,payload);if(r.ok&&!r.duplicate){this.api.save();if(type==='gather'){let n=S.NODES.find(n=>n.id===payload.node);this.sim.sandboxFx={id:n.id,x:n.x,z:n.z,time:this.api.time()};}if(type==='place'||type==='bridge')this.sim.sandboxFx={id:'build',x:this.sim.state.player.x,z:this.sim.state.player.z,time:this.api.time()};}this.api.toast(r.text||'No change.');this.paint();this.refreshGhost();if(['pack','craft','build','journey'].includes(this.api.panel()))this.api.renderPanel();return r;}
 nearResource(){if(this.sim.room)return null;let best=null,d=S.REACH;for(let n of S.NODES){if(n.wild&&!this.state.bridge)continue;let v=Math.hypot(n.x-this.sim.state.player.x,n.z-this.sim.state.player.z);if(v<d){best=n;d=v;}}return best;}
 nearbyCrop(){if(this.sim.room)return null;return this.state.placed.find(p=>p.kind==='bed'&&Math.hypot(S.worldCell(p.gx,p.gz).x-this.sim.state.player.x,S.worldCell(p.gx,p.gz).z-this.sim.state.player.z)<=S.REACH);}
 context(){if(this.sim.room)return null;let n=this.auto?S.NODES.find(n=>n.id===this.auto):this.nearResource();if(n&&Math.hypot(this.sim.state.player.x-n.x,this.sim.state.player.z-n.z)<=S.REACH){let r=this.state.nodes.find(r=>r.id===n.id);return r.hp?'Gather '+S.ITEMS[n.kind].name+' · '+r.hp+' strength':'Regrowing · '+Math.max(0,Math.ceil(r.readyAt-this.state.elapsed))+'s';}
 let crop=this.nearbyCrop();if(crop)return !crop.crop?'Plant a sunberry seed':crop.crop.stage==='seeded'?'Water the growing bed':crop.crop.stage==='ripe'?'Harvest sunberries':'Sunberries growing';
 if(!this.state.bridge&&Math.hypot(this.sim.state.player.x,this.sim.state.player.z+21.3)<3.5)return 'Restore crossing · 8 planks + 6 stone';
 if(S.station(this.state,this.sim.state.player))return 'Open the crafting workbench';return null;}
 interact(){if(this.sim.room)return false;if(this.build&&this.cell){this.place();return true;}let n=this.nearResource();if(n){this.run('gather',{node:n.id});return true;}let crop=this.nearbyCrop();if(crop){this.run('crop',{object:crop.id});return true;}if(!this.state.bridge&&Math.hypot(this.sim.state.player.x,this.sim.state.player.z+21.3)<3.5){this.run('bridge');return true;}if(S.station(this.state,this.sim.state.player)){this.api.openPanel('craft');return true;}return false;}
 stopAuto(){this.auto=null;}
 go(x,z){this.endBuild();this.auto=null;return this.api.walk(x,z);}
 seek(id){let p=this.sim.state.player,nodes=S.NODES.filter(n=>n.kind===id&&(!n.wild||this.state.bridge)&&this.state.nodes.find(r=>r.id===n.id).hp>0).sort((a,b)=>Math.hypot(p.x-a.x,p.z-a.z)-Math.hypot(p.x-b.x,p.z-b.z));if(!nodes.length){this.api.toast(id==='crystal'&&!this.state.bridge?'Restore the crossing to reach moon crystal.':'These resources are regrowing. Try another activity.');return;}this.visitNode(nodes[0]);}
 visitNode(n){this.endBuild();if(n.wild&&!this.state.bridge){this.api.toast('Restore the crossing first.');return;}let best=null,p=this.sim.room?this.sim.returnPos:this.sim.state.player;for(let i=0;i<12;i++){let a=i*Math.PI/6,q={x:n.x+Math.cos(a)*1.7,z:n.z+Math.sin(a)*1.7};if(C.walkable(q.x,q.z,{id:'outdoors',sandbox:this.state})&&(!best||Math.hypot(q.x-p.x,q.z-p.z)<Math.hypot(best.x-p.x,best.z-p.z)))best=q;}
 if(best&&this.api.walk(best.x,best.z)){this.auto=n.id;this.api.closePanel();this.api.toast('Walking to '+S.ITEMS[n.kind].name.toLowerCase()+'. Gathering begins on arrival; move to cancel.');}}
 startBuild(kind){this.auto=null;this.build=kind;this.cell=null;this.sim.presentation=this.sim.presentation||{};this.sim.presentation.buildMode=true;this.api.closePanel();$('#build-toolbar').hidden=false;this.refreshGhost();this.api.toast('Choose a marked Wildwood tile. T rotates; Escape leaves building.');this.paint();}
 endBuild(){this.build=null;this.cell=null;if(this.sim.presentation){this.sim.presentation.buildMode=false;this.sim.presentation.blueprint=null;}$('#build-toolbar').hidden=true;}
 rotate(){this.rotation=(this.rotation+1)%4;this.refreshGhost();this.paint();}
 refreshGhost(){this.sim.presentation=this.sim.presentation||{};if(!this.build||!this.cell){this.sim.presentation.blueprint=null;$('#build-place').disabled=true;return;}const{gx,gz}=this.cell;let candidate=this.build==='reclaim'?null:S.placement(this.state,this.sim.state.player,this.sim.room,this.build,gx,gz,this.rotation);const valid=this.build==='reclaim'?this.state.placed.some(o=>o.gx===gx&&o.gz===gz):typeof candidate==='object'&&this.state.inventory[this.build]>0;this.sim.presentation.blueprint={...(typeof candidate==='object'&&candidate||{}),gx,gz,kind:this.build,rotation:this.rotation,level:candidate?.level||1,valid};$('#build-place').disabled=!valid;}
 cursor(point){if(!this.build||this.sim.room)return;let cell=S.cellAt(point.x,point.z);if(this.cell?.gx===cell.gx&&this.cell?.gz===cell.gz)return;this.cell=cell;this.refreshGhost();}
 worldClick(point,touch=false){if(this.sim.room)return false;if(this.build){let c=S.cellAt(point.x,point.z),same=this.cell&&this.cell.gx===c.gx&&this.cell.gz===c.gz;this.cell=c;this.refreshGhost();if(!touch||same)this.place();return true;}let n=S.NODES.filter(n=>Math.hypot(n.x-point.x,n.z-point.z)<1.05).sort((a,b)=>Math.hypot(a.x-point.x,a.z-point.z)-Math.hypot(b.x-point.x,b.z-point.z))[0];if(n){this.visitNode(n);return true;}this.auto=null;return false;}
 place(){if(!this.cell){this.api.toast('Choose a homestead tile first.');return;}if(this.build==='reclaim')this.run('reclaim',this.cell);else this.run('place',{...this.cell,kind:this.build,rotation:this.rotation});}
 key(k){if(k==='7'||k==='i'){this.api.openPanel('pack');return true;}if(k==='c'){this.api.openPanel('craft');return true;}if(k==='b'){this.api.openPanel('build');return true;}if(k==='j'){this.api.openPanel('journey');return true;}if(k==='t'&&this.build){this.rotate();return true;}if(k==='escape'&&this.build){this.endBuild();return true;}return false;}
 action(b){const act=b.dataset.action,id=b.dataset.id;if(!act?.startsWith('sb-'))return false;
 if(act==='sb-gather')this.seek(id);
 if(act==='sb-craft')this.run('craft',{recipe:id});
 if(act==='sb-build'){if(!this.state.bridge){this.api.toast('Restore the northern crossing to open your building site.');return true;}this.startBuild(id);}
 if(act==='sb-go'){if(id==='bench')this.go(11,9);if(id==='crossing')this.go(0,-21.3);if(id==='wild'){if(this.state.bridge)this.go(0,-33);else this.api.toast('Restore the northern crossing first.');}this.api.closePanel();}
 if(act==='sb-repair')this.run('bridge');
 if(act==='sb-open')this.api.openPanel(id);
 if(act==='sb-reclaim')this.startBuild('reclaim');
 if(act==='sb-cell'){if(!this.build){this.api.toast('Choose a building piece first, then select a tile.');return true;}this.cell={gx:Number(b.dataset.gx),gz:Number(b.dataset.gz)};this.refreshGhost();this.api.closePanel();this.paint();}
 if(act==='sb-crop')this.run('crop',{object:Number(id)});
 return true;}
 renderPanel(name){const s=this.state,btn=(label,act,id,disabled=false)=>'<button data-action="sb-'+act+'" data-id="'+(id||'')+'" '+(disabled?'disabled':'')+'>'+label+'</button>';
 if(name==='pack')return'<p class="intro">What you gather stays in this world. Click a resource in the valley to walk over and harvest; moving cancels the action. Tools do not break.</p><div class="pack-grid">'+Object.entries(S.ITEMS).map(([id,v])=>'<div class="pack-item '+(s.inventory[id]?'':'empty')+'">'+icon(id)+'<strong>'+s.inventory[id]+'</strong><span>'+v.name+'</span></div>').join('')+'</div><div class="section-label">Find materials</div><div class="row">'+['wood','stone','fiber','crystal'].map(id=>btn('Find '+S.ITEMS[id].name,'gather',id)).join('')+'</div><div class="divider"></div><div class="row">'+btn('Craft something','open','craft')+btn('Your field guide','open','journey')+'</div><p class="legal">No weight penalty, hunger timer, real money or online inventory. Export your world JSON to keep a portable backup.</p>';
 if(name==='craft')return'<div class="craft-status '+(S.station(s,this.sim.state.player)&&!this.sim.room?'ready':'')+'">'+(S.station(s,this.sim.state.player)&&!this.sim.room?'AT A WORKBENCH':'FIELD CRAFTING')+'</div><p class="intro">Cut, shape, and make. Recipes spend the displayed materials only on success. Tool, bench and lantern recipes need a nearby workbench.</p><div class="row">'+btn('Walk to Oren’s bench','go','bench')+btn('Backpack','open','pack')+'</div>'+S.RECIPES.map(r=>{let enough=S.checkCost(s,r.cost),bench=!r.station||S.station(s,this.sim.state.player)&&!this.sim.room,owned=r.unique&&s.inventory[r.id];return'<article class="recipe-card"><div class="card-header">'+icon(r.id)+'<div><h3>'+S.ITEMS[r.id].name+'</h3><small>'+(r.station?'Workbench recipe':'Anywhere outside')+' · makes '+r.out+'</small></div><span class="badge">'+(s.inventory[r.id]||0)+' kept</span></div><p>'+r.desc+'</p><div class="ingredients">'+Object.entries(r.cost).map(([id,n])=>'<span class="'+(s.inventory[id]>=n?'met':'missing')+'">'+icon(id)+s.inventory[id]+'/'+n+'</span>').join('')+'</div>'+btn(owned?'Tool equipped':!bench?'Workbench needed':'Craft '+r.out,'craft',r.id,!!owned||!enough||!bench||!!this.sim.room)+'</article>';}).join('');
 if(name==='build')return'<p class="intro">A 7 × 7 homestead on Wildwood Reach. Lay decks, stack stone three high, place furnishings and grow a garden. The central lane stays open. Reclaim returns the crafted item.</p><div class="row">'+btn(s.bridge?'Walk to Wildwood':'Walk to the broken crossing','go',s.bridge?'wild':'crossing')+btn('Craft pieces','open','craft')+'</div><div class="furniture-list sandbox-blueprints">'+S.BUILDABLE.map(id=>'<button data-action="sb-build" data-id="'+id+'" '+(!s.inventory[id]?'disabled':'')+'>'+icon(id)+'<span>'+S.ITEMS[id].name+'</span><small>'+s.inventory[id]+' in pack</small></button>').join('')+'</div><div class="row">'+btn('Reclaim placed object','reclaim','')+'</div><p class="intro">Mouse: move over a tile to preview, click to place. Touch: tap a tile, then Place. Rotate with T. Building checks your position and refuses blocked exits.</p><div class="section-label">Accessible tile selection</div><div class="homestead-plan" role="group" aria-label="Homestead build tiles">'+Array.from({length:49},(_,i)=>{let gx=i%7-3,gz=Math.floor(i/7)-3,count=s.placed.filter(p=>p.gx===gx&&p.gz===gz).length;return'<button data-action="sb-cell" data-gx="'+gx+'" data-gz="'+gz+'" title="Tile '+gx+', '+gz+'" aria-label="Tile '+gx+', '+gz+(gx===0?', open lane':'')+'">'+(count||gx===0?'·':'◇')+'</button>';}).join('')+'</div>';
 if(name==='journey')return'<p class="intro">An optional first adventure. You can always keep composing, decorating and exploring instead. The village stays protected; the new shore is yours to build.</p>'+S.objectives(s).map((m,i)=>'<article class="journey-card '+(m.done?'complete':'')+'"><span class="journey-number">'+(m.done?'✓':String(i+1).padStart(2,'0'))+'</span><div><h3>'+m.title+'</h3><p>'+m.detail+'</p></div></article>').join('')+'<div class="section-label">Your next destination</div><div class="row">'+btn('Find timber','gather','wood')+btn('Find stone','gather','stone')+btn('Open crafting','open','craft')+btn('Northern crossing','go','crossing')+(s.bridge?btn('Wildwood homestead','go','wild'):btn('Restore crossing','repair',''))+'</div><div class="notice" style="margin-top:16px">Resource nodes regrow on active simulation time. Pausing, closing the page, or changing the day slider does not secretly advance growth.</div>';
 return null;}
 paint(){const s=this.state;$('#pocket').innerHTML=['wood','stone','plank','crystal'].map(id=>'<span title="'+S.ITEMS[id].name+'">'+icon(id)+'<b>'+s.inventory[id]+'</b></span>').join('');let list=S.objectives(s),done=list.filter(m=>m.done).length,next=list.find(m=>!m.done);$('#journey-title').textContent=next?next.title:'A place you made yourself';$('#journey-detail').textContent=next?next.detail:'Keep building. Your music, home and garden are waiting.';$('#journey-progress').innerHTML=list.map(m=>'<i class="'+(m.done?'done':'')+'"></i>').join('');$('#journey-open').setAttribute('aria-label','Field guide: '+done+' of 6 milestones');if(this.build){$('#build-name').textContent=this.build==='reclaim'?'Reclaim topmost object':S.ITEMS[this.build].name+' · '+s.inventory[this.build]+' left';$('#build-rotate').textContent='Rotate '+this.rotation*90+'° · T';}}
 tick(){const s=this.state;this.sim.presentation=this.sim.presentation||{};this.sim.presentation.resource=this.auto||this.nearResource()?.id||null;this.sim.presentation.buildMode=!!this.build;if(this.build&&this.cell)this.refreshGhost();
 if(this.auto&&!this.sim.paused&&!this.sim.room&&!this.sim.playerPath.length){const n=S.NODES.find(n=>n.id===this.auto),state=s.nodes.find(n=>n.id===this.auto);if(!n||!state.hp||Math.hypot(n.x-this.sim.state.player.x,n.z-this.sim.state.player.z)>S.REACH)this.auto=null;else if(s.elapsed>=s.cooldownUntil){let r=this.run('gather',{node:n.id});if(!r.ok||!state.hp)this.auto=null;}}
 if(s.revision!==this.lastRevision){this.lastRevision=s.revision;this.paint();this.refreshGhost();}
 }
 reset(){this.endBuild();this.auto=null;this.lastRevision=-1;this.paint();}
}
G.RealmSandboxUI={SandboxUI};
})(globalThis);
